TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += circle.db
DB += dbExample1.db
DB += dbExample2.db
DB += testiocVersion.db
DB += dbSubExample.db
DB += random_num.template
DB += random_num.sub
DB += user.substitutions

DB += bo.template
DB += mbbi.template
DB += ai.template
DB += stringin.template
DB += sine.template
DB += simulation.sub

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

