TOP = ../..
include $(TOP)/configure/CONFIG

LIBRARY     += glassManPS
DBDINC      += gmpsRecord
DBD         += gmpsRecord.dbd
DBD         += devFj01n120.dbd
DBD	    += devFj10n12.dbd
DBD	    += devEt50p40.dbd
DBD	    += devFj50n02.4.dbd
DBD	    += devFj50p02.4.dbd

glassManPS_SRCS += devFj01n120.c devFj10n12.dbd devEt50p40.dbd devFj50n02.4.c devFj50p02.4.c gmpsRecord.c funGmps.c

include $(TOP)/configure/RULES

