/**
 * Project Name : FPS - Fast Protection System
 * 
 * Copyright 2018 by Intech Telecom Corporation, Inc
 * All right reserved.
 * 
 * Project Description :    To protect the accelerators from sudden beam loss during RAON accelerator operation, 
 *                          we want to develop a Fast Protection System (FPS) based on Field Programmable Gate Array (FPGA).
 *                          Prior to the fabrication of the FPS including the entire range of the RAON accelerator, 
 *                          one chain consisting of one mitigation node and seven acquisition nodes is to be tested.
 *                          Monitoring and operation of this system is performed in the CS-Studio (CSS) Operator Interface (OPI) 
 *                          environment and the data is transferred to the central control system through the EPICS IOC.
 */

/** 
 * File name : intech_global.h
 *
 * File Description : Includes information that includes the header file included in the functions generated by the intra-terecom.
 *
 * Author : Kim Jong In (jongink@imcu.co.kr)
 * Dept : Software
 * Created Date : 2018.07.xx
 * Version	: .
 */

#ifndef __INTECH_GLOBAL_H
#define __INTECH_GLOBAL_H

#include <fcntl.h>
#include <math.h>
#include <stdio.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <vector>
#include <sys/mman.h>
#include <sys/time.h>
#include <sys/ioctl.h>

#include <algorithm>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <iterator>
#include <set>
#include <sstream>

/* epics header */
#include <dbCommon.h>
#include <epicsEvent.h>
#include <epicsExit.h>
#include <epicsExport.h>
#include <epicsMutex.h>
#include <epicsString.h>
#include <epicsThread.h>
#include <epicsTypes.h>
#include <epicsTime.h>
#include <epicsTimer.h>
#include <iocsh.h>
#include <registryFunction.h>

/* fps header */
#include <asynPortDriver.h>
#include "intech_define.h"
#include "mitiFPSDriver.h"


#endif