TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this

DB += danfysikMps9700.template
DB += danfysikMps8700_scpi.template
#DB += danfysikUnit.template
#DB += danfysikMps9700_scpi.template
#DB += danfysik.sub
#DB += danfysik_SW1.sub
#DB += danfysik_SW2.sub
#DB += MGField2Cur.vdb

DB += dbAutoRampup.db
DB += MGField2Cur.vdb
DB += MGField2Cur_SW1.vdb
DB += MGField2Cur_SW2.vdb
DB += MGField2Cur_Q1P.vdb
DB += MGField2Cur_Q2P.vdb
DB += MGField2Cur_Q3.vdb  
DB += MGField2Cur_Q4.vdb
DB += MGField2Cur_Q5.vdb
DB += MGField2Cur_Q6.vdb
DB += MGField2Cur_Q7P.vdb
DB += MGField2Cur_Q8.vdb 
DB += MGField2Cur_Q9.vdb
DB += MGField2Cur_Q10P.vdb
DB += MGField2Cur_Q11P.vdb
DB += MGField2Cur_Q12P.vdb
DB += MGField2Cur_Q13P.vdb
DB += MGField2Cur_Q14P.vdb
DB += MGField2Cur_Q15P.vdb
DB += MGField2Cur_LQP.vdb
DB += MGField2Cur_SQP.vdb
DB += MGField2Cur_H1.vdb
DB += MGField2Cur_H2P.vdb

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

