TOP = ../..
include $(TOP)/configure/CONFIG

LIBRARY += timeStamp

DBD += timestampDevSoft.dbd
DBD += timestampRecord.dbd
DBDINC += timestampRecord


timeStamp_SRCS += timestampRecord.c
timeStamp_SRCS += devTimestampSoft.c

include $(TOP)/configure/RULES
