# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVASRV_SRC)/dbGroup

DBD += dbGroup.dbd

INC += dbGroup.h
INC += pvValue.h

LIBSRCS += pvValue.cpp
LIBSRCS += dbGroupRegister.cpp
LIBSRCS += dbGroupProvider.cpp
LIBSRCS += dbGroup.cpp
LIBSRCS += dbGroupGet.cpp
