TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db
DB += PressR.template
DB += PressR_1.sub
DB += cooldown04_1.sub
DB += CVValve.template
DB += Additional.sub

#DB += press.template
#DB += PressR.sub
#DB += ai.template
#DB += bi.template
#DB += longin.template
#DB += stringin.template
#DB += cd_ai.template
#DB += FlowR.sub
#DB += LevelR.sub
#DB += TempR.sub
#DB += Additional.sub
#DB += CVValve.template
#DB += CVValve_OM14_step6.template
#DB += XVValve.template
#DB += Heater.template
#DB += cooldown03.sub
#DB += cooldown04.sub
#DB += cooldown12.sub
#DB += cooldown14.sub
#DB += cooldown15.sub
#DB += cooldown21.sub
#DB += cooldown51.sub
#DB += cooldown52.sub
#DB += cooldown53.sub
#DB += templhePAK.template
#DB += subhePAK.sub
#DB += Waveform.template
#DB += subHePAKWF.sub
#DB += ASubWFParam_QWR_VBx02.template
#DB += ASubWFParam_QWR.template
#DB += ASubWFParam_HWR.template
#DB += subASubWFParam.sub
#DB += PT7002Calc.template
#DB += subPT7002Calc.sub
#DB += MFR7501_7002HWR.template
#DB += subMFR7501_7002HWR.sub
#DB += MFR7503_QWR.template
#DB += subMFR7503_QWR.sub
#DB += MFRColdHe.template
#DB += subMFRColdHe.sub

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

