TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db
DB += waveform_macro.template
DB += ai_macro.template
DB += bi_macro.template
DB += bi_word.template
DB += bo_word.template
DB += bi_bit.template
DB += bo_bit.template
DB += longin.template
DB += longout.template
DB += longinInt32.template
DB += longoutInt32.template
DB += mbbiDirect.template
DB += mbboDirect.template
DB += ai.template
DB += ai_average.template
DB += ao.template
DB += aiFloat64.template
DB += aoFloat64.template
DB += aiFloat64_sim.template
DB += check_condition_press.vdb
DB += check_condition_heline_circulation.vdb
#DB += calcout.template
#DB += cd_ao.template
DB += cd_ai.template
#DB += cd_ai_presseval.template
DB += cd_ai_pressevalOM0.3.template
DB += pressure_eval.vdb
DB += PressEval.vdb
DB += PressEval2.vdb
DB += calcout_ao.template
#DB += calcout_OM0_3_ao.template
DB += calcout_OM0.3_ao.template
DB += Condition_Process_Fantout.vdb
DB += CDFanoutTest.vdb
DB += fanout_db_field.vdb
DB += TempEval.vdb
DB += testwaveform.vdb
DB += TestCountPV.vdb
DB += OM031AdditionalPV.vdb
DB += OM032AdditionalPV.vdb
DB += OM033AdditionalPV.vdb
DB += OM034AdditionalPV.vdb
DB += OM035AdditionalPV.vdb
DB += OM036-1AdditionalPV.vdb
DB += OM036-2AdditionalPV.vdb
DB += OM036-3AdditionalPV.vdb
DB += OM036-4AdditionalPV.vdb
DB += OM036-5AdditionalPV.vdb
DB += OM036-6AdditionalPV.vdb
DB += OM036-7AdditionalPV.vdb
DB += OM037AdditionalPV.vdb
DB += OM038AdditionalPV.vdb
DB += OM041_2AdditionalPV.vdb
DB += OM043-1AdditionalPV.vdb
DB += OM043-2AdditionalPV.vdb
DB += OM043-3AdditionalPV.vdb
DB += OM043-4AdditionalPV.vdb
DB += OM043-5AdditionalPV.vdb
DB += OM043-6AdditionalPV.vdb
DB += OM044AdditionalPV.vdb
DB += OM121AdditionalPV.vdb
DB += OM122AdditionalPV.vdb
DB += OM141AdditionalPV.vdb
DB += OM142AdditionalPV.vdb
DB += OM143AdditionalPV.vdb
DB += OM144AdditionalPV.vdb
DB += OM145AdditionalPV.vdb
DB += OM146AdditionalPV.vdb
DB += OM147AdditionalPV.vdb
DB += OM15QWR_1_2_3AdditionalPV.vdb
DB += OM15QWR4AdditionalPV.vdb
DB += OM15QWR5AdditionalPV.vdb
DB += OM15HWR_1AdditionalPV.vdb
DB += OM15HWR_2_3AdditionalPV.vdb
DB += OM15HWR_4AdditionalPV.vdb
DB += OM15HWR_5AdditionalPV.vdb
DB += OM21AdditionalPV.vdb
DB += OM511AdditionalPV.vdb
DB += OM512AdditionalPV.vdb
DB += OM52AdditionalPV.vdb
DB += OM53_1_3_4AdditionalPV.vdb
DB += OM535AdditionalPV.vdb
DB += OM536AdditionalPV.vdb



#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

