file "db/test.template" pattern {
{SIGNAL,                      INP,      FLNK,               SCAN,                         DTYP}
{"Signal_0",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_1",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_2",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_3",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_4",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_5",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_6",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_7",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_8",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_9",                  "AAA",    "BBB",              "1 second",                   "Soft Channel"}
{"Signal_10",                 "AAA",    "BBB",              "1 second",                   "Soft Channel"}
}
