file "db/GBCURStat_OVR_Fail.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,		INPA,		INPB }
#####CM-CV-:CURStat
#####TT8404
{SCL31,	-BL01:,		CM01,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8404:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8404:,	OVRStat,	FailStat}

#####TT8401
{SCL31,	-BL01:,		CM01,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8401:,	OVRStat,	FailStat}

#####TT8406
{SCL31,	-BL01:,		CM01,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8406:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8406:,	OVRStat,	FailStat}

#####TT8402
{SCL31,	-BL01:,		CM01,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8402:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8402:,	OVRStat,	FailStat}

#####TT8403
{SCL31,	-BL01:,		CM01,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8403:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8403:,	OVRStat,	FailStat}

#####TT8405
{SCL31,	-BL01:,		CM01,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8405:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8405:,	OVRStat,	FailStat}

#####TT8501
{SCL31,	-BL01:,		CM01,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8501:,	OVRStat,	FailStat}

#####TT8502
{SCL31,	-BL01:,		CM01,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8502:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8502:,	OVRStat,	FailStat}

#####LT8401
{SCL31,	-BL01:,		CM01,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-LT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-LT8401:,	OVRStat,	FailStat}

#####PT8501
{SCL31,	-BL01:,		CM01,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-PT8501:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-PT8501:,	OVRStat,	FailStat}

#####PT8301
{SCL31,	-BL01:,		CM01,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-PT8301:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-PT8301:,	OVRStat,	FailStat}

#####PT8101
{SCL31,	-BL01:,		CM01,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-PT8101:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-PT8101:,	OVRStat,	FailStat}

#####PT8102
{SCL31,	-BL01:,		CM01,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-PT8102:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-PT8102:,	OVRStat,	FailStat}

#####PT8112
{SCL31,	-BL01:,		CM01,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-PT8112:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-PT8112:,	OVRStat,	FailStat}

#####PT8113
{SCL31,	-BL01:,		CM03,	-PT8113:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8113:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8113:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8113:,	OVRStat,	FailStat}

#####PT8103
{SCL31,	-BL01:,		CM03,	-PT8103:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8103:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8103:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8103:,	OVRStat,	FailStat}
#####PT8104
{SCL31,	-BL01:,		CM01,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-PT8104:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-PT8104:,	OVRStat,	FailStat}

##QWR-VBx
##TT7301
{SCL31,	-CDL01:,	VBx02,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-TT7301:,	OVRStat,	FailStat}

##TT7401
{SCL31,	-CDL01:,	VBx02,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-TT7401:,	OVRStat,	FailStat}

##TT7501
{SCL31,	-CDL01:,	VBx02,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-TT7501:,	OVRStat,	FailStat}

##TT7502
{SCL31,	-BL01:,		CM01,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM02,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM03,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM04,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM05,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM06,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM07,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM08,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM09,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM10,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM11,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM12,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM13,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM14,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM15,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM16,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM17,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM18,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM19,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM20,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM21,	-TT8401:,	OVRStat,	FailStat}
{SCL31,	-BL01:,		CM22,	-TT8401:,	OVRStat,	FailStat}

##TT7503
{SCL31,	-CDL01:,	VBx02,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-TT7503:,	OVRStat,	FailStat}

##TT7504
{SCL31,	-CDL01:,	VBx02,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-TT7504:,	OVRStat,	FailStat}

##TT7505
{SCL31,	-CDL01:,	VBx02,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-TT7505:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-TT7505:,	OVRStat,	FailStat}

##PT7501
{SCL31,	-CDL01:,	VBx02,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-PT7501:,	OVRStat,	FailStat}

##PT7502
{SCL31,	-CDL01:,	VBx02,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-PT7502:,	OVRStat,	FailStat}

##PT7503
{SCL31,	-CDL01:,	VBx02,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-PT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-PT7503:,	OVRStat,	FailStat}

##PT7401
{SCL31,	-CDL01:,	VBx02,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-PT7401:,	OVRStat,	FailStat}

##PT7301
{SCL31,	-CDL01:,	VBx02,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx04,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx06,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx08,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx10,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx12,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx14,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx16,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx18,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx20,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	VBx22,	-PT7301:,	OVRStat,	FailStat}


##EBx
{SCL31,	-CDL01:,	EBx01,	-TT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-TT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-TT7503:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-TT7504:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-TT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-TT7402:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-TT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7501:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7502:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7401:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7301:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7302:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7303:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-LT7401A:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-LT7401B:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7101:,	OVRStat,	FailStat}
{SCL31,	-CDL01:,	EBx01,	-PT7102:,	OVRStat,	FailStat}

##HWRA/P2DB CMs
##TT8204
{SCL32,	-BL02:,		CM01,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8204:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8204:,	OVRStat,	FailStat}

##TT8401
{SCL32,	-BL02:,		CM01,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8401:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8401:,	OVRStat,	FailStat}

##TT8404
{SCL32,	-BL02:,		CM01,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8404:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8404:,	OVRStat,	FailStat}

##TT8402
{SCL32,	-BL02:,		CM01,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8402:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8402:,	OVRStat,	FailStat}

##TT8202
{SCL32,	-BL02:,		CM01,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8202:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8202:,	OVRStat,	FailStat}

##TT8207
{SCL32,	-BL02:,		CM01,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8207:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8207:,	OVRStat,	FailStat}

##TT8203
{SCL32,	-BL02:,		CM01,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8203:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8203:,	OVRStat,	FailStat}

##TT8206
{SCL32,	-BL02:,		CM01,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8206:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8206:,	OVRStat,	FailStat}

##TT8205
{SCL32,	-BL02:,		CM01,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8205:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8205:,	OVRStat,	FailStat}

##TT8208
{SCL32,	-BL02:,		CM01,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8208:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8208:,	OVRStat,	FailStat}

##TT8501
{SCL32,	-BL02:,		CM01,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8501:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8501:,	OVRStat,	FailStat}

##TT8502
{SCL32,	-BL02:,		CM01,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8502:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8502:,	OVRStat,	FailStat}

##TT8601
{SCL32,	-BL02:,		CM01,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8601:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8601:,	OVRStat,	FailStat}

##TT8602
{SCL32,	-BL02:,		CM01,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-TT8602:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-TT8602:,	OVRStat,	FailStat}

##LT8401
{SCL32,	-BL02:,		CM01,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-LT8401:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-LT8401:,	OVRStat,	FailStat}

##LT8402
{SCL32,	-BL02:,		CM01,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-LT8402:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-LT8402:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-LT8402:,	OVRStat,	FailStat}

##PT8501
{SCL32,	-BL02:,		CM01,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8501:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8501:,	OVRStat,	FailStat}

##PT8301
{SCL32,	-BL02:,		CM01,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8301:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8301:,	OVRStat,	FailStat}

##PT8201
{SCL32,	-BL02:,		CM01,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8201:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8201:,	OVRStat,	FailStat}

##PT8202
{SCL32,	-BL02:,		CM01,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8202:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8202:,	OVRStat,	FailStat}

##PT8203
{SCL32,	-BL02:,		CM01,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8203:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8203:,	OVRStat,	FailStat}

##PT8101
{SCL32,	-BL02:,		CM01,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8101:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8101:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8101:,	OVRStat,	FailStat}

##PT8102
{SCL32,	-BL02:,		CM01,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8102:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8102:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8102:,	OVRStat,	FailStat}

##PT8112
{SCL32,	-BL02:,		CM01,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8112:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8112:,	OVRStat,	FailStat}

##PT8113
{SCL32,	-BL02:,		CM01,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8113:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8113:,	OVRStat,	FailStat}

##PT8103
{SCL32,	-BL02:,		CM01,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8103:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8103:,	OVRStat,	FailStat}

##PT8104
{SCL32,	-BL02:,		CM01,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM02,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM03,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM04,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM05,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM06,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM07,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM08,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM09,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM10,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM11,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM12,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL02:,		CM13,	-PT8104:,	OVRStat,	FailStat}
{P2DT,	-BL04:,		CM01,	-PT8104:,	OVRStat,	FailStat}

##HWRA/B/P2DB VBxs
##TT7502
{SCL32,	-CDL02:,	VBx01,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7502:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7502:,	OVRStat,	FailStat}

##TT7401
{SCL32,	-CDL02:,	VBx01,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7401:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7401:,	OVRStat,	FailStat}

##TT7301
{SCL32,	-CDL02:,	VBx01,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7301:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7301:,	OVRStat,	FailStat}

##TT7201
{SCL32,	-CDL02:,	VBx01,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7201:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7201:,	OVRStat,	FailStat}

##TT7501
{SCL32,	-CDL02:,	VBx01,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7501:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7501:,	OVRStat,	FailStat}

##TT7503
{SCL32,	-CDL02:,	VBx01,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7503:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7503:,	OVRStat,	FailStat}

##TT7504
{SCL32,	-CDL02:,	VBx01,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-TT7504:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-TT7504:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-TT7504:,	OVRStat,	FailStat}

##PT7501
{SCL32,	-CDL02:,	VBx01,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7501:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7501:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7501:,	OVRStat,	FailStat}

##PT7502
{SCL32,	-CDL02:,	VBx01,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7502:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7502:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7502:,	OVRStat,	FailStat}

##PT7401
{SCL32,	-CDL02:,	VBx01,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7401:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7401:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7401:,	OVRStat,	FailStat}

##PT7301
{SCL32,	-CDL02:,	VBx01,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7301:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7301:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7301:,	OVRStat,	FailStat}

##PT7201
{SCL32,	-CDL02:,	VBx01,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7201:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7201:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7201:,	OVRStat,	FailStat}

##PT7202
{SCL32,	-CDL02:,	VBx01,	-PT7202:,	OVRStat,	FailStat}
##No P2DT

##PT7503
{SCL32,	-CDL02:,	VBx03,	-PT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7503:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7503:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7503:,	OVRStat,	FailStat}

##PT7203
{SCL32,	-CDL02:,	VBx01,	-PT7203:,	OVRStat,	FailStat}
##No P2DT

##PT7101
{SCL32,	-CDL02:,	VBx01,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7101:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7101:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7101:,	OVRStat,	FailStat}

##PT7102
{SCL32,	-CDL02:,	VBx01,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx02,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx03,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx04,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx05,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx06,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx07,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx08,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx09,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx10,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx11,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx12,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL02:,	VBx13,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx01,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx02,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx03,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx04,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx05,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx06,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx07,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx08,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx09,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx10,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx11,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx12,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx13,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx14,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx15,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx16,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx17,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx18,	-PT7102:,	OVRStat,	FailStat}
{SCL32,	-CDL03:,	VBx19,	-PT7102:,	OVRStat,	FailStat}
{P2DT,	-CDL04:,	VBx01,	-PT7102:,	OVRStat,	FailStat}

##HWRB CMs
##TT8204
{SCL32,	-BL03:,		CM01,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8204:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8204:,	OVRStat,	FailStat}

##TT8401
{SCL32,	-BL03:,		CM01,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8401:,	OVRStat,	FailStat}

##TT8404
{SCL32,	-BL03:,		CM01,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8404:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8404:,	OVRStat,	FailStat}

##TT8402
{SCL32,	-BL03:,		CM01,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8402:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8402:,	OVRStat,	FailStat}

##TT8202
{SCL32,	-BL03:,		CM01,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8202:,	OVRStat,	FailStat}

##TT8207
{SCL32,	-BL03:,		CM01,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8207:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8207:,	OVRStat,	FailStat}

##TT8210
{SCL32,	-BL03:,		CM01,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8210:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8210:,	OVRStat,	FailStat}

##TT8213
{SCL32,	-BL03:,		CM01,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8213:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8213:,	OVRStat,	FailStat}

##TT8203
{SCL32,	-BL03:,		CM01,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8203:,	OVRStat,	FailStat}

##TT8206
{SCL32,	-BL03:,		CM01,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8206:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8206:,	OVRStat,	FailStat}

##TT8209
{SCL32,	-BL03:,		CM01,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8209:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8209:,	OVRStat,	FailStat}

##TT8212
{SCL32,	-BL03:,		CM01,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8212:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8212:,	OVRStat,	FailStat}

##TT8205
{SCL32,	-BL03:,		CM01,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8205:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8205:,	OVRStat,	FailStat}

##TT8208
{SCL32,	-BL03:,		CM01,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8208:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8208:,	OVRStat,	FailStat}

##TT8211
{SCL32,	-BL03:,		CM01,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8211:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8211:,	OVRStat,	FailStat}

##TT8214
{SCL32,	-BL03:,		CM01,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8214:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8214:,	OVRStat,	FailStat}

##TT8501
{SCL32,	-BL03:,		CM01,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8501:,	OVRStat,	FailStat}

##TT8502
{SCL32,	-BL03:,		CM01,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8502:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8502:,	OVRStat,	FailStat}

##TT8601
{SCL32,	-BL03:,		CM01,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8601:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8601:,	OVRStat,	FailStat}

##TT8602
{SCL32,	-BL03:,		CM01,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8602:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8602:,	OVRStat,	FailStat}

##TT8603
{SCL32,	-BL03:,		CM01,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8603:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8603:,	OVRStat,	FailStat}

##TT8604
{SCL32,	-BL03:,		CM01,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-TT8604:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-TT8604:,	OVRStat,	FailStat}

##LT8401
{SCL32,	-BL03:,		CM01,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-LT8401:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-LT8401:,	OVRStat,	FailStat}

##LT8201
{SCL32,	-BL03:,		CM01,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-LT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-LT8201:,	OVRStat,	FailStat}

##PT8501
{SCL32,	-BL03:,		CM01,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8501:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8501:,	OVRStat,	FailStat}

##PT8301
{SCL32,	-BL03:,		CM01,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8301:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8301:,	OVRStat,	FailStat}

##PT8201
{SCL32,	-BL03:,		CM01,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8201:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8201:,	OVRStat,	FailStat}

##PT8202
{SCL32,	-BL03:,		CM01,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8202:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8202:,	OVRStat,	FailStat}

##PT8203
{SCL32,	-BL03:,		CM01,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8203:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8203:,	OVRStat,	FailStat}
##NO P2DT

##PT8112
{SCL32,	-BL03:,		CM01,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8112:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8112:,	OVRStat,	FailStat}

##PT8113
{SCL32,	-BL03:,		CM01,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8113:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8113:,	OVRStat,	FailStat}

##PT8103
{SCL32,	-BL03:,		CM01,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8103:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8103:,	OVRStat,	FailStat}

##PT8104
{SCL32,	-BL03:,		CM01,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM02,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM03,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM04,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM05,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM06,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM07,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM08,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM09,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM10,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM11,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM12,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM13,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM14,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM15,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM16,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM17,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM18,	-PT8104:,	OVRStat,	FailStat}
{SCL32,	-BL03:,		CM19,	-PT8104:,	OVRStat,	FailStat}

#leesi
}

##{P2DT,	-BL04:,		CM01,	
##{P2DT,	-CDL04:,	VBx01,	
file "db/GBCURStat_Int_Fail_DCPC.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,		INPA,		INPB,		INPC }
##OWR-CMs
##EH8401
{SCL31,	-BL01:,		CM01,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM02,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-EH8401:,	FailStat,	IntStat,	DCPCStat}

##EH8402
{SCL31,	-BL01:,		CM01,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM02,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-EH8402:,	FailStat,	IntStat,	DCPCStat}

##CV8401
{SCL31,	-BL01:,		CM01,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM02,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-CV8401:,	FailStat,	IntStat,	DCPCStat}

##CV8402
{SCL31,	-BL01:,		CM01,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM02,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-CV8402:,	FailStat,	IntStat,	DCPCStat}

##XV8111
{SCL31,	-BL01:,		CM01,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-XV8111:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-XV8111:,	FailStat,	IntStat,	DCPCStat}

##XV8112
{SCL31,	-BL01:,		CM01,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-XV8112:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-XV8112:,	FailStat,	IntStat,	DCPCStat}

##XV8113
{SCL31,	-BL01:,		CM02,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-XV8113:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-XV8113:,	FailStat,	IntStat,	DCPCStat}

##XV8114
{SCL31,	-BL01:,		CM02,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-XV8114:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-XV8114:,	FailStat,	IntStat,	DCPCStat}

##OWR-VBxs
##CV7501
{SCL31,	-CDL01:,	VBx02,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7501:,	FailStat,	IntStat,	DCPCStat}

##CV7502
{SCL31,	-CDL01:,	VBx02,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7502:,	FailStat,	IntStat,	DCPCStat}

##CV7503
{SCL31,	-CDL01:,	VBx02,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7503:,	FailStat,	IntStat,	DCPCStat}

##CV7504
{SCL31,	-CDL01:,	VBx02,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7504:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7504:,	FailStat,	IntStat,	DCPCStat}

##CV7505
{SCL31,	-CDL01:,	VBx02,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7505:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7505:,	FailStat,	IntStat,	DCPCStat}

##CV7401
{SCL31,	-CDL01:,	VBx02,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7401:,	FailStat,	IntStat,	DCPCStat}

##CV7301
{SCL31,	-CDL01:,	VBx02,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-CV7301:,	FailStat,	IntStat,	DCPCStat}

##XV7501
{SCL31,	-CDL01:,	VBx02,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-XV7501:,	FailStat,	IntStat,	DCPCStat}

##XV7502
{SCL31,	-CDL01:,	VBx02,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-XV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-XV7502:,	FailStat,	IntStat,	DCPCStat}

##XV7301
{SCL31,	-CDL01:,	VBx02,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx04,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx06,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx08,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx10,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx12,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx14,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx16,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx18,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx20,	-XV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	VBx22,	-XV7301:,	FailStat,	IntStat,	DCPCStat}

##EBx
{SCL31,	-CDL01:,	EBx01,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-CV7402:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-EH7401A:,	FailStat,	IntStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-EH7401B:,	FailStat,	IntStat,	DCPCStat}

##HWR A/B/P2DT-CMs
##EH8401
{SCL32,	-BL02:,		CM01,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-EH8401:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-EH8401:,	FailStat,   IntStat,	DCPCStat}

##EH8402
{SCL32,	-BL02:,		CM01,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-EH8402:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-EH8402:,	FailStat,   IntStat,	DCPCStat}

##EH8201
{SCL32,	-BL02:,		CM01,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-EH8201:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-EH8201:,	FailStat,   IntStat,	DCPCStat}

##CV8401
{SCL32,	-BL02:,		CM01,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-CV8401:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-CV8401:,	FailStat,   IntStat,	DCPCStat}

##CV8402
{SCL32,	-BL02:,		CM01,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-CV8402:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-CV8402:,	FailStat,   IntStat,	DCPCStat}

##CV8403
{SCL32,	-BL02:,		CM01,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-CV8403:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-CV8403:,	FailStat,   IntStat,	DCPCStat}

##XV8201
{SCL32,	-BL02:,		CM03,	-XV8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8201:,	FailStat,	IntStat,	DCPCStat}

##HWR A/B/P2DT-VBxs
##CV7501
{SCL32,	-CDL02:,	VBx01,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7501:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-CV7501:,	FailStat,   IntStat,	DCPCStat}

##CV7502
{SCL32,	-CDL02:,	VBx01,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7502:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-CV7502:,	FailStat,   IntStat,	DCPCStat}

##CV7503
{SCL32,	-CDL02:,	VBx01,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7503:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-CV7503:,	FailStat,   IntStat,	DCPCStat}

##CV7401
{SCL32,	-CDL02:,	VBx01,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7401:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-CV7401:,	FailStat,   IntStat,	DCPCStat}

##CV7301
{SCL32,	-CDL02:,	VBx01,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7301:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-CV7301:,	FailStat,   IntStat,	DCPCStat}

##CV7201
{SCL32,	-CDL02:,	VBx01,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7201:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-CV7201:,	FailStat,   IntStat,	DCPCStat}

##XV7501
{SCL32,	-CDL02:,	VBx01,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-XV7501:,	FailStat,	IntStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-XV7501:,	FailStat,   IntStat,	DCPCStat}

##XV7301
{SCL32,	-CDL02:,	VBx01,	-XV7301:,	FailStat,	IntStat,	DCPCStat}

#leesi
}

file "db/GBCURStat_Fail_DCPC.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,		INPA,		INPB }
##QWR TP8101
{SCL31,	-BL01:,		CM03,	-TP8101:,	IntStat,	ErrLampR}
{SCL31,	-BL01:,		CM09,	-TP8101:,	IntStat,	ErrLampR}
{SCL31,	-BL01:,		CM15,	-TP8101:,	IntStat,	ErrLampR}
{SCL31,	-BL01:,		CM19,	-TP8101:,	IntStat,	ErrLampR}

##QWR TP8102
{SCL31,	-BL01:,		CM04,	-TP8102:,	IntStat,	ErrLampR}
{SCL31,	-BL01:,		CM10,	-TP8102:,	IntStat,	ErrLampR}
{SCL31,	-BL01:,		CM16,	-TP8102:,	IntStat,	ErrLampR}
{SCL31,	-BL01:,		CM20,	-TP8102:,	IntStat,	ErrLampR}

##HWRA TP8101
{SCL32,	-BL02:,		CM03,	-TP8101:,	IntStat,	ErrLampR}
{SCL32,	-BL02:,		CM08,	-TP8101:,	IntStat,	ErrLampR}
{SCL32,	-BL02:,		CM12,	-TP8101:,	IntStat,	ErrLampR}

##HWRA TP8102
{SCL32,	-BL02:,		CM03,	-TP8102:,	IntStat,	ErrLampR}
{SCL32,	-BL02:,		CM08,	-TP8102:,	IntStat,	ErrLampR}
{SCL32,	-BL02:,		CM12,	-TP8102:,	IntStat,	ErrLampR}

##HWRB TP8101
{SCL32,	-BL03:,		CM03,	-TP8101:,	IntStat,	ErrLampR}
{SCL32,	-BL03:,		CM08,	-TP8101:,	IntStat,	ErrLampR}
{SCL32,	-BL03:,		CM13,	-TP8101:,	IntStat,	ErrLampR}
{SCL32,	-BL03:,		CM17,	-TP8101:,	IntStat,	ErrLampR}
##HWRB TP8102
{SCL32,	-BL03:,		CM03,	-TP8102:,	IntStat,	ErrLampR}
{SCL32,	-BL03:,		CM08,	-TP8102:,	IntStat,	ErrLampR}
{SCL32,	-BL03:,		CM13,	-TP8102:,	IntStat,	ErrLampR}
{SCL32,	-BL03:,		CM17,	-TP8102:,	IntStat,	ErrLampR}

##P2DT TP8101
{P2DT,	-BL04:,		CM01,	-TP8101:,	IntStat,	ErrLampR}
{P2DT,	-BL04:,		CM01,	-TP8102:,	IntStat,	ErrLampR}

##OWR-CMs
##EV8301
{SCL31,	-BL01:,		CM01,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM02,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-EV8301:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-EV8301:,	FailStat,	DCPCStat}

##XV8103
{SCL31,	-BL01:,		CM01,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM02,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM03,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM04,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM05,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM06,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM07,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM08,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM09,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM10,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM11,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM12,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM13,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM14,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM15,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM16,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM17,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM18,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM19,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM20,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM21,	-XV8103:,	FailStat,	DCPCStat}
{SCL31,	-BL01:,		CM22,	-XV8103:,	FailStat,	DCPCStat}

##EBx
##CV7501 ##CV7503 ##XV7501 ##XV7502 ##XV7401 ##XV7301 ##XV7302
{SCL31,	-CDL01:,	EBx01,	-CV7501:,	FailStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-CV7503:,	FailStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-XV7501:,	FailStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-XV7502:,	FailStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-XV7401:,	FailStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-XV7301:,	FailStat,	DCPCStat}
{SCL31,	-CDL01:,	EBx01,	-XV7302:,	FailStat,	DCPCStat}

##HWR A/B/P2DT CMs
##EV8301
{SCL32,	-BL02:,		CM01,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-EV8301:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-EV8301:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-EV8301:,	FailStat,   DCPCStat}

##XV8103
{SCL32,	-BL02:,		CM01,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-XV8103:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-XV8103:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-XV8103:,	FailStat,   DCPCStat}

##XV8501
{SCL32,	-BL02:,		CM01,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-XV8501:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-XV8501:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-XV8501:,	FailStat,   DCPCStat}

##XV8111
{SCL32,	-BL02:,		CM01,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-XV8111:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-XV8111:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-XV8111:,	FailStat,   DCPCStat}

##XV8113
{SCL32,	-BL02:,		CM01,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-XV8113:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-XV8113:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-XV8113:,	FailStat,   DCPCStat}

##XV8112
{SCL32,	-BL02:,		CM01,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-XV8112:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-XV8112:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-XV8112:,	FailStat,   DCPCStat}

##XV8114
{SCL32,	-BL02:,		CM01,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM02,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM03,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM04,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM05,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM06,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM07,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM08,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM09,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM10,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM11,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM12,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL02:,		CM13,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM01,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM02,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM03,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM04,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM05,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM06,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM07,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM08,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM09,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM10,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM11,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM12,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM13,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM14,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM15,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM16,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM17,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM18,	-XV8114:,	FailStat,	DCPCStat}
{SCL32,	-BL03:,		CM19,	-XV8114:,	FailStat,	DCPCStat}
{P2DT,	-BL04:,		CM01,	-XV8114:,	FailStat,   DCPCStat}

##HWR A/B/P2DT VBxs
##CV7302
{SCL32,	-CDL02:,	VBx01,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-CV7302:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-CV7302:,	FailStat,	DCPCStat}
##No P2DT

##XV7502
{SCL32,	-CDL02:,	VBx01,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-XV7502:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-XV7502:,	FailStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-XV7502:,	FailStat,   DCPCStat}

##XV7201
{SCL32,	-CDL02:,	VBx01,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx02,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx03,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx04,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx05,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx06,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx07,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx08,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx09,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx10,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx11,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx12,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL02:,	VBx13,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx01,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx02,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx03,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx04,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx05,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx06,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx07,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx08,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx09,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx10,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx11,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx12,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx13,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx14,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx15,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx16,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx17,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx18,	-XV7201:,	FailStat,	DCPCStat}
{SCL32,	-CDL03:,	VBx19,	-XV7201:,	FailStat,	DCPCStat}
{P2DT,	-CDL04:,	VBx01,	-XV7201:,	FailStat,   DCPCStat}

#leesi
}

file "db/GBCURStat_ErrLamp.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,		INPA }
##QWR DP8101
{SCL31,	-BL01:,		CM03,	-DP8101:,	ErrLampR}
{SCL31,	-BL01:,		CM09,	-DP8101:,	ErrLampR}
{SCL31,	-BL01:,		CM15,	-DP8101:,	ErrLampR}
{SCL31,	-BL01:,		CM19,	-DP8101:,	ErrLampR}

##QWR DP8102
{SCL31,	-BL01:,		CM04,	-DP8102:,	ErrLampR}
{SCL31,	-BL01:,		CM10,	-DP8102:,	ErrLampR}
{SCL31,	-BL01:,		CM16,	-DP8102:,	ErrLampR}
{SCL31,	-BL01:,		CM20,	-DP8102:,	ErrLampR}

##HWRA DP8101
{SCL32,	-BL02:,		CM03,	-DP8101:,	ErrLampR}
{SCL32,	-BL02:,		CM08,	-DP8101:,	ErrLampR}
{SCL32,	-BL02:,		CM12,	-DP8101:,	ErrLampR}

##HWRA DP8102
{SCL32,	-BL02:,		CM03,	-DP8102:,	ErrLampR}
{SCL32,	-BL02:,		CM08,	-DP8102:,	ErrLampR}
{SCL32,	-BL02:,		CM12,	-DP8102:,	ErrLampR}

##HWRB DP8101
{SCL32,	-BL03:,		CM03,	-DP8101:,	ErrLampR}
{SCL32,	-BL03:,		CM08,	-DP8101:,	ErrLampR}
{SCL32,	-BL03:,		CM13,	-DP8101:,	ErrLampR}
{SCL32,	-BL03:,		CM17,	-DP8101:,	ErrLampR}

##HWRB DP8102
{SCL32,	-BL03:,		CM03,	-DP8102:,	ErrLampR}
{SCL32,	-BL03:,		CM08,	-DP8102:,	ErrLampR}
{SCL32,	-BL03:,		CM13,	-DP8102:,	ErrLampR}
{SCL32,	-BL03:,		CM17,	-DP8102:,	ErrLampR}

##P2DT DP8101
{P2DT,	-BL04:,		CM01,	-DP8101:,	ErrLampR}
{P2DT,	-BL04:,		CM01,	-DP8102:,	ErrLampR}
}

file "db/GBCURStat_NoStat.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV }
{SCL31,	-BL01:,		CM01,	-IP8101: }
{SCL31,	-BL01:,		CM02,	-IP8101: }
{SCL31,	-BL01:,		CM03,	-IP8101: }
{SCL31,	-BL01:,		CM04,	-IP8101: }
{SCL31,	-BL01:,		CM05,	-IP8101: }
{SCL31,	-BL01:,		CM06,	-IP8101: }
{SCL31,	-BL01:,		CM07,	-IP8101: }
{SCL31,	-BL01:,		CM08,	-IP8101: }
{SCL31,	-BL01:,		CM09,	-IP8101: }
{SCL31,	-BL01:,		CM10,	-IP8101: }
{SCL31,	-BL01:,		CM11,	-IP8101: }
{SCL31,	-BL01:,		CM12,	-IP8101: }
{SCL31,	-BL01:,		CM13,	-IP8101: }
{SCL31,	-BL01:,		CM14,	-IP8101: }
{SCL31,	-BL01:,		CM15,	-IP8101: }
{SCL31,	-BL01:,		CM16,	-IP8101: }
{SCL31,	-BL01:,		CM17,	-IP8101: }
{SCL31,	-BL01:,		CM18,	-IP8101: }
{SCL31,	-BL01:,		CM19,	-IP8101: }
{SCL31,	-BL01:,		CM20,	-IP8101: }
{SCL31,	-BL01:,		CM21,	-IP8101: }
{SCL31,	-BL01:,		CM22,	-IP8101: }

{SCL32,	-BL02:,		CM01,	-IP8101: }
{SCL32,	-BL02:,		CM02,	-IP8101: }
{SCL32,	-BL02:,		CM03,	-IP8101: }
{SCL32,	-BL02:,		CM04,	-IP8101: }
{SCL32,	-BL02:,		CM05,	-IP8101: }
{SCL32,	-BL02:,		CM06,	-IP8101: }
{SCL32,	-BL02:,		CM07,	-IP8101: }
{SCL32,	-BL02:,		CM08,	-IP8101: }
{SCL32,	-BL02:,		CM09,	-IP8101: }
{SCL32,	-BL02:,		CM10,	-IP8101: }
{SCL32,	-BL02:,		CM11,	-IP8101: }
{SCL32,	-BL02:,		CM12,	-IP8101: }
{SCL32,	-BL02:,		CM13,	-IP8101: }

{SCL32,	-BL03:,		CM01,	-IP8101: }
{SCL32,	-BL03:,		CM02,	-IP8101: }
{SCL32,	-BL03:,		CM03,	-IP8101: }
{SCL32,	-BL03:,		CM04,	-IP8101: }
{SCL32,	-BL03:,		CM05,	-IP8101: }
{SCL32,	-BL03:,		CM06,	-IP8101: }
{SCL32,	-BL03:,		CM07,	-IP8101: }
{SCL32,	-BL03:,		CM08,	-IP8101: }
{SCL32,	-BL03:,		CM09,	-IP8101: }
{SCL32,	-BL03:,		CM10,	-IP8101: }
{SCL32,	-BL03:,		CM11,	-IP8101: }
{SCL32,	-BL03:,		CM12,	-IP8101: }
{SCL32,	-BL03:,		CM13,	-IP8101: }
{SCL32,	-BL03:,		CM14,	-IP8101: }
{SCL32,	-BL03:,		CM15,	-IP8101: }
{SCL32,	-BL03:,		CM16,	-IP8101: }
{SCL32,	-BL03:,		CM17,	-IP8101: }
{SCL32,	-BL03:,		CM18,	-IP8101: }
{SCL32,	-BL03:,		CM19,	-IP8101: }
{P2DT,	-BL04:,		CM01,	-IP8101: }
}
