##for cooldown031.sub
file "db/PressR.template" { pattern
{SYS,      SUBSYS,   DEV,      SUBDEV,   SIGNAL,   PINI,     VAL,           SCAN}
{Cryo,     -CDL00:,  TBx01,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{Cryo,     -CDL00:,  TBx01,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{Cryo,     -CDL00:,  TBx01,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{Cryo,     -CDL00:,  TBx01,    -PT7504:, Press,    "YES",    "2.2",         "Passive"}
{Cryo,     -CDL00:,  TBx01,    -PT7505:, Press,    "YES",    "2.2",         "Passive"}
{Cryo,     -CDL00:,  TBx01,    -PT7506:, Press,    "YES",    "2.2",         "Passive"}
{Cryo,     -CDL00:,  TBx01,    -PT7581:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  EBx01,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  EBx01,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx02,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx02,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx02,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx04,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx04,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx04,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx06,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx06,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx06,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx08,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx08,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx08,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx10,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx10,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx10,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx12,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx12,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx12,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx14,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx14,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx14,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx16,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx16,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx16,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx18,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx18,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx18,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx20,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx20,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx20,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx22,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx22,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL31,    -CDL01:,  VBx22,    -PT7503:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx01,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx01,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx02,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx02,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx03,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx03,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx04,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx04,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx05,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx05,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx06,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx06,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx07,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx07,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx08,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx08,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx09,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx09,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx10,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx10,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx11,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx11,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx12,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx12,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx13,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL02:,  VBx13,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx01,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx01,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx02,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx02,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx03,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx03,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx04,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx04,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx05,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx05,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx06,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx06,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx07,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx07,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx08,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx08,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx09,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx09,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx10,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx10,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx11,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx11,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx12,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx12,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx13,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx13,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx14,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx14,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx15,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx15,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx16,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx16,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx17,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx17,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx18,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx18,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx19,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{SCL32,    -CDL03:,  VBx19,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
{P2DT,     -CDL04:,  VBx01,    -PT7501:, Press,    "YES",    "2.2",         "Passive"}
{P2DT,     -CDL04:,  VBx01,    -PT7502:, Press,    "YES",    "2.2",         "Passive"}
}

#for cooldown032.sub
file "db/PressR.template" { pattern
{SYS,		SUBSYS,		 DEV,		    SUBDEV,		  SIGNAL,	    PINI,       VAL,         SCAN}
{Cryo,      -CDL00:,      TBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7202:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7203:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7302:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7303:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7304:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7382:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7402:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7403:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,      TBx01,	    -PT7481:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
}

##for cooldown034.sub
file "db/PressR.template" { pattern
{SYS,		SUBSYS,		 DEV,		    SUBDEV,		  SIGNAL,	    PINI,       VAL,         SCAN}
{SCL31,     -CDL01:,      EBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #EBx
}

##for cooldown036-1.sub
file "db/PressR.template" { pattern
{SYS,		SUBSYS,		 DEV,		    SUBDEV,		  SIGNAL,	    PINI,       VAL,         SCAN}
#{SCL31,     -CDL01:,      EBx01,		-PT7301:,	  Press,		"YES",		"2",		"Passive"	} #EBx
{SCL31,     -CDL01:,      VBx02,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx04,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx06,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx08,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx10,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx12,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx14,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx16,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx18,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx20,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx22,		-PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -CDL02:,      VBx01,	    -PT7202:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx02,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx03,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx03,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx04,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx05,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx05,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx06,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx07,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx07,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx08,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx09,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx09,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx10,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx11,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx11,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx12,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx13,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx13,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,      VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx02,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx03,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx03,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx04,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx05,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx05,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx06,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx07,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx07,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx08,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx09,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx09,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx10,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx11,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx11,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx12,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx13,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx13,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx14,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx14,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx15,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx15,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx16,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx16,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx17,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx17,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx18,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx18,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx19,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx19,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,      VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
{P2DT,      -CDL04:,      VBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

##for cooldown036-2.sub
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,	    -CDL01:,	  EBx01,		-PT7401:,	  Press,		"YES",		"2",		"Passive"	}
{Cryo,      -CDL00:,      TBx01,        -PT7403:,     Press,        "YES",		"2.5",		"Passive"	} #TBx
{SCL31,     -CDL01:,      VBx02,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx04,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx06,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx08,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx10,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx12,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx14,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx16,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx18,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx20,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx22,		-PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR 

{SCL32,     -CDL02:,      VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx03,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx05,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx07,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx09,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx11,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx13,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA

{SCL32,     -CDL03:,      VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx03,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx05,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx07,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx09,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx11,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx13,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx14,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx15,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx16,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx17,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx18,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx19,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB

{P2DT,      -CDL04:,      VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

##for cooldown036-3.sub
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,     -BL01:,       CM01,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM02,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM03,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM04,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR

{SCL32,     -BL02:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
  
{SCL32,     -BL03:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
  
{P2DT,      -BL04:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

##for cooldown036-4.sub
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,     -BL01:,       CM01,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM02,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM03,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM04,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,	    	-PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
}


##for cooldown036-5.sub
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL32,     -BL02:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
{SCL32,     -BL02:,       CM01,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

##for cooldown036-6.sub
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,     -BL01:,       CM01,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM02,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM03,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM04,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,	        -PT8301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR

{SCL32,     -BL02:,       CM01,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
  
{SCL32,     -BL03:,       CM01,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
  
{P2DT,      -BL04:,       CM01,	        -PT8201:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

##for cooldown036-7.sub
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,     -CDL01:,    VBx02,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx02,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx04,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx04,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,      -PT7502:,       Press,		"YES",		"2.2",		"Passive"	} #QWR

{SCL32,     -CDL02:,    VBx01,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx02,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
  
{SCL32,     -CDL03:,    VBx01,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx02,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
  
{P2DT,      -CDL04:,    VBx01,      -PT7501:,       Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

#for cooldown04
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,     -CDL01:,    EBx01,	    -PT7503:,	  Press,		"YES",		"2.2",		"Passive"	} #EBx
{SCL31,     -CDL01:,    EBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #EBx
{SCL31,     -CDL01:,    EBx01,		-PT7401:,	  Press,		"YES",		"2",		"Passive"	} #EBx
{Cryo,      -CDL00:,    TBx01,      -PT7403:,     Press,        "YES",		"2",		"Passive"	} #TBx
{SCL31,     -CDL01:,    EBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #EBx
{Cryo,      -CDL00;,    TBx01,      -PT7403;,     Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00;,    TBx01,      -PT7203;,     Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00;,    TBx01,      -PT7202;,     Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00;,    TBx01,      -PT7201;,     Press,		"YES",		"2.2",		"Passive"	} #TBx
{SCL32,     -CDL02:,    VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
{SCL32,     -CDL02:,    VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
{SCL31,     -CDL01:,    VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx14,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx16,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx18,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx20,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx22,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx01,	    -PT7202:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{Cryo,      -CDL00;,    TBx01,      -PT7203;,     Press,		"YES",		"2.2",		"Passive"	} #TBx
{SCL31,     -CDL01:,    VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -CDL02:,    VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx02,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,	    -PT7401:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT

{SCL31,     -CDL01:,    VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx14,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx16,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx18,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx20,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL31,     -CDL01:,    VBx22,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA

{SCL32,     -CDL02:,    VBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx02,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx02,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT

{SCL31,     -CDL01:,    VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -CDL02:,    VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx02,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,	    -PT7301:,	  Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

#for cooldown12
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{Cryo,      -CDL00:,    TBx01,	    -PT7203:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,    TBx01,	    -PT7202:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
{Cryo,      -CDL00:,    TBx01,	    -PT7201:,	  Press,		"YES",		"2.2",		"Passive"	} #TBx
}

#for cooldown14
file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -CDL01:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx20,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx22,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -CDL02:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx15,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx17,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx19,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,	    SUBSYS,		  DEV,		SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN		}
{SCL31,     -BL01:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR  
{SCL31,     -BL01:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -BL02:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -CDL01:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx20,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx22,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -CDL02:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx15,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx17,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx19,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}


file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,       CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,		SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,      VBx02,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx04,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx06,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx08,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx10,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx12,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx14,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx16,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx18,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx20,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx22,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -CDL02:,      VBx01,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx02,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx03,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx04,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx05,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx06,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx07,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx08,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx09,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx10,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx11,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx12,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx13,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,      VBx01,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx02,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx03,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx04,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx05,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx06,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx07,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx08,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx09,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx10,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx11,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx12,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx13,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx14,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx15,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx16,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx17,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx18,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx19,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,      VBx01,    -PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -CDL01:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx20,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,       VBx22,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,	      DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -BL01:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR  
{SCL31,     -BL01:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,	      DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,       CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -CDL02:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx15,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx17,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx19,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		  DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -BL01:,       CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR  
{SCL31,     -BL01:,       CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,    VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -CDL01:,    VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		DEV,	    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,    VBx02,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR   
{SCL31,     -CDL01:,    VBx04,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,     DEV,     SUBDEV,        SIGNAL,   PINI,     VAL,		SCAN        }
{SCL31,     -CDL01:,    VBx02,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR   
{SCL31,     -CDL01:,    VBx04,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx06,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx08,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx10,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx12,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx14,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx16,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx18,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx20,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
{SCL31,     -CDL01:,    VBx22,   -PT7301:,      Press,    "YES",    "2.2",		"Passive"	} #QWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,     DEV,        SUBDEV,         SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -CDL02:,    VBx01,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA   
{SCL32,     -CDL02:,    VBx02,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB   
{SCL32,     -CDL03:,    VBx02,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,      -PT7301:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB

{SCL32,     -CDL02:,    VBx01,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA   
{SCL32,     -CDL02:,    VBx02,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx03,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx04,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx05,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx06,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx07,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx08,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx09,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx10,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx11,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx12,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,    VBx13,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,    VBx01,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB   
{SCL32,     -CDL03:,    VBx02,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx03,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx04,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx05,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx06,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx07,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx08,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx09,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx10,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx11,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx12,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx13,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx14,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx15,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx16,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx17,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx18,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,    VBx19,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,    VBx01,      -PT7201:,       Press,		"YES",		"2.2",		"Passive"	} #HWRB
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,     DEV,        SUBDEV,         SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,       CM01,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA  
{SCL32,     -BL02:,       CM03,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA  
{SCL32,     -BL02:,       CM04,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB  
{SCL32,     -BL03:,       CM02,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB  
{SCL32,     -BL03:,       CM03,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB  
{SCL32,     -BL03:,       CM04,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,		-PT8201:,     Press,		"YES",		"1.3",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,     -PT8201:,     Press,        "YES",      "1.3",      "Passive"   } #P2DT

{SCL32,     -BL02:,       CM01,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM02,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA  
{SCL32,     -BL02:,       CM03,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA  
{SCL32,     -BL02:,       CM04,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM05,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM06,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM07,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM08,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM09,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM10,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM11,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM12,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL02:,       CM13,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRA
{SCL32,     -BL03:,       CM01,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB  
{SCL32,     -BL03:,       CM02,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB  
{SCL32,     -BL03:,       CM03,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB  
{SCL32,     -BL03:,       CM04,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM05,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM06,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM07,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM08,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM09,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM10,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM11,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM12,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM13,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM14,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM15,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM16,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM17,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM18,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{SCL32,     -BL03:,       CM19,		-PT8301:,     Press,		"YES",		"2.0",		"Passive"	} #HWRB
{P2DT,      -BL04:,       CM01,     -PT8301:,     Press,        "YES",      "2.0",      "Passive"   } #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -CDL02:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA   
{SCL32,     -CDL02:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB   
{SCL32,     -CDL03:,       VBx02,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx03,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx04,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx05,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx06,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx07,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx08,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx09,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx10,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx11,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx12,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx13,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx14,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx15,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx16,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx17,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx18,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx19,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,       VBx01,		-PT7401:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -CDL02:,       VBx01,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR   
{SCL32,     -CDL02:,       VBx02,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx03,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx04,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx05,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx06,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx07,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx08,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx09,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx10,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx11,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL02:,       VBx12,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR   
{SCL32,     -CDL02:,       VBx13,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx01,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx02,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx03,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx04,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx05,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx06,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx07,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx08,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx09,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx10,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx11,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx12,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx13,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx14,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx15,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx16,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx17,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx18,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -CDL03:,       VBx19,		-PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{P2DT,      -CDL04:,       VBx01,       -PT7201:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -CDL02:,       VBx01,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA   
{SCL32,     -CDL02:,       VBx02,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx03,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx04,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx05,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx06,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx07,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx08,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx09,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx10,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx11,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL02:,       VBx12,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA   
{SCL32,     -CDL02:,       VBx13,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -CDL03:,       VBx01,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx02,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx03,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx04,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx05,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx06,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx07,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx08,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx09,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx10,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx11,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx12,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx13,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx14,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx15,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx16,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx17,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx18,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -CDL03:,       VBx19,		-PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -CDL04:,       VBx01,       -PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{Cryo,      -CDL00:,       TBx01,		-PT7202:,     Press,		"YES",		"2.2",		"Passive"	} #TBx   
{Cryo,      -CDL00:,       TBx01,		-PT7304:,     Press,		"YES",		"2.2",		"Passive"	} #TBx
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,     -CDL01:,       EBx01,       -PT7301:,     Press,		"YES",		"2.2",		"Passive"	} #EBx
{SCL31,     -BL01:,        CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM20,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM21,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL31,     -BL01:,        CM22,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #QWR
{SCL32,     -BL02:,        CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,        CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM14,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM15,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM16,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM17,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM18,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM19,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,        CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,        CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL02:,        CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM02,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM03,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM04,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM05,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM06,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM07,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM08,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM09,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM10,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM11,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM12,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM13,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM14,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM15,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM16,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM17,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM18,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{SCL32,     -BL03:,        CM19,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
{P2DT,      -BL04:,        CM01,		-PT8301:,     Press,		"YES",		"2.2",		"Passive"	} #HWR
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,		PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,        CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
{SCL32,     -BL03:,        CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM02,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM03,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM04,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM05,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM06,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM07,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM08,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM09,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM10,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM11,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM12,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM13,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM14,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM15,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM16,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM17,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM18,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM19,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #HWRB
{P2DT,      -BL04:,        CM01,		-PT8201:,     Press,		"YES",		"2.2",		"Passive"	} #P2DT
{Cryo,      -CDL00:,       TBx01,       -PT7203:,     Press,        "YES",      "2.2",      "Passive"   } #TBx
{Cryo,      -CDL00:,       TBx01,       -PT7302:,     Press,        "YES",      "2.2",      "Passive"   } #TBx
{Cryo,      -CDL00:,       TBx01,       -PT7304:,     Press,        "YES",      "2.2",      "Passive"   } #TBx
{SCL32,     -CDL02:,       VBx01,		-PT7202:,     Press,		"YES",		"2.2",		"Passive"	} #HWRA
}
#cooldown14
file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		  DEV,		SUBDEV,		  SIGNAL,	PINI,       VAL,		SCAN		}
{SCL31,     -CDL01:,      VBx02,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx04,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx06,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx08,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx10,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx12,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx14,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx16,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx18,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx20,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx22,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL32,     -CDL02:,      VBx01,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx02,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx03,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx04,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx05,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx06,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx07,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx08,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx09,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx10,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx11,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx12,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx13,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRA
{SCL32,     -CDL03:,      VBx01,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx02,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx03,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx04,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx05,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx06,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx07,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx08,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx09,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx10,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx11,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx12,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx13,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx14,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx15,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx16,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx17,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx18,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx19,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #HWRB
{P2DT,      -CDL04:,      VBx01,    -TT7401:,     Temp,		"YES",		"20",		"Passive"	} #P2DT
}

#cooldown14
file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		  DEV,		SUBDEV,		  SIGNAL,	PINI,       VAL,		SCAN		}
{SCL31,     -BL01:,       CM01,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR  
{SCL31,     -BL01:,       CM02,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM03,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR   
{SCL31,     -BL01:,       CM04,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM05,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM06,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM07,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM08,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM09,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM10,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM11,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM12,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM13,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM14,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM15,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM16,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM17,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM18,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM19,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM20,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM21,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
{SCL31,     -BL01:,       CM22,		-TT8403:,     Temp,         "YES",		"10",		"Passive"	} #QWR
}

#cooldown15
file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		  DEV,		SUBDEV,		  SIGNAL,	PINI,       VAL,		SCAN		}
{SCL31,     -CDL01:,      VBx02,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx04,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx06,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx08,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx10,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx12,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx14,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx16,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx18,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx20,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
{SCL31,     -CDL01:,      VBx22,    -TT7301:,     Temp,     "YES",		"10",		"Passive"	} #QWR
}

file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		  DEV,		    SUBDEV,		  SIGNAL,     PINI,		    VAL,	    SCAN		}
{SCL32,     -CDL02:,      VBx01,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx02,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx03,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx04,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx05,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx06,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx07,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx08,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx09,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx10,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx11,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx12,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL02:,      VBx13,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx01,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx02,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx03,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx04,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx05,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx06,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx07,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx08,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx09,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx10,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx11,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx12,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx13,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx14,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx15,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx16,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx17,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx18,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{SCL32,     -CDL03:,      VBx19,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
{P2DT,      -CDL04:,      VBx01,        -TT7201:,     Temp,		  "YES",		"5",		"Passive"	} #HWR
}

file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		  DEV,      SUBDEV,		  SIGNAL,     PINI,		    VAL,	    SCAN		}
{SCL32,     -CDL02:,      VBx01,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx02,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx03,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx04,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx05,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx06,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx07,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx08,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx09,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx10,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx11,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx12,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL02:,      VBx13,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRA
{SCL32,     -CDL03:,      VBx01,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx02,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx03,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx04,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx05,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx06,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx07,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx08,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx09,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx10,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx11,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx12,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx13,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx14,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx15,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx16,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx17,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx18,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{SCL32,     -CDL03:,      VBx19,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #HWRB
{P2DT,      -CDL04:,      VBx01,    -TT7301:,     Temp,		  "YES",		"5",		"Passive"	} #P2DT
}

file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		DEV,		SUBDEV,		    SIGNAL,		PINI,       VAL,		SCAN		}
{SCL31,     -CDL01:,    EBx01,      -TT7501:,       Temp,		"YES",		"20",		"Passive"	} #QWR
{SCL31,		-CDL01:,	EBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx14,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx16,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx18,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx20,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx22,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx03,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx05,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx07,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx09,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx11,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx13,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx03,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx05,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx07,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx09,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx11,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx13,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx14,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx15,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx16,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx17,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx18,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx19,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{P2DT,		-CDL04:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	EBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx14,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx16,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx18,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx20,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx22,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx03,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx05,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx07,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx09,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx11,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx13,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx03,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx05,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx07,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx09,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx11,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx13,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx14,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx15,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx16,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx17,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx18,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx19,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	EBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx14,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx16,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx18,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx20,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx22,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx03,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx05,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx07,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx09,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx11,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL02:,	VBx13,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx01,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx02,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx03,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx04,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx05,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx06,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx07,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx08,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx09,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx10,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx11,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx12,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx13,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx14,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx15,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx16,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx17,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx18,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
{SCL32,		-CDL03:,	VBx19,		-TT7501:,		Temp,		"YES",		"20",		"Passive"	}
}

file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		DEV,		SUBDEV,		    SIGNAL,		PINI,       VAL,		SCAN		}
{SCL31,		-CDL01:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"	}
{SCL31,		-CDL01:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx06,		-TT7502:,		Temp,       "YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx14,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx16,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx18,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx20,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx22,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx03,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx05,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx06,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx07,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx09,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx11,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx13,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx03,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx05,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx06,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx07,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx09,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx11,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx13,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx14,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx15,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx16,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx17,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx18,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx19,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{P2DT,		-CDL04:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx22,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx03,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx05,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx06,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx07,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx09,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx11,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx13,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx03,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx05,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx06,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx07,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx09,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx11,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx13,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx14,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx15,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx16,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx17,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx18,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx19,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx22,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx03,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx05,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx06,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx07,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx09,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx11,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL02:,	VBx13,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx01,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx02,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx03,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx04,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx05,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx06,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx07,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx08,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx09,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx10,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx11,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx12,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx13,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx14,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx15,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx16,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx17,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx18,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
{SCL32,		-CDL03:,	VBx19,		-TT7502:,		Temp,		"YES",		"20",		"Passive"   }
}

file "db/cd_ai.template" { pattern
{SYS,	    SUBSYS,		DEV,		SUBDEV,		    SIGNAL,		PINI,       VAL,		SCAN		}
{SCL31,		-CDL01:,	VBx02,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx04,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx06,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx08,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx10,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx12,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx14,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx16,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx18,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx20,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx22,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx02,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx04,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx06,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx08,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx10,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx12,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx14,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx16,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx18,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx20,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx02,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx04,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx06,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx08,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx10,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx12,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx14,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx16,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx18,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	VBx20,		-TT7503:,		Temp,		"YES",		"20",		"Passive"   }
{SCL31,		-CDL01:,	EBx01,		-TT7504:,		Temp,		"YES",		"20",		"Passive"   }
}

file "db/press.template" { pattern
{SYS,   	SUBSYS,		    DEV,		    SUBDEV,		SIGNAL,		PINI,		VAL,		SCAN        }
{SCL31,		-CDL01:,		VBx02,			-PT7001:,	Press,		"YES",		"10",		"Passive"	}
{SCL31,		-CDL01:,		VBx04,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx06,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx08,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx10,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx12,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx14,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx16,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx18,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx20,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx22,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx01,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx02,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx03,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx04,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx05,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx06,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx07,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx08,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx09,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx10,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx11,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx12,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx13,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx01,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx02,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx03,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx04,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx05,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx06,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx07,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx08,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx09,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx10,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx11,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx12,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx13,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx14,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx15,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx16,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx17,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx18,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx19,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx02,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx04,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx06,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx08,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx10,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx12,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx14,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx16,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx18,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx20,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx22,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx01,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx02,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx03,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx04,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx05,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx06,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx07,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx08,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx09,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx10,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx11,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx12,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx13,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx01,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx02,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx03,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx04,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx05,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx06,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx07,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx08,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx09,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx10,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx11,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx12,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx13,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx14,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx15,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx16,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx17,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx18,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx19,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx02,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx04,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx06,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx08,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx10,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx12,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx14,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx16,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx18,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx20,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx22,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx01,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx02,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx03,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx04,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx05,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx06,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx07,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx08,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx09,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx10,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx11,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx12,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx13,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx01,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx02,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx03,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx04,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx05,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx06,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx07,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx08,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx09,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx10,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx11,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx12,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx13,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx14,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx15,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx16,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx17,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx18,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx19,			-PT7001:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx02,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx04,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx06,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx08,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx10,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx12,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx14,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx16,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx18,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx20,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL31,		-CDL01:,		VBx22,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx01,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx02,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx03,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx04,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx05,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx06,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx07,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx08,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx09,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx10,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx11,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx12,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL02:,		VBx13,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx01,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx02,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx03,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx04,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx05,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx06,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx07,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx08,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx09,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx10,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx11,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx12,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx13,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx14,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx15,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx16,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx17,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx18,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
{SCL32,		-CDL03:,		VBx19,			-PT7002:,	Press,		"YES",		"10",		"Passive"   }
}

file "db/PressR.template" { pattern
{SYS,   	SUBSYS,		   DEV,		    SUBDEV,		  SIGNAL,	PINI,		VAL,		SCAN        }
{SCL32,     -BL02:,        CM01,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM02,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM03,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM04,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM05,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM06,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM07,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM08,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM09,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM10,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM11,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM12,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL02:,        CM13,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRA
{SCL32,     -BL03:,        CM01,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM02,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM03,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM04,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM05,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM06,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM07,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM08,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM09,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM10,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM11,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM12,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM13,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM14,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM15,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM16,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM17,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM18,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{SCL32,     -BL03:,        CM19,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #HWRB
{P2DT,      -BL04:,        CM01,		-TT8202:,     Temp,		"YES",		"10",		"Passive"	} #P2DT
}

