#Makefile at top of application tree
TOP = .
include $(TOP)/configure/CONFIG
DIRS += configure
DIRS += seqLib
DIRS += asynLib
DIRS += timestampRecordLib
DIRS += sysMonLib
DIRS += cltuLib
DIRS += sfwLib
DIRS += kutilLib
DIRS += kupaLib
DIRS += sfwTreeLib
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Lib))
include $(TOP)/configure/RULES_TOP
