TOP = ../../..
include $(TOP)/configure/CONFIG

LIBRARY	+= raspCharLCD
DBDINC	+= lcdoutRecord
DBD	+= lcdoutRecord.dbd devCharLCD.dbd

raspCharLCD_SRCS += lcdoutRecord.c devCharLCD.c

include $(TOP)/configure/RULES

