file "db/ai.template" { pattern
{ SYS,	SUBSYS,		DEV,	PORT,		ADDR, TIMEOUT, 	SIGNAL,		ALIAS,			SCAN,		    VAL } 
{ 200425, 347114,   1214,  	SerialUSB,   0,    1,        TempA,     1214_TEMP_A,       "I/O Intr",  	0.0 }
{ 200425, 347114,   1214,  	SerialUSB,   0,    1,        TempB,     1214_TEMP_B,       "I/O Intr",  	0.0 }
{ 200304, 435155,   1130,  	SerialUSB,   0,    1,        TempA,     1130_TEMP_A,       "I/O Intr",  	0.0 }
{ 200304, 435155,   1130,  	SerialUSB,   0,    1,        TempB,     1130_TEMP_B,       "I/O Intr",  	0.0 }
}

