TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
DB  += aiFloat64.template
DB  += aoFloat64.template
DB  += biWord.template
DB  += boWord.template
DB  += TBxcontrol.sub
DB  += TBxcontrol_2.sub
DB  += TBxcontrol_test.sub


#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

