file "db/aiFloat64.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,			SIGNAL,		PORT,		OFFSET, DATA_TYPE,	LOPR,	HOPR,	PREC,	EGU,		SCAN,		DESC}
{Cryo,	-CDL00:,	TBx01,	-PT7101:,		PresR,		"TBXAI",	  0,	 FLOAT32_BE, 0,		 25,	 3,		 "mbar",	"1 second",	"TBx PT7101 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7102:,		PresR,		"TBXAI",	  2,	 FLOAT32_BE, 0,		 25,	 3,		 "mbar",	"1 second",	"TBx PT7102 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7103:,		PresR,		"TBXAI",      4,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7103 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7104:,		PresR,		"TBXAI",      6,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7104 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		PresR,		"TBXAI",      8,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7181 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI",     10,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PTSpare1 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7141:,		PresR,		"TBXAI",     12,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7141 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7142:,		PresR,		"TBXAI",     14,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7142 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7143:,		PresR,		"TBXAI",     16,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7143 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7144:,		PresR,		"TBXAI",     18,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7144 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI",     20,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PTSpare2 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		PresR,		"TBXAI",     22,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PTSpare3 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		PresR,		"TBXAI",     24,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7106 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		PresR,		"TBXAI",     26,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7105 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		PresR,		"TBXAI",     28,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7146 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		PresR,		"TBXAI",     30,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7145 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7182:,		PresR,		"TBXAI",     32,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PT7182 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare4:,		PresR,		"TBXAI",     34,     FLOAT32_BE, 0,      25,     3,      "mbar",	"1 second", "TBx PTSpare4 Press"}
#{AI_72																 36,																			}
#{AI_76																 38,																			}
{Cryo,	-CDL00:,	TBx01,	-TT7543:,		TempR,		"TBXAI",     40,     FLOAT32_BE, 0,      25,     3,      "K",		"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7541:,		TempR,		"TBXAI",     42,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7544:,		TempR,		"TBXAI",     44,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7542:,		TempR,		"TBXAI",     46,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		TempR,		"TBXAI",     48,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7582:,		TempR,		"TBXAI",     50,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare1:,		TempR,		"TBXAI",     52,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare2:,		TempR,		"TBXAI",     54,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7241:,		TempR,		"TBXAI",     56,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7242:,		TempR,		"TBXAI",     58,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7341:,		TempR,		"TBXAI",     60,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7342:,		TempR,		"TBXAI",     62,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7441:,		TempR,		"TBXAI",     64,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7442:,		TempR,		"TBXAI",     66,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare3:,		TempR,		"TBXAI",     68,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare4:,		TempR,		"TBXAI",     70,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7503:,		TempR,		"TBXAI",     72,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7501:,		TempR,		"TBXAI",     74,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7504:,		TempR,		"TBXAI",     76,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7502:,		TempR,		"TBXAI",     78,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7583:,		TempR,		"TBXAI",     80,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare5:,		TempR,		"TBXAI",     82,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare6:,		TempR,		"TBXAI",     84,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare7:,		TempR,		"TBXAI",     86,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7303:,		TempR,		"TBXAI",     88,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7343:,		TempR,		"TBXAI",     90,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare8:,		TempR,		"TBXAI",     92,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare9:,		TempR,		"TBXAI",     94,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare10:,	TempR,		"TBXAI",     96,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare11:,	TempR,		"TBXAI",     98,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare12:,	TempR,		"TBXAI",    100,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare13:,	TempR,		"TBXAI",    102,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7201:,		TempR,		"TBXAI",    104,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7202:,		TempR,		"TBXAI",    106,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7301:,		TempR,		"TBXAI",    108,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7302:,		TempR,		"TBXAI",    110,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7401:,		TempR,		"TBXAI",    112,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7402:,		TempR,		"TBXAI",    114,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7381:,		TempR,		"TBXAI",    116,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare14:,	TempR,		"TBXAI",    118,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		PresR,		"TBXAI",    120,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		PresR,		"TBXAI",    122,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		PresR,		"TBXAI",    124,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		PresR,		"TBXAI_1",    0,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		PresR,		"TBXAI_1",    2,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7241:,		PresR,		"TBXAI_1",    4,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7202:,		PresR,		"TBXAI_1",    6,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7305:,		PresR,		"TBXAI_1",    8,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7505:,		PresR,		"TBXAI_1",   10,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7502:,		PresR,		"TBXAI_1",   12,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7302:,		PresR,		"TBXAI_1",   14,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7402:,		PresR,		"TBXAI_1",   16,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7544:,		PresR,		"TBXAI_1",   18,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7541:,		PresR,		"TBXAI_1",   20,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7341:,		PresR,		"TBXAI_1",   22,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7441:,		PresR,		"TBXAI_1",   24,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7306:,		PresR,		"TBXAI_1",   26,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7304:,		PresR,		"TBXAI_1",   28,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		PresR,		"TBXAI_1",   30,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7503:,		PresR,		"TBXAI_1",   32,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		PresR,		"TBXAI_1",   34,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		PresR,		"TBXAI_1",   36,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7545:,		PresR,		"TBXAI_1",   38,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7542:,		PresR,		"TBXAI_1",   40,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7203:,		PresR,		"TBXAI_1",   42,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7243:,		PresR,		"TBXAI_1",   44,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7242:,		PresR,		"TBXAI_1",   46,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7342:,		PresR,		"TBXAI_1",   48,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7442:,		PresR,		"TBXAI_1",   50,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7546:,		PresR,		"TBXAI_1",   52,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7543:,		PresR,		"TBXAI_1",   54,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7343:,		PresR,		"TBXAI_1",   56,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7443:,		PresR,		"TBXAI_1",   58,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		PresR,		"TBXAI_1",   60,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		PresR,		"TBXAI_1",   62,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7344:,		PresR,		"TBXAI_1",   64,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7581:,		PresR,		"TBXAI_1",   66,     FLOAT32_BE, 0,      25,     3,      "mbar",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI_1",   68,     FLOAT32_BE, 0,      25,     3,      "",		"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI_1",   70,     FLOAT32_BE, 0,      25,     3,      "",        "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		PresR,		"TBXAI_1",   72,     FLOAT32_BE, 0,      25,     3,      "",        "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		FBRB,		"TBXAI_1",   74,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second","TBx GV7503 FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		FBRB,		"TBXAI_1",   76,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		FBRB,		"TBXAI_1",   78,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		FBRB,		"TBXAI_1",   80,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		FBRB,		"TBXAI_1",   82,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		FBRB,		"TBXAI_1",   84,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		FBRB,		"TBXAI_1",   86,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		FBRB,		"TBXAI_1",   88,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		FBRB,		"TBXAI_1",   90,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		FBRB,		"TBXAI_1",   92,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		FBRB,		"TBXAI_1",   94,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		FBRB,		"TBXAI_1",   96,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		FBRB,		"TBXAI_1",   98,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		FBRB,		"TBXAI_1",  100,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		FBRB,		"TBXAI_1",  102,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		FBRB,		"TBXAI_1",  104,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		FBRB,		"TBXAI_1",  106,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		FBRB,		"TBXAI_1",  108,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		FBRB,		"TBXAI_1",  110,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		FBRB,		"TBXAI_1",  112,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		FBRB,		"TBXAI_1",  114,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		FBRB,		"TBXAI_1",  116,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		FBRB,		"TBXAI_1",  118,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		FBRB,		"TBXAI_1",  120,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-PDT7503:,		PresR,		"TBXAI_1",  122,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Press"}
{Cryo,	-CDL00:,	TBx01,	-PDT7504:,		PresR,		"TBXAI_1",  124,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Press"}

{Cryo,	-CDL00:,	TBx01,	-PDT7501:,		PresR,		"TBXAI_2",    0,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7502:,		PresR,		"TBXAI_2",	  2,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7301:,		PresR,		"TBXAI_2",    4,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7302:,		PresR,		"TBXAI_2",    6,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7401:,		PresR,		"TBXAI_2",    8,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7402:,		PresR,		"TBXAI_2",   10,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7543:,		PresR,		"TBXAI_2",   12,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7544:,		PresR,		"TBXAI_2",   14,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7541:,		PresR,		"TBXAI_2",   16,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7542:,		PresR,		"TBXAI_2",   18,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7341:,		PresR,		"TBXAI_2",   20,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7342:,		PresR,		"TBXAI_2",   22,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7441:,		PresR,		"TBXAI_2",   24,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7442:,		PresR,		"TBXAI_2",   26,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare1:,	PresR,		"TBXAI_2",   28,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare2:,	PresR,		"TBXAI_2",   30,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare3:,	PresR,		"TBXAI_2",   32,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		PresR,		"TBXAI_2",   34,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7508:,		PresR,		"TBXAI_2",   36,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7547:,		PresR,		"TBXAI_2",   38,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7548:,		PresR,		"TBXAI_2",   40,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		PresR,		"TBXAI_2",   42,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7483:,		PresR,		"TBXAI_2",   44,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI_2",   46,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI_2",   48,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		FBRB,		"TBXAI_2",   50,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		FBRB,		"TBXAI_2",   52,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		FBRB,		"TBXAI_2",   54,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		FBRB,		"TBXAI_2",   56,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7505:,		PresR,		"TBXAI_2",   58,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7506:,		PresR,		"TBXAI_2",   60,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7545:,		PresR,		"TBXAI_2",   62,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7546:,		PresR,		"TBXAI_2",   64,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7581:,		PresR,		"TBXAI_2",   66,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7582:,		PresR,		"TBXAI_2",   68,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7509:,		PresR,		"TBXAI_2",   70,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7549:,		PresR,		"TBXAI_2",   72,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI_2",   74,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI_2",   76,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
#{AI_165,															 78,																		}
#{AI_166,															 80,																		}
#{AI_167,															 82,																		}
#{AI_168,															 84,																		}
#{AI_169,															 86,																		}
#{AI_170,															 88,																		}
#{AI_171,															 90,																		}
#{AI_172,															 92,																		}
#{AI_173,															 94,																		}
#{AI_174,															 96,																		}
#{AI_175,															 98,																		}
#{AI_176,															100,																		}
#{AI_177,															102,																		}
#{AI_178,															104,																		}
#{AI_179,															106,																		}
#{AI_180,															108,																		}
#{AI_181,															110,																		}
#{AI_182,															112,																		}
#{AI_183,															114,																		}
#{AI_184,															116,																		}
#{AI_185,															118,																		}
#{AI_186,															120,																		}
#{AI_187,															122,																		}
#{AI_188,															124,																		}
#{AI_189,															 0,																		    }
#{AI_190,															 2,																		    }
#{AI_191,															 4,																		    }
#{AI_192,															 6,																		    }
#{AI_193,															 8,																		    }
#{AI_194,															10,																		    }
#{AI_195,															12,																		    }
#{AI_196,															14,																		    }
#{AI_197,															16,																		    }
#{AI_198,															18,																		    }
#{AI_199,															20,																		    }
}                                                                   

####AO Base Address 400word(800 PLC offset(byte))
file "db/aoFloat64.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,			SIGNAL,			PORT,		OFFSET, DATA_TYPE,	LOPR,	HOPR,	PREC,	EGU,	DESC}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		Setpt,			"TBXAO",	0,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		SetManuRamp,	"TBXAO",	2,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		Setpt,			"TBXAO",	4,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		SetManuRamp,	"TBXAO",	6,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		Setpt,			"TBXAO",	8,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		SetManuRamp,	"TBXAO",	10,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		Setpt,			"TBXAO",	12,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetManuRamp,	"TBXAO",	14,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		Setpt,			"TBXAO",	16,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		SetManuRamp,	"TBXAO",	18,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		Setpt,			"TBXAO",	20,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetManuRamp,	"TBXAO",	22,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		Setpt,			"TBXAO",	24,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetManuRamp,	"TBXAO",	26,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		Setpt,			"TBXAO",	28,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetManuRamp,	"TBXAO",	30,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		Setpt,			"TBXAO",	32,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		SetManuRamp,	"TBXAO",	34,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		Setpt,			"TBXAO",	36,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		SetManuRamp,	"TBXAO",	38,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		Setpt,			"TBXAO",	40,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		SetManuRamp,	"TBXAO",	42,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		Setpt,			"TBXAO",	44,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		SetManuRamp,	"TBXAO",	46,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		Setpt,			"TBXAO",	48,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetManuRamp,	"TBXAO",	50,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		Setpt,			"TBXAO",	52,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		SetManuRamp,	"TBXAO",	54,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		Setpt,			"TBXAO",	56,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		SetManuRamp,	"TBXAO",	58,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		Setpt,			"TBXAO",	60,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		SetManuRamp,	"TBXAO",	62,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		Setpt,			"TBXAO",	64,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetManuRamp,	"TBXAO",	66,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		Setpt,			"TBXAO",	68,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		SetManuRamp,	"TBXAO",	70,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		Setpt,			"TBXAO",	72,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetManuRamp,	"TBXAO",	74,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		Setpt,			"TBXAO",	76,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		SetManuRamp,	"TBXAO",	78,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		Setpt,			"TBXAO",	80,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		SetManuRamp,	"TBXAO",	82,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		Setpt,			"TBXAO",	84,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		SetManuRamp,	"TBXAO",	86,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		Setpt,			"TBXAO",	88,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		SetManuRamp,	"TBXAO",	90,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		Setpt,			"TBXAO",	92,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		SetManuRamp,	"TBXAO",	94,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		Setpt,			"TBXAO",	96,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetManuRamp,	"TBXAO",	98,		FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		Setpt,			"TBXAO",	100,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetManuRamp,	"TBXAO",	102,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		Setpt,			"TBXAO",	104,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		SetManuRamp,	"TBXAO",	106,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		Setpt,			"TBXAO",	108,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		SetManuRamp,	"TBXAO",	110,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7503:,		PressSet,	"TBXAO",	112,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7504:,		PressSet,	"TBXAO",	114,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7501:,		PressSet,	"TBXAO",	116,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7502:,		PressSet,	"TBXAO",	118,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7301:,		PressSet,	"TBXAO",	120,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7302:,		PressSet,	"TBXAO",	122,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7401:,		PressSet,	"TBXAO",	124,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7402:,		PressSet,	"TBXAO_1",	  0,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7543:,		PressSet,	"TBXAO_1",	  2,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7544:,		PressSet,	"TBXAO_1",	  4,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7541:,		PressSet,	"TBXAO_1",	  6,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7542:,		PressSet,	"TBXAO_1",	  8,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7341:,		PressSet,	"TBXAO_1",	 10,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7342:,		PressSet,	"TBXAO_1",	 12,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7441:,		PressSet,	"TBXAO_1",	 14,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDT7442:,		PressSet,	"TBXAO_1",	 16,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare1:,	PressSet,	"TBXAO_1",	 18,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare2:,	PressSet,	"TBXAO_1",	 20,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare3:,	PressSet,	"TBXAO_1",	 22,	FLOAT32_BE,	0,		30,		3,		"%",	"" }
}


###New list
Cryo-CDL00:TBx01-TT7543:SetOVR			608
Cryo-CDL00:TBx01-TT7541:SetOVR			610
Cryo-CDL00:TBx01-TT7544:SetOVR			612
Cryo-CDL00:TBx01-TT7542:SetOVR			614
Cryo-CDL00:TBx01-TT7581:SetOVR			616
Cryo-CDL00:TBx01-TT7582:SetOVR			618
Cryo-CDL00:TBx01-TTSpare1:SetOVR		620
Cryo-CDL00:TBx01-TTSpare2:SetOVR		622
Cryo-CDL00:TBx01-TT7241:SetOVR			624
Cryo-CDL00:TBx01-TT7242:SetOVR			626
Cryo-CDL00:TBx01-TT7341:SetOVR			628
Cryo-CDL00:TBx01-TT7342:SetOVR			630
Cryo-CDL00:TBx01-TT7441:SetOVR			632
Cryo-CDL00:TBx01-TT7442:SetOVR			634
Cryo-CDL00:TBx01-TTSpare3:SetOVR		636
Cryo-CDL00:TBx01-TTSpare4:SetOVR		638
Cryo-CDL00:TBx01-TT7503:SetOVR			640
Cryo-CDL00:TBx01-TT7501:SetOVR			642
Cryo-CDL00:TBx01-TT7504:SetOVR			644
Cryo-CDL00:TBx01-TT7502:SetOVR			646
Cryo-CDL00:TBx01-TT7583:SetOVR			648
Cryo-CDL00:TBx01-TTSpare5:SetOVR		650
Cryo-CDL00:TBx01-TTSpare6:SetOVR		652
Cryo-CDL00:TBx01-TTSpare7:SetOVR		654
Cryo-CDL00:TBx01-TT7303:SetOVR			656
Cryo-CDL00:TBx01-TT7343:SetOVR			658
Cryo-CDL00:TBx01-TTSpare8:SetOVR		660
Cryo-CDL00:TBx01-TTSpare9:SetOVR		662
Cryo-CDL00:TBx01-TTSpare10:SetOVR		664
Cryo-CDL00:TBx01-TTSpare11:SetOVR		666
Cryo-CDL00:TBx01-TTSpare12:SetOVR		668
Cryo-CDL00:TBx01-TTSpare13:SetOVR		670
Cryo-CDL00:TBx01-TT7201:SetOVR			672
Cryo-CDL00:TBx01-TT7202:SetOVR			674
Cryo-CDL00:TBx01-TT7301:SetOVR			676
Cryo-CDL00:TBx01-TT7302:SetOVR			678
Cryo-CDL00:TBx01-TT7401:SetOVR			680
Cryo-CDL00:TBx01-TT7402:SetOVR			682
Cryo-CDL00:TBx01-TT7381:SetOVR			684
Cryo-CDL00:TBx01-TTSpare14:SetOVR		686
Cryo-CDL00:TBx01-PT7101:SetOVR			688
Cryo-CDL00:TBx01-PT7102:SetOVR			690
Cryo-CDL00:TBx01-PT7103:SetOVR			692
Cryo-CDL00:TBx01-PT7104:SetOVR			694
Cryo-CDL00:TBx01-PT7181:SetOVR			696
Cryo-CDL00:TBx01-PTSpare1:SetOVR		698
Cryo-CDL00:TBx01-PT7141:SetOVR			700
Cryo-CDL00:TBx01-PT7142:SetOVR			702
Cryo-CDL00:TBx01-PT7143:SetOVR			704
Cryo-CDL00:TBx01-PT7144:SetOVR			706
Cryo-CDL00:TBx01-PTSpare2:SetOVR		708
Cryo-CDL00:TBx01-PTSpare3:SetOVR		710
Cryo-CDL00:TBx01-PT7106:SetOVR			712
Cryo-CDL00:TBx01-PT7105:SetOVR			714
Cryo-CDL00:TBx01-PT7146:SetOVR			716
Cryo-CDL00:TBx01-PT7145:SetOVR			718
Cryo-CDL00:TBx01-PT7182:SetOVR			720
Cryo-CDL00:TBx01-PTSpare4:SetOVR		722
Cryo-CDL00:TBx01-PT7504:SetOVR			724
Cryo-CDL00:TBx01-PT7501:SetOVR			726
Cryo-CDL00:TBx01-PT7301:SetOVR			728
Cryo-CDL00:TBx01-PT7401:SetOVR			730
Cryo-CDL00:TBx01-PT7203:SetOVR			732
Cryo-CDL00:TBx01-PT7201:SetOVR			734
Cryo-CDL00:TBx01-PT7202:SetOVR			736
Cryo-CDL00:TBx01-PT7305:SetOVR			738
Cryo-CDL00:TBx01-PT7506:SetOVR			740
Cryo-CDL00:TBx01-PT7502:SetOVR			742
Cryo-CDL00:TBx01-PT7302:SetOVR			744
Cryo-CDL00:TBx01-PT7402:SetOVR			746
Cryo-CDL00:TBx01-PT7544:SetOVR			748
Cryo-CDL00:TBx01-PT7541:SetOVR			750
Cryo-CDL00:TBx01-PT7341:SetOVR			752
Cryo-CDL00:TBx01-PT7441:SetOVR			754
Cryo-CDL00:TBx01-PT7306:SetOVR			756
Cryo-CDL00:TBx01-PT7304:SetOVR			758
Cryo-CDL00:TBx01-PT7505:SetOVR			760
Cryo-CDL00:TBx01-PT7503:SetOVR			762
Cryo-CDL00:TBx01-PT7303:SetOVR			764
Cryo-CDL00:TBx01-PT7403:SetOVR			766
Cryo-CDL00:TBx01-PT7545:SetOVR			768
Cryo-CDL00:TBx01-PT7542:SetOVR			770
Cryo-CDL00:TBx01-PT7243:SetOVR			772
Cryo-CDL00:TBx01-PT7241:SetOVR			774
Cryo-CDL00:TBx01-PT7242:SetOVR			776
Cryo-CDL00:TBx01-PT7342:SetOVR			778
Cryo-CDL00:TBx01-PT7442:SetOVR			780
Cryo-CDL00:TBx01-PT7546:SetOVR			782
Cryo-CDL00:TBx01-PT7543:SetOVR			784
Cryo-CDL00:TBx01-PT7343:SetOVR			786
Cryo-CDL00:TBx01-PT7443:SetOVR			788
Cryo-CDL00:TBx01-PT7381:SetOVR			790
Cryo-CDL00:TBx01-PT7345:SetOVR			792
Cryo-CDL00:TBx01-PT7344:SetOVR			794
Cryo-CDL00:TBx01-PT7581:SetOVR			796
Cryo-CDL00:TBx01-PTSpare1:SetOVR		798
Cryo-CDL00:TBx01-PTSpare2:SetOVR		800
Cryo-CDL00:TBx01-PTSpare3:SetOVR		802
Cryo-CDL00:TBx01-PDT7503:SetOVR			804
Cryo-CDL00:TBx01-PDT7504:SetOVR			806
Cryo-CDL00:TBx01-PDT7501:SetOVR			808
Cryo-CDL00:TBx01-PDT7502:SetOVR			810
Cryo-CDL00:TBx01-PDT7301:SetOVR			812
Cryo-CDL00:TBx01-PDT7302:SetOVR			814
Cryo-CDL00:TBx01-PDT7401:SetOVR			816
Cryo-CDL00:TBx01-PDT7402:SetOVR			818
Cryo-CDL00:TBx01-PDT7543:SetOVR			820
Cryo-CDL00:TBx01-PDT7544:SetOVR			822
Cryo-CDL00:TBx01-PDT7541:SetOVR			824
Cryo-CDL00:TBx01-PDT7542:SetOVR			826
Cryo-CDL00:TBx01-PDT7341:SetOVR			828
Cryo-CDL00:TBx01-PDT7342:SetOVR			830
Cryo-CDL00:TBx01-PDT7441:SetOVR			832
Cryo-CDL00:TBx01-PDT7442:SetOVR			834
Cryo-CDL00:TBx01-PDTSpare1:SetOVR		836
Cryo-CDL00:TBx01-PDTSpare2:SetOVR		838
Cryo-CDL00:TBx01-PDTSpare3:SetOVR		840
Cryo-CDL00:TBx01-PT7507:SetOVR			842
Cryo-CDL00:TBx01-PT7508:SetOVR			844
Cryo-CDL00:TBx01-PT7547:SetOVR			846
Cryo-CDL00:TBx01-PT7548:SetOVR			848
Cryo-CDL00:TBx01-PT7582:SetOVR			850
Cryo-CDL00:TBx01-PT7483:SetOVR			852
Cryo-CDL00:TBx01-PTSpare1:SetOVR		854
Cryo-CDL00:TBx01-PTSpare2:SetOVR		856
Cryo-CDL00:TBx01-PDT7505:SetOVR			858
Cryo-CDL00:TBx01-PDT7506:SetOVR			860
Cryo-CDL00:TBx01-PDT7545:SetOVR			862
Cryo-CDL00:TBx01-PDT7546:SetOVR			864
Cryo-CDL00:TBx01-PDT7581:SetOVR			866
Cryo-CDL00:TBx01-PDT7582:SetOVR			868
Cryo-CDL00:TBx01-PT7509:SetOVR			870
Cryo-CDL00:TBx01-PT7549:SetOVR			872
Cryo-CDL00:TBx01-PTSpare1:SetOVR		874
Cryo-CDL00:TBx01-PTSpare2:SetOVR		876
Cryo-CDL00:TBx01-TT7581:SetCP			878
Cryo-CDL00:TBx01-TT7581:SetDelayTime	880
Cryo-CDL00:TBx01-PT7501:SetCP			882
Cryo-CDL00:TBx01-PT7501:SetDelayTime	884
Cryo-CDL00:TBx01-PT7503:SetCP			886
Cryo-CDL00:TBx01-PT7503:SetDelayTime	888
Cryo-CDL00:TBx01-PT7504:SetCP			890
Cryo-CDL00:TBx01-PT7504:SetDelayTime	892
Cryo-CDL00:TBx01-PT7506:SetCP			894
Cryo-CDL00:TBx01-PT7506:SetDelayTime	896
Cryo-CDL00:TBx01-PT7507:SetCP			898
Cryo-CDL00:TBx01-PT7507:SetDelayTime	900
Cryo-CDL00:TBx01-PT7401:SetCP			902
Cryo-CDL00:TBx01-PT7401:SetDelayTime	904
Cryo-CDL00:TBx01-PT7403:SetCP			906
Cryo-CDL00:TBx01-PT7403:SetDelayTime	908
Cryo-CDL00:TBx01-PT7301:SetCP			910
Cryo-CDL00:TBx01-PT7301:SetDelayTime	912
Cryo-CDL00:TBx01-PT7303:SetCP			914
Cryo-CDL00:TBx01-PT7303:SetDelayTime	916
Cryo-CDL00:TBx01-PT7305:SetCP			918
Cryo-CDL00:TBx01-PT7305:SetDelayTime	920
Cryo-CDL00:TBx01-PT7201:SetCP			922
Cryo-CDL00:TBx01-PT7201:SetDelayTime	924
Cryo-CDL00:TBx01-PT7582:SetCP			926
Cryo-CDL00:TBx01-PT7582:SetDelayTime	928
Cryo-CDL00:TBx01-PT7483:SetCP			930
Cryo-CDL00:TBx01-PT7483:SetDelayTime	932
Cryo-CDL00:TBx01-PT7381:SetCPA			934
Cryo-CDL00:TBx01-PT7381:SetDelayTimeA	936
Cryo-CDL00:TBx01-PT7381:SetCPB			938
Cryo-CDL00:TBx01-PT7381:SetDelayTimeB	940
Cryo-CDL00:TBx01-PT7105:SetCP			942
Cryo-CDL00:TBx01-PT7105:SetDelayTime	944
Cryo-CDL00:TBx01-PT7106:SetCP			946
Cryo-CDL00:TBx01-PT7106:SetDelayTime	948
Cryo-CDL00:TBx01-PT7145:SetCP			950
Cryo-CDL00:TBx01-PT7145:SetDelayTime	952
Cryo-CDL00:TBx01-PT7146:SetCP			954
Cryo-CDL00:TBx01-PT7146:SetDelayTime	956
Cryo-CDL00:TBx01-PT7181:SetCP			958
Cryo-CDL00:TBx01-PT7181:SetDelayTime	960


####BI Base Address 550(1100 PLC offset(byte))
file "db/biWord.template" { pattern
{SYS,	SUBSYS,		DEV, 	SUBDEV,			SIGNAL,				PORT,		OFFSET,	MASK,	 ZNAM,   ONAM,		SCAN,		DESC}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		OpenStat,			TBXDI,		0,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		CloseStat,			TBXDI,		0,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		OpenStat,			TBXDI,		0,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		CloseStat,			TBXDI,		0,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		OpenStat,			TBXDI,		0,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		CloseStat,			TBXDI,		0,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		OpenStat,			TBXDI,		0,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		CloseStat,			TBXDI,		0,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		OpenStat,			TBXDI,		0,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		CloseStat,			TBXDI,		0,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		OpenStat,			TBXDI,		0,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		CloseStat,			TBXDI,		0,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		OpenStat,			TBXDI,		0,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		CloseStat,			TBXDI,		0,      0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		OpenStat,			TBXDI,		0,      0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		CloseStat,			TBXDI,		0,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		OpenStat,			TBXDI,		1,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		CloseStat,			TBXDI,		1,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		OpenStat,			TBXDI,		1,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		CloseStat,			TBXDI,		1,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		OpenStat,			TBXDI,		1,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		CloseStat,			TBXDI,		1,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		OpenStat,			TBXDI,		1,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		CloseStat,			TBXDI,		1,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		OpenStat,			TBXDI,		1,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		CloseStat,			TBXDI,		1,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		OpenStat,			TBXDI,		1,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		CloseStat,			TBXDI,		1,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		OpenStat,			TBXDI,		1,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		CloseStat,			TBXDI,		1,      0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		OpenStat,			TBXDI,		1,      0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		CloseStat,			TBXDI,		1,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		OpenStat,			TBXDI,		2,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		CloseStat,			TBXDI,		2,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		OpenStat,			TBXDI,		2,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		CloseStat,			TBXDI,		2,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		OpenStat,			TBXDI,		2,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		CloseStat,			TBXDI,		2,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		OpenStat,			TBXDI,		2,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		CloseStat,			TBXDI,		2,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		OpenStat,			TBXDI,		2,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		CloseStat,			TBXDI,		2,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		OpenStat,			TBXDI,		2,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		CloseStat,			TBXDI,		2,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		OpenStat,			TBXDI,		2,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		CloseStat,			TBXDI,		2,      0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		OpenStat,			TBXDI,		2,      0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		CloseStat,			TBXDI,		2,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		OpenStat,			TBXDI,		3,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		CloseStat,			TBXDI,		3,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		OpenStat,			TBXDI,		3,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		CloseStat,			TBXDI,		3,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		OpenStat,			TBXDI,		3,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		CloseStat,			TBXDI,		3,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		OpenStat,			TBXDI,		3,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		CloseStat,			TBXDI,		3,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		OpenStat,			TBXDI,		3,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		CloseStat,			TBXDI,		3,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		OpenStat,			TBXDI,		3,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		CloseStat,			TBXDI,		3,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		OpenStat,			TBXDI,		3,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		CloseStat,			TBXDI,		3,      0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		3,		0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		3,		0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7502:,		OpenErrR,			TBXDI,		4,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		CloseErrR,			TBXDI,		4,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		OpenErrR,			TBXDI,		4,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		CloseErrR,			TBXDI,		4,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		OpenErrR,			TBXDI,		4,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		CloseErrR,			TBXDI,		4,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		OpenErrR,			TBXDI,		4,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		CloseErrR,			TBXDI,		4,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		OpenErrR,			TBXDI,		4,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		CloseErrR,			TBXDI,		4,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		OpenErrR,			TBXDI,		4,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		CloseErrR,			TBXDI,		4,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		OpenErrR,			TBXDI,		4,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		CloseErrR,			TBXDI,		4,      0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		OpenErrR,			TBXDI,		4,      0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		CloseErrR,			TBXDI,		4,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		OpenErrR,			TBXDI,		5,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		CloseErrR,			TBXDI,		5,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		OpenErrR,			TBXDI,		5,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		CloseErrR,			TBXDI,		5,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		OpenErrR,			TBXDI,		5,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		CloseErrR,			TBXDI,		5,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		OpenErrR,			TBXDI,		5,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		CloseErrR,			TBXDI,		5,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		OpenErrR,			TBXDI,		5,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		CloseErrR,			TBXDI,		5,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		OpenErrR,			TBXDI,		5,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		CloseErrR,			TBXDI,		5,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		OpenErrR,			TBXDI,		5,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		CloseErrR,			TBXDI,		5,      0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		OpenErrR,			TBXDI,		5,      0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		CloseErrR,			TBXDI,		5,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		OpenErrR,			TBXDI,		6,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		CloseErrR,			TBXDI,		6,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		OpenErrR,			TBXDI,		6,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		CloseErrR,			TBXDI,		6,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		OpenErrR,			TBXDI,		6,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		CloseErrR,			TBXDI,		6,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		OpenErrR,			TBXDI,		6,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		CloseErrR,			TBXDI,		6,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		OpenErrR,			TBXDI,		6,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		CloseErrR,			TBXDI,		6,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		OpenErrR,			TBXDI,		6,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		CloseErrR,			TBXDI,		6,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		OpenErrR,			TBXDI,		6,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		CloseErrR,			TBXDI,		6,      0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		OpenErrR,			TBXDI,		6,      0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		CloseErrR,			TBXDI,		6,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		OpenErrR,			TBXDI,		7,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		CloseErrR,			TBXDI,		7,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		OpenErrR,			TBXDI,		7,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		CloseErrR,			TBXDI,		7,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		OpenErrR,			TBXDI,		7,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		CloseErrR,			TBXDI,		7,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		OpenErrR,			TBXDI,		7,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		CloseErrR,			TBXDI,		7,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		OpenErrR,			TBXDI,		7,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		CloseErrR,			TBXDI,		7,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		OpenErrR,			TBXDI,		7,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		CloseErrR,			TBXDI,		7,      0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		OpenErrR,			TBXDI,		7,      0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		CloseErrR,			TBXDI,		7,      0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		7,      0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		7,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7502:,		CloseStat,			TBXDI,		8,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		CloseStat,			TBXDI,		8,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		CloseStat,			TBXDI,		8,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		CloseStat,			TBXDI,		8,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		CloseStat,			TBXDI,		8,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		CloseStat,			TBXDI,		8,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		CloseStat,			TBXDI,		8,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		CloseStat,			TBXDI,		8,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		CloseStat,			TBXDI,		8,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		CloseStat,			TBXDI,		8,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		CloseStat,			TBXDI,		8,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		CloseStat,			TBXDI,		8,      0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7502:,		CloseErrR,			TBXDI,		9,      0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		CloseErrR,			TBXDI,		9,      0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		CloseErrR,			TBXDI,		9,      0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		CloseErrR,			TBXDI,		9,      0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		CloseErrR,			TBXDI,		9,      0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		CloseErrR,			TBXDI,		9,      0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		CloseErrR,			TBXDI,		9,      0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		CloseErrR,			TBXDI,		9,      0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		CloseErrR,			TBXDI,		9,      0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		CloseErrR,			TBXDI,		9,      0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		CloseErrR,			TBXDI,		9,      0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		CloseErrR,			TBXDI,		9,      0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7502:,		CloseStat,			TBXDI,		10,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		CloseStat,			TBXDI,		10,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		CloseStat,			TBXDI,		10,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		CloseStat,			TBXDI,		10,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		CloseStat,			TBXDI,		10,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		CloseStat,			TBXDI,		10,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		CloseStat,			TBXDI,		10,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		CloseStat,			TBXDI,		10,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		CloseStat,			TBXDI,		10,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		CloseStat,			TBXDI,		10,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		CloseStat,			TBXDI,		10,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		CloseStat,			TBXDI,		10,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		CloseStat,			TBXDI,		10,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		CloseStat,			TBXDI,		10,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		CloseStat,			TBXDI,		10,     0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		CloseStat,			TBXDI,		10,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		CloseStat,			TBXDI,		11,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		CloseStat,			TBXDI,		11,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		CloseStat,			TBXDI,		11,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		CloseStat,			TBXDI,		11,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		CloseStat,			TBXDI,		11,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		CloseStat,			TBXDI,		11,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		CloseStat,			TBXDI,		11,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		CloseStat,			TBXDI,		11,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		CloseStat,			TBXDI,		11,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		CloseStat,			TBXDI,		11,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		CloseStat,			TBXDI,		11,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		CloseStat,			TBXDI,		11,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		CloseStat,			TBXDI,		11,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		CloseStat,			TBXDI,		11,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		CloseStat,			TBXDI,		11,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		11,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7503:,		CloseStat,			TBXDI,		12,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		FailStat,			TBXDI,		12,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		CloseStat,			TBXDI,		12,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		FailStat,			TBXDI,		12,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		CloseStat,			TBXDI,		12,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		FailStat,			TBXDI,		12,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		CloseStat,			TBXDI,		12,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		FailStat,			TBXDI,		12,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		CloseStat,			TBXDI,		12,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		FailStat,			TBXDI,		12,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		CloseStat,			TBXDI,		12,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		FailStat,			TBXDI,		12,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		CloseStat,			TBXDI,		12,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		FailStat,			TBXDI,		12,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		CloseStat,			TBXDI,		12,     0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		FailStat,			TBXDI,		12,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7303:,		CloseStat,			TBXDI,		13,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		FailStat,			TBXDI,		13,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		CloseStat,			TBXDI,		13,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		FailStat,			TBXDI,		13,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		CloseStat,			TBXDI,		13,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		FailStat,			TBXDI,		13,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		CloseStat,			TBXDI,		13,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		FailStat,			TBXDI,		13,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		CloseStat,			TBXDI,		13,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		FailStat,			TBXDI,		13,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		CloseStat,			TBXDI,		13,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		FailStat,			TBXDI,		13,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		CloseStat,			TBXDI,		13,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		FailStat,			TBXDI,		13,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		CloseStat,			TBXDI,		13,     0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		FailStat,			TBXDI,		13,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7342:,		CloseStat,			TBXDI,		14,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		FailStat,			TBXDI,		14,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		CloseStat,			TBXDI,		14,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		FailStat,			TBXDI,		14,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		CloseStat,			TBXDI,		14,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		FailStat,			TBXDI,		14,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		CloseStat,			TBXDI,		14,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		FailStat,			TBXDI,		14,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		CloseStat,			TBXDI,		14,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		FailStat,			TBXDI,		14,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		CloseStat,			TBXDI,		14,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		FailStat,			TBXDI,		14,     0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7582:,		CloseStat,			TBXDI,		15,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		FailStat,			TBXDI,		15,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		CloseStat,			TBXDI,		15,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		FailStat,			TBXDI,		15,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		CloseStat,			TBXDI,		15,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		FailStat,			TBXDI,		15,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		CloseStat,			TBXDI,		15,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		FailStat,			TBXDI,		15,     0x8000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0001,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0002,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0004,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7103:,		SpdSet,				TBXDI,		16,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		NoErr,				TBXDI,		16,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		RemLoc,				TBXDI,		16,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		SPD,				TBXDI,		16,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		Mal,				TBXDI,		16,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		Warn,				TBXDI,		16,     0x2000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x4000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		SpdSet,				TBXDI,		16,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		NoErr,				TBXDI,		16,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		RemLoc,				TBXDI,		16,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		SPD,				TBXDI,		16,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		Mal,				TBXDI,		16,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		Warn,				TBXDI,		16,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7143:,		SpdSet,				TBXDI,		17,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		NoErr,				TBXDI,		17,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		RemLoc,				TBXDI,		17,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		SPD,				TBXDI,		17,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		Mal,				TBXDI,		17,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		Warn,				TBXDI,		17,     0x2000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x4000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		SpdSet,				TBXDI,		17,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		NoErr,				TBXDI,		17,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		RemLoc,				TBXDI,		17,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		SPD,				TBXDI,		17,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		Mal,				TBXDI,		17,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		Warn,				TBXDI,		17,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7181:,		SpdSet,				TBXDI,		18,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		NoErr,				TBXDI,		18,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		RemLoc,				TBXDI,		18,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		SPD,				TBXDI,		18,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		Mal,				TBXDI,		18,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		Warn,				TBXDI,		18,     0x2000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x4000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		SpdSet,				TBXDI,		18,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		NoErr,				TBXDI,		18,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		RemLoc,				TBXDI,		18,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		SPD,				TBXDI,		18,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		Mal,				TBXDI,		18,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		Warn,				TBXDI,		18,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-DP7103:,		OnR,				TBXDI,		19,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		OffR,				TBXDI,		19,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		TripRst,			TBXDI,		19,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		TripRPTC,			TBXDI,		19,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		OnR,				TBXDI,		19,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		OffR,				TBXDI,		19,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		TripRst,			TBXDI,		19,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		TripRPTC,			TBXDI,		19,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		OnR,				TBXDI,		19,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		OffR,				TBXDI,		19,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		TripRst,				TBXDI,		19,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		TripRPTC,			TBXDI,		19,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		OnR,				TBXDI,		19,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		OffR,				TBXDI,		19,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		TripRst,				TBXDI,		19,     0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		TripRPTC,			TBXDI,		19,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-DP7181:,		OnR,				TBXDI,		20,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		OffR,				TBXDI,		20,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		TripRst,				TBXDI,		20,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		TripRPTC,			TBXDI,		20,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		OnR,				TBXDI,		20,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		OffR,				TBXDI,		20,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		TripRst,				TBXDI,		20,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		TripRPTC,			TBXDI,		20,     0x8000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0001,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0002,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0004,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TT7543:,		Interlock,			TBXDI,		21,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7541:,		Interlock,			TBXDI,		21,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7544:,		Interlock,			TBXDI,		21,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7542:,		Interlock,			TBXDI,		21,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		Interlock,			TBXDI,		21,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7582:,		Interlock,			TBXDI,		21,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare1:,		Interlock,			TBXDI,		21,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare2:,		Interlock,			TBXDI,		21,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7241:,		Interlock,			TBXDI,		21,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7242:,		Interlock,			TBXDI,		21,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7341:,		Interlock,			TBXDI,		21,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7342:,		Interlock,			TBXDI,		21,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7441:,		Interlock,			TBXDI,		21,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7442:,		Interlock,			TBXDI,		21,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare3:,		Interlock,			TBXDI,		21,     0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare4:,		Interlock,			TBXDI,		21,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TT7503:,		Interlock,			TBXDI,		22,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7501:,		Interlock,			TBXDI,		22,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7504:,		Interlock,			TBXDI,		22,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7502:,		Interlock,			TBXDI,		22,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7583:,		Interlock,			TBXDI,		22,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare5:,		Interlock,			TBXDI,		22,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare6:,		Interlock,			TBXDI,		22,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare7:,		Interlock,			TBXDI,		22,     0x8000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7303:,		Interlock,			TBXDI,		22,     0x0001,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7343:,		Interlock,			TBXDI,		22,     0x0002,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare8:,		Interlock,			TBXDI,		22,     0x0004,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare9:,		Interlock,			TBXDI,		22,     0x0008,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare10:,	Interlock,			TBXDI,		22,     0x0010,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare11:,	Interlock,			TBXDI,		22,     0x0020,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare12:,	Interlock,			TBXDI,		22,     0x0040,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare13:,	Interlock,			TBXDI,		22,     0x0080,  Open,   Close,     "1 second", "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TT7201:,		Interlock,			TBXDI,		23,     0x0100,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7202:,		Interlock,			TBXDI,		23,     0x0200,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7301:,		Interlock,			TBXDI,		23,     0x0400,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7302:,		Interlock,			TBXDI,		23,     0x0800,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7401:,		Interlock,			TBXDI,		23,     0x1000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7402:,		Interlock,			TBXDI,		23,     0x2000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7381:,		Interlock,			TBXDI,		23,     0x4000,  Open,   Close,     "1 second", "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare14:,	Interlock,			TBXDI,		23,     0x8000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0001,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0002,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0004,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0080,  Open,   Close,     "1 second", "Switch1"}

#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0100,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0200,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0400,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0800,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x1000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x2000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x4000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x8000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0001,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0002,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0004,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0080,  Open,   Close,     "1 second", "Switch1"}

#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0100,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0200,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0400,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0800,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x1000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x2000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x4000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x8000,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0001,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0002,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0004,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0008,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0010,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0020,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0040,  Open,   Close,     "1 second", "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0080,  Open,   Close,     "1 second", "Switch1"}

}


##New List
Cryo-CDL91:TBx01-TT7543:Interlock	Cryo-CDL00:TBx01-XV7501:IntStatPT7501
Cryo-CDL91:TBx01-TT7541:Interlock	Cryo-CDL00:TBx01-XV7501:IntStatPT7503
Cryo-CDL91:TBx01-TT7544:Interlock	Cryo-CDL00:TBx01-XV7502:IntStatPT7504
Cryo-CDL91:TBx01-TT7542:Interlock	Cryo-CDL00:TBx01-XV7503:IntStatPT7507
Cryo-CDL91:TBx01-TT7581:Interlock	Cryo-CDL00:TBx01-XV7401:IntStatPT7401
Cryo-CDL91:TBx01-TT7582:Interlock	Cryo-CDL00:TBx01-XV7401:IntStatPT7403
Cryo-CDL91:TBx01-TTSpare1:Interlock	Cryo-CDL00:TBx01-XV7301:IntStatPT7301
Cryo-CDL91:TBx01-TTSpare2:Interlock	Cryo-CDL00:TBx01-XV7303:IntStatPT7305
Cryo-CDL91:TBx01-TT7241:Interlock	Cryo-CDL00:TBx01-XV7201:IntStatPT7201
Cryo-CDL91:TBx01-TT7242:Interlock	Cryo-CDL00:TBx01-CV7502:IntStatPT7503
Cryo-CDL91:TBx01-TT7341:Interlock	Cryo-CDL00:TBx01-CV7502:IntStatTT7581
Cryo-CDL91:TBx01-TT7342:Interlock	Cryo-CDL00:TBx01-CV7504:IntStatPT7506
Cryo-CDL91:TBx01-TT7441:Interlock	Cryo-CDL00:TBx01-CV7504:IntStatPT7381
Cryo-CDL91:TBx01-TT7442:Interlock	Cryo-CDL00:TBx01-CV7304:IntStatPT7303
Cryo-CDL91:TBx01-TTSpare3:Interlock	Cryo-CDL00:TBx01-CV7304:IntStatPT7381
Cryo-CDL91:TBx01-TTSpare4:Interlock	Cryo-CDL00:TBx01-CV7582:IntStatPT7503
Cryo-CDL91:TBx01-TT7503:Interlock	Cryo-CDL00:TBx01-CV7582:IntStatPT7582
Cryo-CDL91:TBx01-TT7501:Interlock	Cryo-CDL00:TBx01-CV7482:IntStatPT7403
Cryo-CDL91:TBx01-TT7504:Interlock	Cryo-CDL00:TBx01-CV7482:IntStatPT7483
Cryo-CDL91:TBx01-TT7502:Interlock	Cryo-CDL00:TBx01-XV7102:IntStatPT7105
Cryo-CDL91:TBx01-TT7583:Interlock	Cryo-CDL00:TBx01-XV7102:IntStatDP7102
Cryo-CDL91:TBx01-TTSpare5:Interlock	Cryo-CDL00:TBx01-XV7102:IntStatTP7102
Cryo-CDL91:TBx01-TTSpare6:Interlock	Cryo-CDL00:TBx01-XV7103:IntStatPT7106
Cryo-CDL91:TBx01-TTSpare7:Interlock	Cryo-CDL00:TBx01-XV7103:IntStatDP7103
Cryo-CDL91:TBx01-TT7303:Interlock	Cryo-CDL00:TBx01-XV7103:IntStatTP7103
Cryo-CDL91:TBx01-TT7343:Interlock	Cryo-CDL00:TBx01-XV7142:IntStatPT7145
Cryo-CDL91:TBx01-TTSpare8:Interlock	Cryo-CDL00:TBx01-XV7142:IntStatDP7142
Cryo-CDL91:TBx01-TTSpare9:Interlock	Cryo-CDL00:TBx01-XV7142:IntStatTP7142
Cryo-CDL91:TBx01-TTSpare10:Interlock	Cryo-CDL00:TBx01-XV7143:IntStatPT7146
Cryo-CDL91:TBx01-TTSpare11:Interlock	Cryo-CDL00:TBx01-XV7143:IntStatDP7143
Cryo-CDL91:TBx01-TTSpare12:Interlock	Cryo-CDL00:TBx01-XV7143:IntStatTP7143
Cryo-CDL91:TBx01-TTSpare13:Interlock	Cryo-CDL00:TBx01-XV7181:IntStatPT7181
Cryo-CDL91:TBx01-TT7201:Interlock	Cryo-CDL00:TBx01-XV7181:IntStatDP7181
Cryo-CDL91:TBx01-TT7202:Interlock	Cryo-CDL00:TBx01-XV7181:IntStatTP7181
Cryo-CDL91:TBx01-TT7301:Interlock	Cryo-CDL00:TBx01-TP7102:IntStatPT7105
Cryo-CDL91:TBx01-TT7302:Interlock	Cryo-CDL00:TBx01-TP7102:IntStatDP7102
Cryo-CDL91:TBx01-TT7401:Interlock	Cryo-CDL00:TBx01-TP7103:IntStatPT7106
Cryo-CDL91:TBx01-TT7402:Interlock	Cryo-CDL00:TBx01-TP7103:IntStatDP7103
Cryo-CDL91:TBx01-TT7381:Interlock	Cryo-CDL00:TBx01-TP7142:IntStatPT7145
Cryo-CDL91:TBx01-TTSpare14:Interlock	Cryo-CDL00:TBx01-TP7142:IntStatDP7142
1147.0	Cryo-CDL00:TBx01-TP7143:IntStatPT7146
1147.1	Cryo-CDL00:TBx01-TP7143:IntStatDP7143
1147.2	Cryo-CDL00:TBx01-TP7181:IntStatPT7181
1147.3	Cryo-CDL00:TBx01-TP7181:IntStatDP7181


####BO Base Address 576(550+26)(1152 PLC offset(byte))
file "db/boWord.template" { pattern
{SYS,	SUBSYS,		DEV, 	SUBDEV,			SIGNAL,				PORT,		OFFSET,	MASK,	 ZNAM,   ONAM,		DESC}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetManuOpen,		TBXDO,      0,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetManuClose,		TBXDO,      0,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetManuOpen,		TBXDO,      0,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetManuClose,		TBXDO,      0,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetManuOpen,		TBXDO,      0,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetManuClose,		TBXDO,      0,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetManuOpen,		TBXDO,      0,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetManuClose,		TBXDO,      0,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetManuOpen,		TBXDO,      0,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetManuClose,		TBXDO,      0,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetManuOpen,		TBXDO,      0,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetManuClose,		TBXDO,      0,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetManuOpen,		TBXDO,      0,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetManuClose,		TBXDO,      0,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetManuOpen,		TBXDO,      0,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetManuClose,		TBXDO,      0,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetManuOpen,		TBXDO,      1,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetManuClose,		TBXDO,      1,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetManuOpen,		TBXDO,      1,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetManuClose,		TBXDO,      1,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetManuOpen,		TBXDO,      1,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetManuClose,		TBXDO,      1,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetManuOpen,		TBXDO,      1,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetManuClose,		TBXDO,      1,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetManuOpen,		TBXDO,      1,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetManuClose,		TBXDO,      1,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetManuOpen,		TBXDO,      1,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetManuClose,		TBXDO,      1,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetManuOpen,		TBXDO,      1,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetManuClose,		TBXDO,      1,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetManuOpen,		TBXDO,      1,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetManuClose,		TBXDO,      1,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetManuOpen,		TBXDO,      2,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetManuClose,		TBXDO,      2,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetManuOpen,		TBXDO,      2,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetManuClose,		TBXDO,      2,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetManuOpen,		TBXDO,      2,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetManuClose,		TBXDO,      2,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetManuOpen,		TBXDO,      2,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetManuClose,		TBXDO,      2,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetManuOpen,		TBXDO,      2,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetManuClose,		TBXDO,      2,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetManuOpen,		TBXDO,      2,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetManuClose,		TBXDO,      2,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetManuOpen,		TBXDO,      2,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetManuClose,		TBXDO,      2,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetManuOpen,		TBXDO,      2,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetManuClose,		TBXDO,      2,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetManuOpen,		TBXDO,      3,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetManuClose,		TBXDO,      3,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetManuOpen,		TBXDO,      3,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetManuClose,		TBXDO,      3,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetManuOpen,		TBXDO,      3,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetManuClose,		TBXDO,      3,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetManuOpen,		TBXDO,      3,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetManuClose,		TBXDO,      3,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetManuOpen,		TBXDO,      3,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetManuClose,		TBXDO,      3,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetManuOpen,		TBXDO,      3,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetManuClose,		TBXDO,      3,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetManuOpen,		TBXDO,      3,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetManuClose,		TBXDO,      3,      0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      3,      0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      3,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetManuSel,			TBXDO,      4,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetFailRst,			TBXDO,      4,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetManuSel,			TBXDO,      4,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetFailRst,			TBXDO,      4,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetManuSel,			TBXDO,      4,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetFailRst,			TBXDO,      4,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetManuSel,			TBXDO,      4,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetFailRst,			TBXDO,      4,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetManuSel,			TBXDO,      4,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetFailRst,			TBXDO,      4,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetManuSel,			TBXDO,      4,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetFailRst,			TBXDO,      4,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetManuSel,			TBXDO,      4,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetFailRst,			TBXDO,      4,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetManuSel,			TBXDO,      4,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetFailRst,			TBXDO,      4,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetManuSel,			TBXDO,      5,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetFailRst,			TBXDO,      5,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetManuSel,			TBXDO,      5,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetFailRst,			TBXDO,      5,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetManuSel,			TBXDO,      5,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetFailRst,			TBXDO,      5,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetManuSel,			TBXDO,      5,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetFailRst,			TBXDO,      5,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetManuSel,			TBXDO,      5,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetFailRst,			TBXDO,      5,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetManuSel,			TBXDO,      5,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetFailRst,			TBXDO,      5,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetManuSel,			TBXDO,      5,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetFailRst,			TBXDO,      5,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetManuSel,			TBXDO,      5,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetFailRst,			TBXDO,      5,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetManuSel,			TBXDO,      6,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetFailRst,			TBXDO,      6,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetManuSel,			TBXDO,      6,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetFailRst,			TBXDO,      6,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetManuSel,			TBXDO,      6,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetFailRst,			TBXDO,      6,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetManuSel,			TBXDO,      6,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetFailRst,			TBXDO,      6,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetManuSel,			TBXDO,      6,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetFailRst,			TBXDO,      6,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetManuSel,			TBXDO,      6,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetFailRst,			TBXDO,      6,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetManuSel,			TBXDO,      6,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetFailRst,			TBXDO,      6,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetManuSel,			TBXDO,      6,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetFailRst,			TBXDO,      6,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetManuSel,			TBXDO,      7,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetFailRst,			TBXDO,      7,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetManuSel,			TBXDO,      7,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetFailRst,			TBXDO,      7,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetManuSel,			TBXDO,      7,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetFailRst,			TBXDO,      7,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetManuSel,			TBXDO,      7,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetFailRst,			TBXDO,      7,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetManuSel,			TBXDO,      7,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetFailRst,			TBXDO,      7,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetManuSel,			TBXDO,      7,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetFailRst,			TBXDO,      7,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetManuSel,			TBXDO,      7,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetFailRst,			TBXDO,      7,      0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      7,      0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      7,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7503:,		SetManuSel,			TBXDO,      8,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		SetFailRst,			TBXDO,      8,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		SetManuSel,			TBXDO,      8,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		SetFailRst,			TBXDO,      8,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		SetManuSel,			TBXDO,      8,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		SetFailRst,			TBXDO,      8,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetManuSel,			TBXDO,      8,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetFailRst,			TBXDO,      8,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		SetManuSel,			TBXDO,      8,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		SetFailRst,			TBXDO,      8,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetManuSel,			TBXDO,      8,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetFailRst,			TBXDO,      8,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetManuSel,			TBXDO,      8,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetFailRst,			TBXDO,      8,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetManuSel,			TBXDO,      8,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetFailRst,			TBXDO,      8,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7303:,		SetManuSel,			TBXDO,      9,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		SetFailRst,			TBXDO,      9,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		SetManuSel,			TBXDO,      9,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		SetFailRst,			TBXDO,      9,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		SetManuSel,			TBXDO,      9,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		SetFailRst,			TBXDO,      9,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		SetManuSel,			TBXDO,      9,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		SetFailRst,			TBXDO,      9,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetManuSel,			TBXDO,      9,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetFailRst,			TBXDO,      9,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		SetManuSel,			TBXDO,      9,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		SetFailRst,			TBXDO,      9,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		SetManuSel,			TBXDO,      9,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		SetFailRst,			TBXDO,      9,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		SetManuSel,			TBXDO,      9,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		SetFailRst,			TBXDO,      9,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetManuSel,			TBXDO,      10,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetFailRst,			TBXDO,      10,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		SetManuSel,			TBXDO,      10,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		SetFailRst,			TBXDO,      10,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetManuSel,			TBXDO,      10,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetFailRst,			TBXDO,      10,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		SetManuSel,			TBXDO,      10,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		SetFailRst,			TBXDO,      10,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		SetManuSel,			TBXDO,      10,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		SetFailRst,			TBXDO,      10,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		SetManuSel,			TBXDO,      10,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		SetFailRst,			TBXDO,      10,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		SetManuSel,			TBXDO,      10,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		SetFailRst,			TBXDO,      10,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		SetManuSel,			TBXDO,      10,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		SetFailRst,			TBXDO,      10,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetManuSel,			TBXDO,      11,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetFailRst,			TBXDO,      11,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetManuSel,			TBXDO,      11,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetFailRst,			TBXDO,      11,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		SetManuSel,			TBXDO,      11,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		SetFailRst,			TBXDO,      11,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		SetManuSel,			TBXDO,      11,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		SetFailRst,			TBXDO,      11,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		On,					TBXDO,      11,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		Off,				TBXDO,      11,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		TripRst,			TBXDO,      11,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		On,					TBXDO,      11,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		Off,				TBXDO,      11,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		TripRst,			TBXDO,      11,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		On,					TBXDO,      11,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		Off,				TBXDO,      11,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-DP7143:,		TripRst,			TBXDO,      12,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		On,					TBXDO,      12,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		Off,				TBXDO,      12,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		TripRst,			TBXDO,      12,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		On,					TBXDO,      12,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		Off,				TBXDO,      12,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		TripRst,			TBXDO,      12,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		On,					TBXDO,      12,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		Off,				TBXDO,      12,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		TripRst,			TBXDO,      12,     0x0002,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0004,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0008,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0010,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7103:,		VentLc,				TBXDO,      13,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		TMPOnOff,			TBXDO,      13,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		DPOnOff,			TBXDO,      13,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		StnOnOff,			TBXDO,      13,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		ErrRstAut,			TBXDO,      13,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		Priority,			TBXDO,      13,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		VentLc,				TBXDO,      13,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		TMPOnOff,			TBXDO,      13,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		DPOnOff,			TBXDO,      13,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		StnOnOff,			TBXDO,      13,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		ErrRstAut,			TBXDO,      13,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		Priority,			TBXDO,      13,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7143:,		VentLc,				TBXDO,      14,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		TMPOnOff,			TBXDO,      14,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		DPOnOff,			TBXDO,      14,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		StnOnOff,			TBXDO,      14,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		ErrRstAut,			TBXDO,      14,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		Priority,			TBXDO,      14,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		VentLc,				TBXDO,      14,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		TMPOnOff,			TBXDO,      14,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		DPOnOff,			TBXDO,      14,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		StnOnOff,			TBXDO,      14,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		ErrRstAut,			TBXDO,      14,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		Priority,			TBXDO,      14,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7181:,		VentLc,				TBXDO,      15,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		TMPOnOff,			TBXDO,      15,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		DPOnOff,			TBXDO,      15,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		StnOnOff,			TBXDO,      15,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		ErrRstAut,			TBXDO,      15,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		Priority,			TBXDO,      15,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		VentLc,				TBXDO,      15,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		TMPOnOff,			TBXDO,      15,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		DPOnOff,			TBXDO,      15,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		StnOnOff,			TBXDO,      15,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		ErrRstAut,			TBXDO,      15,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		Priority,			TBXDO,      15,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7101:,		SetAlm,				TBXDO,      16,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7102:,		SetAlm,				TBXDO,      16,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7103:,		SetAlm,				TBXDO,      16,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7104:,		SetAlm,				TBXDO,      16,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		SetAlm,				TBXDO,      16,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetAlm,				TBXDO,      16,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7141:,		SetAlm,				TBXDO,      16,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7142:,		SetAlm,				TBXDO,      16,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7143:,		SetAlm,				TBXDO,      16,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7144:,		SetAlm,				TBXDO,      16,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetAlm,				TBXDO,      16,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		SetAlm,				TBXDO,      16,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		SetAlm,				TBXDO,      16,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		SetAlm,				TBXDO,      16,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		SetAlm,				TBXDO,      16,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		SetAlm,				TBXDO,      16,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7182:,		SetAlm,				TBXDO,      17,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare4:,		SetAlm,				TBXDO,      17,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		SetAlm,				TBXDO,      17,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		SetAlm,				TBXDO,      17,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		SetAlm,				TBXDO,      17,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		SetAlm,				TBXDO,      17,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		SetAlm,				TBXDO,      17,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7241:,		SetAlm,				TBXDO,      17,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7202:,		SetAlm,				TBXDO,      17,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7305:,		SetAlm,				TBXDO,      17,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7505:,		SetAlm,				TBXDO,      17,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7502:,		SetAlm,				TBXDO,      17,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7302:,		SetAlm,				TBXDO,      17,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7402:,		SetAlm,				TBXDO,      17,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7544:,		SetAlm,				TBXDO,      17,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7541:,		SetAlm,				TBXDO,      17,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7341:,		SetAlm,				TBXDO,      18,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7441:,		SetAlm,				TBXDO,      18,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7306:,		SetAlm,				TBXDO,      18,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7304:,		SetAlm,				TBXDO,      18,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		SetAlm,				TBXDO,      18,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7503:,		SetAlm,				TBXDO,      18,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		SetAlm,				TBXDO,      18,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		SetAlm,				TBXDO,      18,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7545:,		SetAlm,				TBXDO,      18,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7542:,		SetAlm,				TBXDO,      18,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7203:,		SetAlm,				TBXDO,      18,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7243:,		SetAlm,				TBXDO,      18,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7242:,		SetAlm,				TBXDO,      18,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7342:,		SetAlm,				TBXDO,      18,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7442:,		SetAlm,				TBXDO,      18,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7546:,		SetAlm,				TBXDO,      18,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7543:,		SetAlm,				TBXDO,      19,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7343:,		SetAlm,				TBXDO,      19,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7443:,		SetAlm,				TBXDO,      19,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		SetAlm,				TBXDO,      19,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		SetAlm,				TBXDO,      19,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7344:,		SetAlm,				TBXDO,      19,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7581:,		SetAlm,				TBXDO,      19,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetAlm,				TBXDO,      19,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetAlm,				TBXDO,      19,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		SetAlm,				TBXDO,      19,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		SetAlm,				TBXDO,      19,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7508:,		SetAlm,				TBXDO,      19,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7547:,		SetAlm,				TBXDO,      19,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7548:,		SetAlm,				TBXDO,      19,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		SetAlm,				TBXDO,      19,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7583:,		SetAlm,				TBXDO,      19,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetAlm,				TBXDO,      20,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetAlm,				TBXDO,      20,     0x0200,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0400,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0800,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x1000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x8000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0001,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0002,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0004,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0008,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0010,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0080,  Open,   Close, "Switch1"}

#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0100,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0200,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0400,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0800,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x1000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x8000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0001,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0002,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0004,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0008,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0010,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      21,     0x0080,  Open,   Close, "Switch1"}

}


##New List
Cryo-CDL91:TBx01-PT7101:SetAlm	Cryo-CDL00:TBx01-XV7501:SetIntRst
Cryo-CDL91:TBx01-PT7102:SetAlm	Cryo-CDL00:TBx01-XV7501:SetIntPT7501DS
Cryo-CDL91:TBx01-PT7103:SetAlm	Cryo-CDL00:TBx01-XV7501:SetIntPT7503DS
Cryo-CDL91:TBx01-PT7104:SetAlm	Cryo-CDL00:TBx01-XV7502:SetIntRst
Cryo-CDL91:TBx01-PT7181:SetAlm	Cryo-CDL00:TBx01-XV7502:SetIntPT7504DS
Cryo-CDL91:TBx01-PTSpare1:SetAlm	Cryo-CDL00:TBx01-XV7503:SetIntRst
Cryo-CDL91:TBx01-PT7141:SetAlm	Cryo-CDL00:TBx01-XV7503:SetIntPT7507DS
Cryo-CDL91:TBx01-PT7142:SetAlm	Cryo-CDL00:TBx01-XV7401:SetIntRst
Cryo-CDL91:TBx01-PT7143:SetAlm	Cryo-CDL00:TBx01-XV7401:SetIntPT7401DS
Cryo-CDL91:TBx01-PT7144:SetAlm	Cryo-CDL00:TBx01-XV7401:SetIntPT7403DS
Cryo-CDL91:TBx01-PTSpare2:SetAlm	Cryo-CDL00:TBx01-XV7301:SetIntRst
Cryo-CDL91:TBx01-PTSpare3:SetAlm	Cryo-CDL00:TBx01-XV7301:SetIntPT7301DS
Cryo-CDL91:TBx01-PT7106:SetAlm	Cryo-CDL00:TBx01-XV7303:SetIntRst
Cryo-CDL91:TBx01-PT7105:SetAlm	Cryo-CDL00:TBx01-XV7303:SetIntPT7305DS
Cryo-CDL91:TBx01-PT7146:SetAlm	Cryo-CDL00:TBx01-XV7201:SetIntRst
Cryo-CDL91:TBx01-PT7145:SetAlm	Cryo-CDL00:TBx01-XV7201:SetIntPT7201DS
Cryo-CDL91:TBx01-PT7182:SetAlm	Cryo-CDL00:TBx01-CV7502:SetIntRst
Cryo-CDL91:TBx01-PTSpare4:SetAlm	Cryo-CDL00:TBx01-CV7502:SetIntPT7503DS
Cryo-CDL91:TBx01-PT7504:SetAlm	Cryo-CDL00:TBx01-CV7502:SetIntTT7581DS
Cryo-CDL91:TBx01-PT7501:SetAlm	Cryo-CDL00:TBx01-CV7504:SetIntRst
Cryo-CDL91:TBx01-PT7301:SetAlm	Cryo-CDL00:TBx01-CV7504:SetIntPT7506DS
Cryo-CDL91:TBx01-PT7401:SetAlm	Cryo-CDL00:TBx01-CV7504:SetIntPT7381DS
Cryo-CDL91:TBx01-PT7201:SetAlm	Cryo-CDL00:TBx01-CV7304:SetIntRst
Cryo-CDL91:TBx01-PT7241:SetAlm	Cryo-CDL00:TBx01-CV7304:SetIntPT7303DS
Cryo-CDL91:TBx01-PT7202:SetAlm	Cryo-CDL00:TBx01-CV7304:SetIntPT7381DS
Cryo-CDL91:TBx01-PT7305:SetAlm	Cryo-CDL00:TBx01-CV7582:SetIntRst
Cryo-CDL91:TBx01-PT7505:SetAlm	Cryo-CDL00:TBx01-CV7582:SetIntPT7503DS
Cryo-CDL91:TBx01-PT7502:SetAlm	Cryo-CDL00:TBx01-CV7582:SetIntPT7582DS
Cryo-CDL91:TBx01-PT7302:SetAlm	Cryo-CDL00:TBx01-CV7482:SetIntRst
Cryo-CDL91:TBx01-PT7402:SetAlm	Cryo-CDL00:TBx01-CV7482:SetIntPT7403DS
Cryo-CDL91:TBx01-PT7544:SetAlm	Cryo-CDL00:TBx01-CV7482:SetIntPT7483DS
Cryo-CDL91:TBx01-PT7541:SetAlm	Cryo-CDL00:TBx01-XV7102:SetIntRst
Cryo-CDL91:TBx01-PT7341:SetAlm	Cryo-CDL00:TBx01-XV7102:IntStatPT7105DS
Cryo-CDL91:TBx01-PT7441:SetAlm	Cryo-CDL00:TBx01-XV7102:IntStatDP7102DS
Cryo-CDL91:TBx01-PT7306:SetAlm	Cryo-CDL00:TBx01-XV7102:IntStatTP7102DS
Cryo-CDL91:TBx01-PT7304:SetAlm	Cryo-CDL00:TBx01-XV7103:SetIntRst
Cryo-CDL91:TBx01-PT7506:SetAlm	Cryo-CDL00:TBx01-XV7103:IntStatPT7106DS
Cryo-CDL91:TBx01-PT7503:SetAlm	Cryo-CDL00:TBx01-XV7103:IntStatDP7103DS
Cryo-CDL91:TBx01-PT7303:SetAlm	Cryo-CDL00:TBx01-XV7103:IntStatTP7103DS
Cryo-CDL91:TBx01-PT7403:SetAlm	Cryo-CDL00:TBx01-XV7142:SetIntRst
Cryo-CDL91:TBx01-PT7545:SetAlm	Cryo-CDL00:TBx01-XV7142:IntStatPT7145DS
Cryo-CDL91:TBx01-PT7542:SetAlm	Cryo-CDL00:TBx01-XV7142:IntStatDP7142DS
Cryo-CDL91:TBx01-PT7203:SetAlm	Cryo-CDL00:TBx01-XV7142:IntStatTP7142DS
Cryo-CDL91:TBx01-PT7243:SetAlm	Cryo-CDL00:TBx01-XV7143:SetIntRst
Cryo-CDL91:TBx01-PT7242:SetAlm	Cryo-CDL00:TBx01-XV7143:IntStatPT7146DS
Cryo-CDL91:TBx01-PT7342:SetAlm	Cryo-CDL00:TBx01-XV7143:IntStatDP7143DS
Cryo-CDL91:TBx01-PT7442:SetAlm	Cryo-CDL00:TBx01-XV7143:IntStatTP7143DS
Cryo-CDL91:TBx01-PT7546:SetAlm	Cryo-CDL00:TBx01-XV7181:SetIntRst
Cryo-CDL91:TBx01-PT7543:SetAlm	Cryo-CDL00:TBx01-XV7181:IntStatPT7181DS
Cryo-CDL91:TBx01-PT7343:SetAlm	Cryo-CDL00:TBx01-XV7181:IntStatDP7181DS
Cryo-CDL91:TBx01-PT7443:SetAlm	Cryo-CDL00:TBx01-XV7181:IntStatTP7181DS
Cryo-CDL91:TBx01-PT7381:SetAlm	Cryo-CDL00:TBx01-TP7102:SetIntRst
Cryo-CDL91:TBx01-PT7345:SetAlm	Cryo-CDL00:TBx01-TP7102:IntStatPT7105DS
Cryo-CDL91:TBx01-PT7344:SetAlm	Cryo-CDL00:TBx01-TP7102:IntStatDP7102DS
Cryo-CDL91:TBx01-PT7581:SetAlm	Cryo-CDL00:TBx01-TP7103:SetIntRst
Cryo-CDL91:TBx01-PTSpare1:SetAlm	Cryo-CDL00:TBx01-TP7103:IntStatPT7106DS
Cryo-CDL91:TBx01-PTSpare2:SetAlm	Cryo-CDL00:TBx01-TP7103:IntStatDP7103DS
Cryo-CDL91:TBx01-PTSpare3:SetAlm	Cryo-CDL00:TBx01-TP7142:SetIntRst
Cryo-CDL91:TBx01-PT7507:SetAlm	Cryo-CDL00:TBx01-TP7142:IntStatPT7145DS
Cryo-CDL91:TBx01-PT7508:SetAlm	Cryo-CDL00:TBx01-TP7142:IntStatDP7142DS
Cryo-CDL91:TBx01-PT7547:SetAlm	Cryo-CDL00:TBx01-TP7143:SetIntRst
Cryo-CDL91:TBx01-PT7548:SetAlm	Cryo-CDL00:TBx01-TP7143:IntStatPT7146DS
Cryo-CDL91:TBx01-PT7582:SetAlm	Cryo-CDL00:TBx01-TP7143:IntStatDP7143DS
Cryo-CDL91:TBx01-PT7583:SetAlm	Cryo-CDL00:TBx01-TP7181:SetIntRst
Cryo-CDL91:TBx01-PTSpare1:SetAlm	Cryo-CDL00:TBx01-TP7181:IntStatPT7181DS
Cryo-CDL91:TBx01-PTSpare2:SetAlm	Cryo-CDL00:TBx01-TP7181:IntStatDP7181DS


Cryo-CDL00:TBx01-TT7543:SetOVREN
Cryo-CDL00:TBx01-TT7541:SetOVREN
Cryo-CDL00:TBx01-TT7544:SetOVREN
Cryo-CDL00:TBx01-TT7542:SetOVREN
Cryo-CDL00:TBx01-TT7581:SetOVREN
Cryo-CDL00:TBx01-TT7582:SetOVREN
Cryo-CDL00:TBx01-TTSpare1:SetOVREN
Cryo-CDL00:TBx01-TTSpare2:SetOVREN
Cryo-CDL00:TBx01-TT7241:SetOVREN
Cryo-CDL00:TBx01-TT7242:SetOVREN
Cryo-CDL00:TBx01-TT7341:SetOVREN
Cryo-CDL00:TBx01-TT7342:SetOVREN
Cryo-CDL00:TBx01-TT7441:SetOVREN
Cryo-CDL00:TBx01-TT7442:SetOVREN
Cryo-CDL00:TBx01-TTSpare3:SetOVREN
Cryo-CDL00:TBx01-TTSpare4:SetOVREN
Cryo-CDL00:TBx01-TT7503:SetOVREN
Cryo-CDL00:TBx01-TT7501:SetOVREN
Cryo-CDL00:TBx01-TT7504:SetOVREN
Cryo-CDL00:TBx01-TT7502:SetOVREN
Cryo-CDL00:TBx01-TT7583:SetOVREN
Cryo-CDL00:TBx01-TTSpare5:SetOVREN
Cryo-CDL00:TBx01-TTSpare6:SetOVREN
Cryo-CDL00:TBx01-TTSpare7:SetOVREN
Cryo-CDL00:TBx01-TT7303:SetOVREN
Cryo-CDL00:TBx01-TT7343:SetOVREN
Cryo-CDL00:TBx01-TTSpare8:SetOVREN
Cryo-CDL00:TBx01-TTSpare9:SetOVREN
Cryo-CDL00:TBx01-TTSpare10:SetOVREN
Cryo-CDL00:TBx01-TTSpare11:SetOVREN
Cryo-CDL00:TBx01-TTSpare12:SetOVREN
Cryo-CDL00:TBx01-TTSpare13:SetOVREN
Cryo-CDL00:TBx01-TT7201:SetOVREN
Cryo-CDL00:TBx01-TT7202:SetOVREN
Cryo-CDL00:TBx01-TT7301:SetOVREN
Cryo-CDL00:TBx01-TT7302:SetOVREN
Cryo-CDL00:TBx01-TT7401:SetOVREN
Cryo-CDL00:TBx01-TT7402:SetOVREN
Cryo-CDL00:TBx01-TT7381:SetOVREN
Cryo-CDL00:TBx01-TTSpare14:SetOVREN
Cryo-CDL00:TBx01-PT7101:SetOVREN
Cryo-CDL00:TBx01-PT7102:SetOVREN
Cryo-CDL00:TBx01-PT7103:SetOVREN
Cryo-CDL00:TBx01-PT7104:SetOVREN
Cryo-CDL00:TBx01-PT7181:SetOVREN
Cryo-CDL00:TBx01-PTSpare1:SetOVREN
Cryo-CDL00:TBx01-PT7141:SetOVREN
Cryo-CDL00:TBx01-PT7142:SetOVREN
Cryo-CDL00:TBx01-PT7143:SetOVREN
Cryo-CDL00:TBx01-PT7144:SetOVREN
Cryo-CDL00:TBx01-PTSpare2:SetOVREN
Cryo-CDL00:TBx01-PTSpare3:SetOVREN
Cryo-CDL00:TBx01-PT7106:SetOVREN
Cryo-CDL00:TBx01-PT7105:SetOVREN
Cryo-CDL00:TBx01-PT7146:SetOVREN
Cryo-CDL00:TBx01-PT7145:SetOVREN
Cryo-CDL00:TBx01-PT7182:SetOVREN
Cryo-CDL00:TBx01-PTSpare4:SetOVREN
Cryo-CDL00:TBx01-PT7504:SetOVREN
Cryo-CDL00:TBx01-PT7501:SetOVREN
Cryo-CDL00:TBx01-PT7301:SetOVREN
Cryo-CDL00:TBx01-PT7401:SetOVREN
Cryo-CDL00:TBx01-PT7203:SetOVREN
Cryo-CDL00:TBx01-PT7201:SetOVREN
Cryo-CDL00:TBx01-PT7202:SetOVREN
Cryo-CDL00:TBx01-PT7305:SetOVREN
Cryo-CDL00:TBx01-PT7506:SetOVREN
Cryo-CDL00:TBx01-PT7502:SetOVREN
Cryo-CDL00:TBx01-PT7302:SetOVREN
Cryo-CDL00:TBx01-PT7402:SetOVREN
Cryo-CDL00:TBx01-PT7544:SetOVREN
Cryo-CDL00:TBx01-PT7541:SetOVREN
Cryo-CDL00:TBx01-PT7341:SetOVREN
Cryo-CDL00:TBx01-PT7441:SetOVREN
Cryo-CDL00:TBx01-PT7306:SetOVREN
Cryo-CDL00:TBx01-PT7304:SetOVREN
Cryo-CDL00:TBx01-PT7505:SetOVREN
Cryo-CDL00:TBx01-PT7503:SetOVREN
Cryo-CDL00:TBx01-PT7303:SetOVREN
Cryo-CDL00:TBx01-PT7403:SetOVREN
Cryo-CDL00:TBx01-PT7545:SetOVREN
Cryo-CDL00:TBx01-PT7542:SetOVREN
Cryo-CDL00:TBx01-PT7243:SetOVREN
Cryo-CDL00:TBx01-PT7241:SetOVREN
Cryo-CDL00:TBx01-PT7242:SetOVREN
Cryo-CDL00:TBx01-PT7342:SetOVREN
Cryo-CDL00:TBx01-PT7442:SetOVREN
Cryo-CDL00:TBx01-PT7546:SetOVREN
Cryo-CDL00:TBx01-PT7543:SetOVREN
Cryo-CDL00:TBx01-PT7343:SetOVREN
Cryo-CDL00:TBx01-PT7443:SetOVREN
Cryo-CDL00:TBx01-PT7381:SetOVREN
Cryo-CDL00:TBx01-PT7345:SetOVREN
Cryo-CDL00:TBx01-PT7344:SetOVREN
Cryo-CDL00:TBx01-PT7581:SetOVREN
Cryo-CDL00:TBx01-PTSpare1:SetOVREN
Cryo-CDL00:TBx01-PTSpare2:SetOVREN
Cryo-CDL00:TBx01-PTSpare3:SetOVREN
Cryo-CDL00:TBx01-PDT7503:SetOVREN
Cryo-CDL00:TBx01-PDT7504:SetOVREN
Cryo-CDL00:TBx01-PDT7501:SetOVREN
Cryo-CDL00:TBx01-PDT7502:SetOVREN
Cryo-CDL00:TBx01-PDT7301:SetOVREN
Cryo-CDL00:TBx01-PDT7302:SetOVREN
Cryo-CDL00:TBx01-PDT7401:SetOVREN
Cryo-CDL00:TBx01-PDT7402:SetOVREN
Cryo-CDL00:TBx01-PDT7543:SetOVREN
Cryo-CDL00:TBx01-PDT7544:SetOVREN
Cryo-CDL00:TBx01-PDT7541:SetOVREN
Cryo-CDL00:TBx01-PDT7542:SetOVREN
Cryo-CDL00:TBx01-PDT7341:SetOVREN
Cryo-CDL00:TBx01-PDT7342:SetOVREN
Cryo-CDL00:TBx01-PDT7441:SetOVREN
Cryo-CDL00:TBx01-PDT7442:SetOVREN
Cryo-CDL00:TBx01-PDTSpare1:SetOVREN
Cryo-CDL00:TBx01-PDTSpare2:SetOVREN
Cryo-CDL00:TBx01-PDTSpare3:SetOVREN
Cryo-CDL00:TBx01-PT7507:SetOVREN
Cryo-CDL00:TBx01-PT7508:SetOVREN
Cryo-CDL00:TBx01-PT7547:SetOVREN
Cryo-CDL00:TBx01-PT7548:SetOVREN
Cryo-CDL00:TBx01-PT7582:SetOVREN
Cryo-CDL00:TBx01-PT7483:SetOVREN
Cryo-CDL00:TBx01-PTSpare1:SetOVREN
Cryo-CDL00:TBx01-PTSpare2:SetOVREN
Cryo-CDL00:TBx01-PDT7505:SetOVREN
Cryo-CDL00:TBx01-PDT7506:SetOVREN
Cryo-CDL00:TBx01-PDT7545:SetOVREN
Cryo-CDL00:TBx01-PDT7546:SetOVREN
Cryo-CDL00:TBx01-PDT7581:SetOVREN
Cryo-CDL00:TBx01-PDT7582:SetOVREN
Cryo-CDL00:TBx01-PT7509:SetOVREN
Cryo-CDL00:TBx01-PT7549:SetOVREN
Cryo-CDL00:TBx01-PTSpare1:SetOVREN
Cryo-CDL00:TBx01-PTSpare2:SetOVREN


