file "db/aiFloat64.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,			SIGNAL,		PORT,		OFFSET, DATA_TYPE,	LOPR,	HOPR,	PREC,	EGU,		SCAN,		DESC}
{Cryo,	-CDL00:,	TBx01,	-PT7101:,		PresR,		"TBXAI",	  0,	 FLOAT32_BE, 0,		 1100,	 2,		 "mbara",	"1 second",	"TBx PT7101 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7102:,		PresR,		"TBXAI",	  2,	 FLOAT32_BE, 0,		 1100,	 2,		 "mbara",	"1 second",	"TBx PT7102 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7103:,		PresR,		"TBXAI",      4,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7103 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7104:,		PresR,		"TBXAI",      6,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7104 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		PresR,		"TBXAI",      8,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7181 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI",     10,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PTSpare1 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7141:,		PresR,		"TBXAI",     12,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7141 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7142:,		PresR,		"TBXAI",     14,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7142 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7143:,		PresR,		"TBXAI",     16,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7143 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7144:,		PresR,		"TBXAI",     18,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7144 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI",     20,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PTSpare2 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		PresR,		"TBXAI",     22,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PTSpare3 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		PresR,		"TBXAI",     24,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7106 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		PresR,		"TBXAI",     26,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7105 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		PresR,		"TBXAI",     28,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7146 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		PresR,		"TBXAI",     30,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7145 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7182:,		PresR,		"TBXAI",     32,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PT7182 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare4:,		PresR,		"TBXAI",     34,     FLOAT32_BE, 0,      1100,   2,      "mbara",	"1 second", "TBx PTSpare4 Press"}
#{AI_72																 36,																			}
#{AI_76																 38,																			}
{Cryo,	-CDL00:,	TBx01,	-TT7543:,		TempR,		"TBXAI",     40,     FLOAT32_BE, 0,      350,    1,      "K",		"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7541:,		TempR,		"TBXAI",     42,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7544:,		TempR,		"TBXAI",     44,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7542:,		TempR,		"TBXAI",     46,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		TempR,		"TBXAI",     48,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7582:,		TempR,		"TBXAI",     50,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare1:,		TempR,		"TBXAI",     52,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare2:,		TempR,		"TBXAI",     54,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7241:,		TempR,		"TBXAI",     56,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7242:,		TempR,		"TBXAI",     58,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7341:,		TempR,		"TBXAI",     60,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7342:,		TempR,		"TBXAI",     62,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7441:,		TempR,		"TBXAI",     64,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7442:,		TempR,		"TBXAI",     66,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare3:,		TempR,		"TBXAI",     68,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare4:,		TempR,		"TBXAI",     70,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7503:,		TempR,		"TBXAI",     72,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7501:,		TempR,		"TBXAI",     74,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7504:,		TempR,		"TBXAI",     76,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7502:,		TempR,		"TBXAI",     78,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7583:,		TempR,		"TBXAI",     80,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare5:,		TempR,		"TBXAI",     82,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare6:,		TempR,		"TBXAI",     84,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare7:,		TempR,		"TBXAI",     86,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7303:,		TempR,		"TBXAI",     88,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7343:,		TempR,		"TBXAI",     90,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare8:,		TempR,		"TBXAI",     92,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare9:,		TempR,		"TBXAI",     94,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare10:,	TempR,		"TBXAI",     96,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare11:,	TempR,		"TBXAI",     98,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare12:,	TempR,		"TBXAI",    100,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare13:,	TempR,		"TBXAI",    102,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7201:,		TempR,		"TBXAI",    104,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7202:,		TempR,		"TBXAI",    106,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7301:,		TempR,		"TBXAI",    108,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7302:,		TempR,		"TBXAI",    110,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7401:,		TempR,		"TBXAI",    112,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7402:,		TempR,		"TBXAI",    114,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TT7381:,		TempR,		"TBXAI",    116,     FLOAT32_BE, 0,      350,    1,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare14:,	TempR,		"TBXAI",    118,     FLOAT32_BE, 0,      25,     3,      "K",    	"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		PresR,		"TBXAI",    120,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		PresR,		"TBXAI",    122,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		PresR,		"TBXAI",    124,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		PresR,		"TBXAI_1",    0,     FLOAT32_BE, 0,      20,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7203:,		PresR,		"TBXAI_1",    2,     FLOAT32_BE, 0,      100,    2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		PresR,		"TBXAI_1",    4,     FLOAT32_BE, 0,      100,    2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7202:,		PresR,		"TBXAI_1",    6,     FLOAT32_BE, 0,      25,     1,      "mbara",    "1 second", "TBx Temp2"}
### Edited
{Cryo,	-CDL00:,	TBx01,	-PT7307:,		PresR,		"TBXAI_1",    8,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		PresR,		"TBXAI_1",   10,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}

{Cryo,	-CDL00:,	TBx01,	-PT7502:,		PresR,		"TBXAI_1",   12,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7302:,		PresR,		"TBXAI_1",   14,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7402:,		PresR,		"TBXAI_1",   16,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7544:,		PresR,		"TBXAI_1",   18,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7541:,		PresR,		"TBXAI_1",   20,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7341:,		PresR,		"TBXAI_1",   22,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7441:,		PresR,		"TBXAI_1",   24,     FLOAT32_BE, 0,      20,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7306:,		PresR,		"TBXAI_1",   26,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7304:,		PresR,		"TBXAI_1",   28,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7505:,		PresR,		"TBXAI_1",   30,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}

{Cryo,	-CDL00:,	TBx01,	-PT7503:,		PresR,		"TBXAI_1",   32,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		PresR,		"TBXAI_1",   34,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		PresR,		"TBXAI_1",   36,     FLOAT32_BE, 0,      20,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7545:,		PresR,		"TBXAI_1",   38,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7542:,		PresR,		"TBXAI_1",   40,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7243:,		PresR,		"TBXAI_1",   42,     FLOAT32_BE, 0,      100,    1,      "mbara",   "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7241:,		PresR,		"TBXAI_1",   44,     FLOAT32_BE, 0,      100,    1,      "mbara",   "1 second", "TBx Temp2"}

{Cryo,	-CDL00:,	TBx01,	-PT7242:,		PresR,		"TBXAI_1",   46,     FLOAT32_BE, 0,      25,     1,      "mbara",   "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7342:,		PresR,		"TBXAI_1",   48,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7442:,		PresR,		"TBXAI_1",   50,     FLOAT32_BE, 0,      20,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7546:,		PresR,		"TBXAI_1",   52,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7543:,		PresR,		"TBXAI_1",   54,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7343:,		PresR,		"TBXAI_1",   56,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7443:,		PresR,		"TBXAI_1",   58,     FLOAT32_BE, 0,      20,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		PresR,		"TBXAI_1",   60,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		PresR,		"TBXAI_1",   62,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7344:,		PresR,		"TBXAI_1",   64,     FLOAT32_BE, 0,      10,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7581:,		PresR,		"TBXAI_1",   66,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7382:,		PresR,		"TBXAI_1",   68,     FLOAT32_BE, 0,      25,     3,      "",		"1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI_1",   70,     FLOAT32_BE, 0,      25,     3,      "",        "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		PresR,		"TBXAI_1",   72,     FLOAT32_BE, 0,      25,     3,      "",        "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		FBRB,		"TBXAI_1",   74,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx GV7503 FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		FBRB,		"TBXAI_1",   76,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		FBRB,		"TBXAI_1",   78,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		FBRB,		"TBXAI_1",   80,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		FBRB,		"TBXAI_1",   82,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		FBRB,		"TBXAI_1",   84,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		FBRB,		"TBXAI_1",   86,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		FBRB,		"TBXAI_1",   88,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		FBRB,		"TBXAI_1",   90,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		FBRB,		"TBXAI_1",   92,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		FBRB,		"TBXAI_1",   94,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		FBRB,		"TBXAI_1",   96,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		FBRB,		"TBXAI_1",   98,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		FBRB,		"TBXAI_1",  100,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		FBRB,		"TBXAI_1",  102,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		FBRB,		"TBXAI_1",  104,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		FBRB,		"TBXAI_1",  106,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		FBRB,		"TBXAI_1",  108,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		FBRB,		"TBXAI_1",  110,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		FBRB,		"TBXAI_1",  112,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		FBRB,		"TBXAI_1",  114,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		FBRB,		"TBXAI_1",  116,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		FBRB,		"TBXAI_1",  118,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		FBRB,		"TBXAI_1",  120,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx FBRB"}
{Cryo,	-CDL00:,	TBx01,	-PDT7503:,		PresR,		"TBXAI_1",  122,     FLOAT32_BE, 0,      25,     3,      "mbara",       "1 second", "TBx Press"}
{Cryo,	-CDL00:,	TBx01,	-PDT7504:,		PresR,		"TBXAI_1",  124,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Press"}

{Cryo,	-CDL00:,	TBx01,	-PDT7501:,		PresR,		"TBXAI_2",    0,     FLOAT32_BE, 0,      150,    3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7502:,		PresR,		"TBXAI_2",	  2,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7301:,		PresR,		"TBXAI_2",    4,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7302:,		PresR,		"TBXAI_2",    6,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7401:,		PresR,		"TBXAI_2",    8,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7402:,		PresR,		"TBXAI_2",   10,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7543:,		PresR,		"TBXAI_2",   12,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7544:,		PresR,		"TBXAI_2",   14,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7541:,		PresR,		"TBXAI_2",   16,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7542:,		PresR,		"TBXAI_2",   18,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7341:,		PresR,		"TBXAI_2",   20,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7342:,		PresR,		"TBXAI_2",   22,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7441:,		PresR,		"TBXAI_2",   24,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7442:,		PresR,		"TBXAI_2",   26,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare1:,		PresR,		"TBXAI_2",   28,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare2:,		PresR,		"TBXAI_2",   30,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare3:,		PresR,		"TBXAI_2",   32,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		PresR,		"TBXAI_2",   34,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7508:,		PresR,		"TBXAI_2",   36,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7547:,		PresR,		"TBXAI_2",   38,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7548:,		PresR,		"TBXAI_2",   40,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		PresR,		"TBXAI_2",   42,     FLOAT32_BE, 0,      30,     2,      "bara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7483:,		PresR,		"TBXAI_2",   44,     FLOAT32_BE, 0,      20,     2,      "bara",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI_2",   46,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI_2",   48,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		FBRB,		"TBXAI_2",   50,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		FBRB,		"TBXAI_2",   52,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		FBRB,		"TBXAI_2",   54,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		FBRB,		"TBXAI_2",   56,     FLOAT32_BE, 0,      100,    1,      "%",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7505:,		PresR,		"TBXAI_2",   58,     FLOAT32_BE, 0,      25,     3,      "mbara",    "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7506:,		PresR,		"TBXAI_2",   60,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7545:,		PresR,		"TBXAI_2",   62,     FLOAT32_BE, 0,      25,     3,      "mbara",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7546:,		PresR,		"TBXAI_2",   64,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7581:,		PresR,		"TBXAI_2",   66,     FLOAT32_BE, 0,      25,     3,      "mbara",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PDT7582:,		PresR,		"TBXAI_2",   68,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7509:,		PresR,		"TBXAI_2",   70,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7549:,		PresR,		"TBXAI_2",   72,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PresR,		"TBXAI_2",   74,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PresR,		"TBXAI_2",   76,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}

{Cryo,	-CDL00:,	TBx01,	-PT7305:,		PresR,		"TBXAI_2",   78,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7204:,		PresR,		"TBXAI_2",   80,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		PresR,		"TBXAI_2",   82,     FLOAT32_BE, 0,      25,     3,      "K",       "1 second", "TBx Temp2"}
}                                                                   

####AO Base Address 400word(800 PLC offset(byte))
file "db/aoFloat64.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,			SIGNAL,			PORT,		OFFSET, DATA_TYPE,	LOPR,	HOPR,	PREC,	EGU,	DESC,	VAL}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		Setpt,			"TBXAO",	0,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		SetManuRamp,	"TBXAO",	2,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		Setpt,			"TBXAO",	4,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		SetManuRamp,	"TBXAO",	6,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		Setpt,			"TBXAO",	8,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		SetManuRamp,	"TBXAO",	10,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		Setpt,			"TBXAO",	12,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetManuRamp,	"TBXAO",	14,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		Setpt,			"TBXAO",	16,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		SetManuRamp,	"TBXAO",	18,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		Setpt,			"TBXAO",	20,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetManuRamp,	"TBXAO",	22,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		Setpt,			"TBXAO",	24,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetManuRamp,	"TBXAO",	26,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		Setpt,			"TBXAO",	28,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetManuRamp,	"TBXAO",	30,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		Setpt,			"TBXAO",	32,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		SetManuRamp,	"TBXAO",	34,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		Setpt,			"TBXAO",	36,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		SetManuRamp,	"TBXAO",	38,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		Setpt,			"TBXAO",	40,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		SetManuRamp,	"TBXAO",	42,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		Setpt,			"TBXAO",	44,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		SetManuRamp,	"TBXAO",	46,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		Setpt,			"TBXAO",	48,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetManuRamp,	"TBXAO",	50,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		Setpt,			"TBXAO",	52,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		SetManuRamp,	"TBXAO",	54,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		Setpt,			"TBXAO",	56,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		SetManuRamp,	"TBXAO",	58,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		Setpt,			"TBXAO",	60,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		SetManuRamp,	"TBXAO",	62,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		Setpt,			"TBXAO",	64,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetManuRamp,	"TBXAO",	66,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		Setpt,			"TBXAO",	68,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		SetManuRamp,	"TBXAO",	70,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		Setpt,			"TBXAO",	72,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetManuRamp,	"TBXAO",	74,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		Setpt,			"TBXAO",	76,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		SetManuRamp,	"TBXAO",	78,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		Setpt,			"TBXAO",	80,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		SetManuRamp,	"TBXAO",	82,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		Setpt,			"TBXAO",	84,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		SetManuRamp,	"TBXAO",	86,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		Setpt,			"TBXAO",	88,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		SetManuRamp,	"TBXAO",	90,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		Setpt,			"TBXAO",	92,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		SetManuRamp,	"TBXAO",	94,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		Setpt,			"TBXAO",	96,		FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetManuRamp,	"TBXAO",	98,		FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		Setpt,			"TBXAO",	100,	FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetManuRamp,	"TBXAO",	102,	FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		Setpt,			"TBXAO",	104,	FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		SetManuRamp,	"TBXAO",	106,	FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		Setpt,			"TBXAO",	108,	FLOAT32_BE,	0,		100,	1,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		SetManuRamp,	"TBXAO",	110,	FLOAT32_BE,	0,		10,		1,		"%/s",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7503:,		PressSet,		"TBXAO",	112,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7504:,		PressSet,		"TBXAO",	114,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7501:,		PressSet,		"TBXAO",	116,	FLOAT32_BE,	0,		150,	3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7502:,		PressSet,		"TBXAO",	118,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7301:,		PressSet,		"TBXAO",	120,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7302:,		PressSet,		"TBXAO",	122,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7401:,		PressSet,		"TBXAO",	  0,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7402:,		PressSet,		"TBXAO_1",	  2,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7543:,		PressSet,		"TBXAO_1",	  4,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7544:,		PressSet,		"TBXAO_1",	  6,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7541:,		PressSet,		"TBXAO_1",	  8,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7542:,		PressSet,		"TBXAO_1",	 10,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7341:,		PressSet,		"TBXAO_1",	 12,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7342:,		PressSet,		"TBXAO_1",	 14,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7441:,		PressSet,		"TBXAO_1",	 16,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7442:,		PressSet,		"TBXAO_1",	 18,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare1:,	PressSet,		"TBXAO_1",	 20,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare2:,	PressSet,		"TBXAO_1",	 22,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }
#{Cryo,	-CDL00:,	TBx01,	-PDTSpare3:,	PressSet,		"TBXAO_1",	 24,	FLOAT32_BE,	0,		30,		3,		"%",	"",	"0" }

###New list
{Cryo,	-CDL00:,	TBx01,	-TT7543:,		SetOVR,			"TBXAO_2",	0,		FLOAT32_BE,	"0",	"350",	"1",	 "",	 "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7541:,		SetOVR,			"TBXAO_2",	2,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7544:,		SetOVR,			"TBXAO_2",	4,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7542:,		SetOVR,			"TBXAO_2",	6,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		SetOVR,			"TBXAO_2",	8,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7582:,		SetOVR,			"TBXAO_2",	10,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare1:,		SetOVR,			"TBXAO_2",	12,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare2:,		SetOVR,			"TBXAO_2",	14,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7241:,		SetOVR,			"TBXAO_2",	16,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7242:,		SetOVR,			"TBXAO_2",	18,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7341:,		SetOVR,			"TBXAO_2",	20,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7342:,		SetOVR,			"TBXAO_2",	22,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7441:,		SetOVR,			"TBXAO_2",	24,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7242:,		SetOVR,			"TBXAO_2",	18,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare3:,		SetOVR,			"TBXAO_2",	28,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare4:,		SetOVR,			"TBXAO_2",	30,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7503:,		SetOVR,			"TBXAO_2",	32,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7501:,		SetOVR,			"TBXAO_2",	34,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7504:,		SetOVR,			"TBXAO_2",	36,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7502:,		SetOVR,			"TBXAO_2",	38,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7583:,		SetOVR,			"TBXAO_2",	40,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare5:,		SetOVR,			"TBXAO_2",	42,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare6:,		SetOVR,			"TBXAO_2",	44,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare7:,		SetOVR,			"TBXAO_2",	46,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7303:,		SetOVR,			"TBXAO_2",	48,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7343:,		SetOVR,			"TBXAO_2",	50,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare8:,		SetOVR,			"TBXAO_2",	52,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare9:,		SetOVR,			"TBXAO_2",	54,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare10:,	SetOVR,			"TBXAO_2",	56,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare11:,	SetOVR,			"TBXAO_2",	58,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare12:,	SetOVR,			"TBXAO_2",	60,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare13:,	SetOVR,			"TBXAO_2",	62,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7201:,		SetOVR,			"TBXAO_2",	64,	    FLOAT32_BE, "0",    "350",  "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7202:,		SetOVR,			"TBXAO_2",	66,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7301:,		SetOVR,			"TBXAO_2",	68,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7302:,		SetOVR,			"TBXAO_2",	70,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7401:,		SetOVR,			"TBXAO_2",	72,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7402:,		SetOVR,			"TBXAO_2",	74,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7381:,		SetOVR,			"TBXAO_2",	76,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TTSpare14:,	SetOVR,			"TBXAO_2",	78,	    FLOAT32_BE, "0",    "350", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7101:,		SetOVR,			"TBXAO_2",	80,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7102:,		SetOVR,			"TBXAO_2",	82,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7103:,		SetOVR,			"TBXAO_2",	84,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7104:,		SetOVR,			"TBXAO_2",	86,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		SetOVR,			"TBXAO_2",	88,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetOVR,			"TBXAO_2",	90,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7141:,		SetOVR,			"TBXAO_2",	92,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7142:,		SetOVR,			"TBXAO_2",	94,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7143:,		SetOVR,			"TBXAO_2",	96,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7144:,		SetOVR,			"TBXAO_2",	98,	    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVR,			"TBXAO_2",	100,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		SetOVR,			"TBXAO_2",	102,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		SetOVR,			"TBXAO_2",	104,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		SetOVR,			"TBXAO_2",	106,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		SetOVR,			"TBXAO_2",	108,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		SetOVR,			"TBXAO_2",	110,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7182:,		SetOVR,			"TBXAO_2",	112,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare4:,		SetOVR,			"TBXAO_2",	114,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		SetOVR,			"TBXAO_2",	116,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		SetOVR,			"TBXAO_2",	118,    FLOAT32_BE, "0",    "1100", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		SetOVR,			"TBXAO_2",	120,    FLOAT32_BE, "0",    "10",   "2",     "bara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		SetOVR,			"TBXAO_2",	122,    FLOAT32_BE, "0",    "20",   "2",     "bara",     "", "0" }

{Cryo,	-CDL00:,	TBx01,	-PT7203:,		SetOVR,			"TBXAO_3",	0,      FLOAT32_BE, "0",    "1000", "2",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		SetOVR,			"TBXAO_3",	2,		FLOAT32_BE, "0",    "1000", "1",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7202:,		SetOVR,			"TBXAO_3",	4,	    FLOAT32_BE, "0",    "1000", "1",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7307:,		SetOVR,			"TBXAO_3",	6,	    FLOAT32_BE, "0",    "10",   "2",     "bara",      "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		SetOVR,			"TBXAO_3",	8,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7502:,		SetOVR,			"TBXAO_3",	10,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7302:,		SetOVR,			"TBXAO_3",	12,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7402:,		SetOVR,			"TBXAO_3",	14,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7544:,		SetOVR,			"TBXAO_3",	16,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7541:,		SetOVR,			"TBXAO_3",	18,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7341:,		SetOVR,			"TBXAO_3",	20,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7441:,		SetOVR,			"TBXAO_3",	22,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7306:,		SetOVR,			"TBXAO_3",	24,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7304:,		SetOVR,			"TBXAO_3",	26,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7505:,		SetOVR,			"TBXAO_3",	28,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7503:,		SetOVR,			"TBXAO_3",	30,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		SetOVR,			"TBXAO_3",	32,	    FLOAT32_BE, "0",    "10",   "1",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		SetOVR,			"TBXAO_3",	34,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7545:,		SetOVR,			"TBXAO_3",	36,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7542:,		SetOVR,			"TBXAO_3",	38,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7243:,		SetOVR,			"TBXAO_3",	40,	    FLOAT32_BE, "0",    "1000", "1",     "mbara",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7241:,		SetOVR,			"TBXAO_3",	42,	    FLOAT32_BE, "0",    "1000", "1",     "mbara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7242:,		SetOVR,			"TBXAO_3",	44,	    FLOAT32_BE, "0",    "1000", "1",     "mbara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7342:,		SetOVR,			"TBXAO_3",	46,	    FLOAT32_BE, "0",    "10",   "2",     "bara",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7442:,		SetOVR,			"TBXAO_3",	48,	    FLOAT32_BE, "0",    "20",   "2",     "bara",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7546:,		SetOVR,			"TBXAO_3",	50,	    FLOAT32_BE, "0",    "30",   "2",     "bara",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7543:,		SetOVR,			"TBXAO_3",	52,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7343:,		SetOVR,			"TBXAO_3",	54,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7443:,		SetOVR,			"TBXAO_3",	56,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		SetOVR,			"TBXAO_3",	58,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		SetOVR,			"TBXAO_3",	60,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7344:,		SetOVR,			"TBXAO_3",	62,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7581:,		SetOVR,			"TBXAO_3",	64,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7382:,		SetOVR,			"TBXAO_3",	66,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVR,			"TBXAO_3",	68,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		SetOVR,			"TBXAO_3",	70,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7503:,		SetOVR,			"TBXAO_3",	72,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7504:,		SetOVR,			"TBXAO_3",	74,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7501:,		SetOVR,			"TBXAO_3",	76,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7502:,		SetOVR,			"TBXAO_3",	78,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7301:,		SetOVR,			"TBXAO_3",	80,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7302:,		SetOVR,			"TBXAO_3",	82,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7401:,		SetOVR,			"TBXAO_3",	84,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7402:,		SetOVR,			"TBXAO_3",	86,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7543:,		SetOVR,			"TBXAO_3",	88,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7544:,		SetOVR,			"TBXAO_3",	90,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7541:,		SetOVR,			"TBXAO_3",	92,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7542:,		SetOVR,			"TBXAO_3",	94,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7341:,		SetOVR,			"TBXAO_3",	96,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7342:,		SetOVR,			"TBXAO_3",	98,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7441:,		SetOVR,			"TBXAO_3",	100,	FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7442:,		SetOVR,			"TBXAO_3",	102,    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare1:,	SetOVR,			"TBXAO_3",	104,    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare2:,	SetOVR,			"TBXAO_3",	106,    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDTSpare3:,	SetOVR,			"TBXAO_3",	108,    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		SetOVR,			"TBXAO_3",	110,    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7508:,		SetOVR,			"TBXAO_3",	112,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7547:,		SetOVR,			"TBXAO_3",	114,    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7548:,		SetOVR,			"TBXAO_3",	116,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		SetOVR,			"TBXAO_3",	118,    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7483:,		SetOVR,			"TBXAO_3",	120,    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetOVR,			"TBXAO_3",	122,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVR,			"TBXAO_4",	0,      FLOAT32_BE, "0",    "1000", "1",     "",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7505:,		SetOVR,			"TBXAO_4",	2,      FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7506:,		SetOVR,			"TBXAO_4",	4,		FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7545:,		SetOVR,			"TBXAO_4",	6,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7546:,		SetOVR,			"TBXAO_4",	8,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7581:,		SetOVR,			"TBXAO_4",	10,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PDT7582:,		SetOVR,			"TBXAO_4",	12,	    FLOAT32_BE, "0",    "1000", "2",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7509:,		SetOVR,			"TBXAO_4",	14,	    FLOAT32_BE, "0",    "1000", "1",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7549:,		SetOVR,			"TBXAO_4",	16,	    FLOAT32_BE, "0",    "1000", "1",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetOVR,			"TBXAO_4",	18,	    FLOAT32_BE, "0",    "1000", "1",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVR,			"TBXAO_4",	20,	    FLOAT32_BE, "0",    "1000", "1",     "g/s",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		SetCP			"TBXAO_4",	22,	    FLOAT32_BE, "0",    "350", "1",      "",     "", "50"}
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		SetDelayTime,	"TBXAO_4",	24,	    FLOAT32_BE, "0",    "350", "1",      "",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		SetCP,			"TBXAO_4",	26,	    FLOAT32_BE, "0",    "30",  "2",      "bara", "", "21"}
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		SetDelayTime,	"TBXAO_4",	28,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7503:,		SetCP,			"TBXAO_4",	30,	    FLOAT32_BE, "0",    "30",  "2",      "bara", "", "21"}
{Cryo,	-CDL00:,	TBx01,	-PT7503:,		SetDelayTime,	"TBXAO_4",	32,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		SetCP,			"TBXAO_4",	34,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "20.5" }
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		SetDelayTime,	"TBXAO_4",	36,	    FLOAT32_BE, "0",    "100",  "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		SetCP,			"TBXAO_4",	38,	    FLOAT32_BE, "0",    "30",  "2",     "bara",  "", "20.5" }
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		SetDelayTime,	"TBXAO_4",	40,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		SetCP,			"TBXAO_4",	42,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "18.5" }
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		SetDelayTime,	"TBXAO_4",	44,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		SetCP,			"TBXAO_4",	46,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "8" }
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		SetDelayTime,	"TBXAO_4",	48,	    FLOAT32_BE, "0",    "100",  "1",     "s",    "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		SetCP,			"TBXAO_4",	50,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "8" }
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		SetDelayTime,	"TBXAO_4",	52,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		SetCP,			"TBXAO_4",	54,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "1.8" }
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		SetDelayTime,	"TBXAO_4",	56,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		SetCP,			"TBXAO_4",	58,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "1.8" }
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		SetDelayTime,	"TBXAO_4",	60,	    FLOAT32_BE, "0",    "100",  "1",     "s",    "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7305:,		SetCP,			"TBXAO_4",	62,	    FLOAT32_BE, "0",    "10",   "2",     "bara", "", "1.1" }
{Cryo,	-CDL00:,	TBx01,	-PT7305:,		SetDelayTime,	"TBXAO_4",	64,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		SetCP,			"TBXAO_4",	66,	    FLOAT32_BE, "0",    "100", "1",     "bara", "", "1.8" }
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		SetDelayTime,	"TBXAO_4",	68,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		SetCP,			"TBXAO_4",	70,	    FLOAT32_BE, "0",    "30",   "2",     "bara", "", "18.5" }
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		SetDelayTime,	"TBXAO_4",	72,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7483:,		SetCP,			"TBXAO_4",	74,	    FLOAT32_BE, "0",    "20",   "2",     "bara", "", "8" }
{Cryo,	-CDL00:,	TBx01,	-PT7483:,		SetDelayTime,	"TBXAO_4",	76,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		SetCP,			"TBXAO_4",	78,	    FLOAT32_BE, "0",    "10",  "2",     "bara",  "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		SetDelayTime,	"TBXAO_4",	80,	    FLOAT32_BE, "0",    "100", "1",     "s",     "", "0" }
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		SetCP,			"TBXAO_4",	86,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0.05" }
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		SetDelayTime,	"TBXAO_4",	88,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		SetCP,			"TBXAO_4",	90,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0.05" }
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		SetDelayTime,	"TBXAO_4",	92,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		SetCP,			"TBXAO_4",	94,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0.05" }
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		SetDelayTime,	"TBXAO_4",	96,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		SetCP,			"TBXAO_4",	98,	    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0.05" }
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		SetDelayTime,	"TBXAO_4",	100,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		SetCP,			"TBXAO_4",	102,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "0.05" }
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		SetDelayTime,	"TBXAO_4",	104,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }
##leesi
{Cryo,	-CDL00:,	TBx01,	-PT7305:,		SetOVR,			"TBXAO_4",	106,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }
{Cryo,	-CDL00:,	TBx01,	-PT7204:,		SetOVR,			"TBXAO_4",	108,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		SetOVR,			"TBXAO_4",	110,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }   
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetPGain,		"TBXAO_4",	112,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }   
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetIGain,		"TBXAO_4",	114,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetDGain,		"TBXAO_4",	116,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetMenu,		"TBXAO_4",	118,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetDeadBand,	"TBXAO_4",	120,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetCycleTime,	"TBXAO_4",	122,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetPGain,		"TBXAO_5",	  0,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetIGain,		"TBXAO_5",	  2,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetDGain,		"TBXAO_5",	  4,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }    
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetMenu,		"TBXAO_5",	  6,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }   
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetDeadBand,	"TBXAO_5",	  8,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }       
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetCycleTime,	"TBXAO_5",	 10,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }       
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetPGain,		"TBXAO_5",	 12,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetIGain,		"TBXAO_5",	 14,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetDGain,		"TBXAO_5",	 16,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetMenu,		"TBXAO_5",	 18,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetDeadBand,	"TBXAO_5",	 20,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetCycleTime,	"TBXAO_5",	 22,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetPGain,		"TBXAO_5",	 24,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetIGain,		"TBXAO_5",	 26,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetDGain,		"TBXAO_5",	 28,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetMenu,		"TBXAO_5",	 30,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetDeadBand,	"TBXAO_5",	 32,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetCycleTime,	"TBXAO_5",	 34,    FLOAT32_BE, "0",    "1000", "1",     "",     "", "3" }           

}

####BI Base Address 550(1100 PLC offset(byte))
file "db/biWord.template" { pattern
{SYS,	SUBSYS,		DEV, 	SUBDEV,			SIGNAL,				PORT,		OFFSET,	MASK,	 ZNAM,   ONAM,		SCAN,		DESC,		FLNK}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		OpenStat,			TBXDI,		0,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		CloseStat,			TBXDI,		0,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		OpenStat,			TBXDI,		0,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		CloseStat,			TBXDI,		0,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		OpenStat,			TBXDI,		0,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		CloseStat,			TBXDI,		0,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		OpenStat,			TBXDI,		0,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		CloseStat,			TBXDI,		0,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		OpenStat,			TBXDI,		0,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		CloseStat,			TBXDI,		0,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		OpenStat,			TBXDI,		0,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		CloseStat,			TBXDI,		0,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		OpenStat,			TBXDI,		0,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		CloseStat,			TBXDI,		0,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		OpenStat,			TBXDI,		0,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		CloseStat,			TBXDI,		0,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		OpenStat,			TBXDI,		1,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		CloseStat,			TBXDI,		1,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		OpenStat,			TBXDI,		1,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		CloseStat,			TBXDI,		1,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		OpenStat,			TBXDI,		1,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		CloseStat,			TBXDI,		1,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		OpenStat,			TBXDI,		1,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		CloseStat,			TBXDI,		1,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		OpenStat,			TBXDI,		1,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		CloseStat,			TBXDI,		1,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		OpenStat,			TBXDI,		1,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		CloseStat,			TBXDI,		1,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		OpenStat,			TBXDI,		1,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		CloseStat,			TBXDI,		1,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		OpenStat,			TBXDI,		1,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		CloseStat,			TBXDI,		1,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		OpenStat,			TBXDI,		2,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		CloseStat,			TBXDI,		2,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		OpenStat,			TBXDI,		2,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		CloseStat,			TBXDI,		2,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		OpenStat,			TBXDI,		2,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		CloseStat,			TBXDI,		2,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		OpenStat,			TBXDI,		2,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		CloseStat,			TBXDI,		2,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		OpenStat,			TBXDI,		2,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		CloseStat,			TBXDI,		2,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		OpenStat,			TBXDI,		2,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		CloseStat,			TBXDI,		2,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		OpenStat,			TBXDI,		2,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		CloseStat,			TBXDI,		2,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		OpenStat,			TBXDI,		2,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		CloseStat,			TBXDI,		2,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		OpenStat,			TBXDI,		3,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		CloseStat,			TBXDI,		3,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		OpenStat,			TBXDI,		3,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		CloseStat,			TBXDI,		3,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		OpenStat,			TBXDI,		3,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		CloseStat,			TBXDI,		3,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		OpenStat,			TBXDI,		3,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		CloseStat,			TBXDI,		3,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		OpenStat,			TBXDI,		3,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		CloseStat,			TBXDI,		3,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		OpenStat,			TBXDI,		3,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		CloseStat,			TBXDI,		3,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		OpenStat,			TBXDI,		3,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		CloseStat,			TBXDI,		3,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		3,		0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		3,		0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7502:,		OpenErrR,			TBXDI,		4,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		CloseErrR,			TBXDI,		4,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		OpenErrR,			TBXDI,		4,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		CloseErrR,			TBXDI,		4,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		OpenErrR,			TBXDI,		4,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		CloseErrR,			TBXDI,		4,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		OpenErrR,			TBXDI,		4,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		CloseErrR,			TBXDI,		4,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		OpenErrR,			TBXDI,		4,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		CloseErrR,			TBXDI,		4,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		OpenErrR,			TBXDI,		4,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		CloseErrR,			TBXDI,		4,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		OpenErrR,			TBXDI,		4,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		CloseErrR,			TBXDI,		4,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		OpenErrR,			TBXDI,		4,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		CloseErrR,			TBXDI,		4,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		OpenErrR,			TBXDI,		5,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		CloseErrR,			TBXDI,		5,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		OpenErrR,			TBXDI,		5,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		CloseErrR,			TBXDI,		5,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		OpenErrR,			TBXDI,		5,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		CloseErrR,			TBXDI,		5,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		OpenErrR,			TBXDI,		5,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		CloseErrR,			TBXDI,		5,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		OpenErrR,			TBXDI,		5,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		CloseErrR,			TBXDI,		5,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		OpenErrR,			TBXDI,		5,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		CloseErrR,			TBXDI,		5,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		OpenErrR,			TBXDI,		5,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		CloseErrR,			TBXDI,		5,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		OpenErrR,			TBXDI,		5,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		CloseErrR,			TBXDI,		5,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		OpenErrR,			TBXDI,		6,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		CloseErrR,			TBXDI,		6,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		OpenErrR,			TBXDI,		6,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		CloseErrR,			TBXDI,		6,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		OpenErrR,			TBXDI,		6,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		CloseErrR,			TBXDI,		6,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		OpenErrR,			TBXDI,		6,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		CloseErrR,			TBXDI,		6,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		OpenErrR,			TBXDI,		6,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		CloseErrR,			TBXDI,		6,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		OpenErrR,			TBXDI,		6,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		CloseErrR,			TBXDI,		6,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		OpenErrR,			TBXDI,		6,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		CloseErrR,			TBXDI,		6,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		OpenErrR,			TBXDI,		6,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		CloseErrR,			TBXDI,		6,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		OpenErrR,			TBXDI,		7,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		CloseErrR,			TBXDI,		7,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		OpenErrR,			TBXDI,		7,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		CloseErrR,			TBXDI,		7,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		OpenErrR,			TBXDI,		7,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		CloseErrR,			TBXDI,		7,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		OpenErrR,			TBXDI,		7,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		CloseErrR,			TBXDI,		7,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		OpenErrR,			TBXDI,		7,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		CloseErrR,			TBXDI,		7,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		OpenErrR,			TBXDI,		7,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		CloseErrR,			TBXDI,		7,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		OpenErrR,			TBXDI,		7,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		CloseErrR,			TBXDI,		7,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		7,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		7,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-CV7502:,		CloseStat,			TBXDI,		8,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		CloseStat,			TBXDI,		8,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		CloseStat,			TBXDI,		8,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		CloseStat,			TBXDI,		8,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		CloseStat,			TBXDI,		8,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		CloseStat,			TBXDI,		8,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		CloseStat,			TBXDI,		8,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		CloseStat,			TBXDI,		8,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		CloseStat,			TBXDI,		8,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		CloseStat,			TBXDI,		8,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		CloseStat,			TBXDI,		8,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		CloseStat,			TBXDI,		8,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		8,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-CV7502:,		CloseErrR,			TBXDI,		9,      0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		CloseErrR,			TBXDI,		9,      0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		CloseErrR,			TBXDI,		9,      0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		CloseErrR,			TBXDI,		9,      0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		CloseErrR,			TBXDI,		9,      0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		CloseErrR,			TBXDI,		9,      0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		CloseErrR,			TBXDI,		9,      0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		CloseErrR,			TBXDI,		9,      0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		CloseErrR,			TBXDI,		9,      0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		CloseErrR,			TBXDI,		9,      0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		CloseErrR,			TBXDI,		9,      0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		CloseErrR,			TBXDI,		9,      0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		9,      0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7502:,		ManuStat,			TBXDI,		10,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		ManuStat,			TBXDI,		10,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		ManuStat,			TBXDI,		10,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		ManuStat,			TBXDI,		10,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		ManuStat,			TBXDI,		10,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		ManuStat,			TBXDI,		10,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		ManuStat,			TBXDI,		10,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		ManuStat,			TBXDI,		10,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		ManuStat,			TBXDI,		10,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		ManuStat,			TBXDI,		10,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		ManuStat,			TBXDI,		10,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		ManuStat,			TBXDI,		10,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		ManuStat,			TBXDI,		10,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		ManuStat,			TBXDI,		10,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		ManuStat,			TBXDI,		10,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		ManuStat,			TBXDI,		10,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		ManuStat,			TBXDI,		11,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		ManuStat,			TBXDI,		11,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		ManuStat,			TBXDI,		11,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		ManuStat,			TBXDI,		11,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		ManuStat,			TBXDI,		11,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		ManuStat,			TBXDI,		11,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		ManuStat,			TBXDI,		11,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		ManuStat,			TBXDI,		11,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		ManuStat,			TBXDI,		11,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		ManuStat,			TBXDI,		11,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		ManuStat,			TBXDI,		11,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		ManuStat,			TBXDI,		11,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		ManuStat,			TBXDI,		11,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		ManuStat,			TBXDI,		11,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		ManuStat,			TBXDI,		11,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}

#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		11,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-CV7503:,		ManuStat,			TBXDI,		12,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		ErrStat,			TBXDI,		12,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		ManuStat,			TBXDI,		12,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		ErrStat,			TBXDI,		12,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		ManuStat,			TBXDI,		12,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		ErrStat,			TBXDI,		12,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		ManuStat,			TBXDI,		12,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		ErrStat,			TBXDI,		12,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		ManuStat,			TBXDI,		12,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		ErrStat,			TBXDI,		12,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		ManuStat,			TBXDI,		12,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		ErrStat,			TBXDI,		12,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		ManuStat,			TBXDI,		12,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		ErrStat,			TBXDI,		12,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		ManuStat,			TBXDI,		12,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		ErrStat,			TBXDI,		12,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-CV7303:,		ManuStat,			TBXDI,		13,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		ErrStat,			TBXDI,		13,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		ManuStat,			TBXDI,		13,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		ErrStat,			TBXDI,		13,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		ManuStat,			TBXDI,		13,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		ErrStat,			TBXDI,		13,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		ManuStat,			TBXDI,		13,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		ErrStat,			TBXDI,		13,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		ManuStat,			TBXDI,		13,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		ErrStat,			TBXDI,		13,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		ManuStat,			TBXDI,		13,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		ErrStat,			TBXDI,		13,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		ManuStat,			TBXDI,		13,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		ErrStat,			TBXDI,		13,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		ManuStat,			TBXDI,		13,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		ErrStat,			TBXDI,		13,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-CV7342:,		ManuStat,			TBXDI,		14,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		ErrStat,			TBXDI,		14,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		ManuStat,			TBXDI,		14,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		ErrStat,			TBXDI,		14,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		ManuStat,			TBXDI,		14,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		ErrStat,			TBXDI,		14,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		ManuStat,			TBXDI,		14,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		ErrStat,			TBXDI,		14,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		ManuStat,			TBXDI,		14,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		ErrStat,			TBXDI,		14,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		ManuStat,			TBXDI,		14,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		ErrStat,			TBXDI,		14,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		14,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-CV7582:,		ManuStat,			TBXDI,		15,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		ErrStat,			TBXDI,		15,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		ManuStat,			TBXDI,		15,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		ErrStat,			TBXDI,		15,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		ManuStat,			TBXDI,		15,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		ErrStat,			TBXDI,		15,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		ManuStat,			TBXDI,		15,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	"AutoStat"	}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		ErrStat,			TBXDI,		15,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		15,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		AutoStat,			TBXDI,		15,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		AutoStat,			TBXDI,		15,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		AutoStat,			TBXDI,		15,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		AutoStat,			TBXDI,		15,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-TP7103:,		SpdSet,				TBXDI,		16,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		NoErr,				TBXDI,		16,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		RemLoc,				TBXDI,		16,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		SPD,				TBXDI,		16,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		Mal,				TBXDI,		16,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		Warn,				TBXDI,		16,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		SpdSet,				TBXDI,		16,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		NoErr,				TBXDI,		16,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		RemLoc,				TBXDI,		16,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		SPD,				TBXDI,		16,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		Mal,				TBXDI,		16,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		Warn,				TBXDI,		16,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		16,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-TP7143:,		SpdSet,				TBXDI,		17,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		NoErr,				TBXDI,		17,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		RemLoc,				TBXDI,		17,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		SPD,				TBXDI,		17,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		Mal,				TBXDI,		17,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		Warn,				TBXDI,		17,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		SpdSet,				TBXDI,		17,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		NoErr,				TBXDI,		17,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		RemLoc,				TBXDI,		17,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		SPD,				TBXDI,		17,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		Mal,				TBXDI,		17,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		Warn,				TBXDI,		17,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		17,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-TP7181:,		SpdSet,				TBXDI,		18,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		NoErr,				TBXDI,		18,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		RemLoc,				TBXDI,		18,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		SPD,				TBXDI,		18,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		Mal,				TBXDI,		18,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		Warn,				TBXDI,		18,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		SpdSet,				TBXDI,		18,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		NoErr,				TBXDI,		18,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		RemLoc,				TBXDI,		18,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		SPD,				TBXDI,		18,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		Mal,				TBXDI,		18,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		Warn,				TBXDI,		18,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		18,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-DP7103:,		OnR,				TBXDI,		19,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		OffR,				TBXDI,		19,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		TripRstR,			TBXDI,		19,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		TripRPTC,			TBXDI,		19,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		OnR,				TBXDI,		19,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		OffR,				TBXDI,		19,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		TripRstR,			TBXDI,		19,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		TripRPTC,			TBXDI,		19,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		OnR,				TBXDI,		19,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		OffR,				TBXDI,		19,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		TripRstR,			TBXDI,		19,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		TripRPTC,			TBXDI,		19,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		OnR,				TBXDI,		19,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		OffR,				TBXDI,		19,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		TripRstR,			TBXDI,		19,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		TripRPTC,			TBXDI,		19,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-DP7181:,		OnR,				TBXDI,		20,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		OffR,				TBXDI,		20,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		TripRstR,			TBXDI,		20,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		TripRPTC,			TBXDI,		20,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		OnR,				TBXDI,		20,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		OffR,				TBXDI,		20,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		TripRstR,			TBXDI,		20,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		TripRPTC,			TBXDI,		20,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		20,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

{Cryo,	-CDL00:,	TBx01,	-XV7501:,		IntStatPT7501,		TBXDI,		21,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		IntStatPT7503,		TBXDI,		21,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		IntStatPT7504,		TBXDI,		21,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		IntStatPT7507,		TBXDI,		21,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		IntStatPT7401,		TBXDI,		21,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		IntStatPT7403,		TBXDI,		21,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		IntStatPT7301,		TBXDI,		21,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		IntStatPT7305,		TBXDI,		21,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		IntStatPT7201,		TBXDI,		21,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		IntStatPT7503,		TBXDI,		21,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		IntStatTT7581,		TBXDI,		21,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		IntStatPT7506,		TBXDI,		21,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		IntStatPT7381,		TBXDI,		21,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		IntStatPT7303,		TBXDI,		21,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		IntStatPT7381,		TBXDI,		21,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		IntStatPT7503,		TBXDI,		21,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		IntStatPT7582,		TBXDI,		22,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		IntStatPT7403,		TBXDI,		22,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		IntStatPT7483,		TBXDI,		22,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		IntStatPT7105,		TBXDI,		22,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		IntStatDP7102,		TBXDI,		22,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		IntStatTP7102,		TBXDI,		22,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		IntStatPT7106,		TBXDI,		22,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		IntStatDP7103,		TBXDI,		22,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		IntStatTP7103,		TBXDI,		22,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		IntStatPT7145,		TBXDI,		22,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		IntStatDP7142,		TBXDI,		22,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		IntStatTP7142,		TBXDI,		22,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		IntStatPT7146,		TBXDI,		22,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		IntStatDP7143,		TBXDI,		22,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		IntStatTP7143,		TBXDI,		22,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		IntStatPT7181,		TBXDI,		22,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		IntStatDP7181,		TBXDI,		23,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		IntStatTP7181,		TBXDI,		23,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		IntStatPT7105,		TBXDI,		23,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		IntStatDP7102,		TBXDI,		23,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		IntStatPT7106,		TBXDI,		23,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		IntStatDP7103,		TBXDI,		23,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		IntStatPT7145,		TBXDI,		23,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		IntStatDP7142,		TBXDI,		23,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		IntStatPT7146,		TBXDI,		23,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		IntStatDP7143,		TBXDI,		23,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		IntStatPT7181,		TBXDI,		23,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		IntStatDP7181,		TBXDI,		23,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}

#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		23,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		24,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0100,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0200,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0400,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0800,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x1000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x2000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x4000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x8000,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0001,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0002,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0004,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0008,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0010,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0020,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0040,  Open,   Close,     "I/O Intr", "Switch1",	""	}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDI,		25,     0x0080,  Open,   Close,     "I/O Intr", "Switch1",	""	}

}
##silee

####BO Base Address 576(550+26)(1152 PLC offset(byte))
file "db/boWord.template" { pattern
{SYS,	SUBSYS,		DEV, 	SUBDEV,			SIGNAL,				PORT,		OFFSET,	MASK,	 ZNAM,   ONAM,		DESC}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetManuOpen,		TBXDO,      0,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetManuClose,		TBXDO,      0,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetManuOpen,		TBXDO,      0,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetManuClose,		TBXDO,      0,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetManuOpen,		TBXDO,      0,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetManuClose,		TBXDO,      0,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetManuOpen,		TBXDO,      0,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetManuClose,		TBXDO,      0,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetManuOpen,		TBXDO,      0,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetManuClose,		TBXDO,      0,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetManuOpen,		TBXDO,      0,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetManuClose,		TBXDO,      0,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetManuOpen,		TBXDO,      0,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetManuClose,		TBXDO,      0,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetManuOpen,		TBXDO,      0,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetManuClose,		TBXDO,      0,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetManuOpen,		TBXDO,      1,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetManuClose,		TBXDO,      1,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetManuOpen,		TBXDO,      1,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetManuClose,		TBXDO,      1,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetManuOpen,		TBXDO,      1,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetManuClose,		TBXDO,      1,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetManuOpen,		TBXDO,      1,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetManuClose,		TBXDO,      1,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetManuOpen,		TBXDO,      1,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetManuClose,		TBXDO,      1,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetManuOpen,		TBXDO,      1,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetManuClose,		TBXDO,      1,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetManuOpen,		TBXDO,      1,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetManuClose,		TBXDO,      1,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetManuOpen,		TBXDO,      1,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetManuClose,		TBXDO,      1,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetManuOpen,		TBXDO,      2,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetManuClose,		TBXDO,      2,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetManuOpen,		TBXDO,      2,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetManuClose,		TBXDO,      2,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetManuOpen,		TBXDO,      2,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetManuClose,		TBXDO,      2,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetManuOpen,		TBXDO,      2,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetManuClose,		TBXDO,      2,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetManuOpen,		TBXDO,      2,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetManuClose,		TBXDO,      2,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetManuOpen,		TBXDO,      2,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetManuClose,		TBXDO,      2,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetManuOpen,		TBXDO,      2,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetManuClose,		TBXDO,      2,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetManuOpen,		TBXDO,      2,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetManuClose,		TBXDO,      2,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetManuOpen,		TBXDO,      3,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetManuClose,		TBXDO,      3,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetManuOpen,		TBXDO,      3,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetManuClose,		TBXDO,      3,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetManuOpen,		TBXDO,      3,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetManuClose,		TBXDO,      3,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetManuOpen,		TBXDO,      3,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetManuClose,		TBXDO,      3,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetManuOpen,		TBXDO,      3,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetManuClose,		TBXDO,      3,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetManuOpen,		TBXDO,      3,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetManuClose,		TBXDO,      3,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetManuOpen,		TBXDO,      3,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetManuClose,		TBXDO,      3,      0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      3,      0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      3,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetManuSel,			TBXDO,      4,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetFailRst,			TBXDO,      4,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetManuSel,			TBXDO,      4,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetFailRst,			TBXDO,      4,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetManuSel,			TBXDO,      4,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetFailRst,			TBXDO,      4,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetManuSel,			TBXDO,      4,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetFailRst,			TBXDO,      4,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetManuSel,			TBXDO,      4,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetFailRst,			TBXDO,      4,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetManuSel,			TBXDO,      4,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7302:,		SetFailRst,			TBXDO,      4,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetManuSel,			TBXDO,      4,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetFailRst,			TBXDO,      4,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetManuSel,			TBXDO,      4,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7543:,		SetFailRst,			TBXDO,      4,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetManuSel,			TBXDO,      5,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7541:,		SetFailRst,			TBXDO,      5,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetManuSel,			TBXDO,      5,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7341:,		SetFailRst,			TBXDO,      5,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetManuSel,			TBXDO,      5,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7441:,		SetFailRst,			TBXDO,      5,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetManuSel,			TBXDO,      5,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7241:,		SetFailRst,			TBXDO,      5,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetManuSel,			TBXDO,      5,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7343:,		SetFailRst,			TBXDO,      5,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetManuSel,			TBXDO,      5,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7344:,		SetFailRst,			TBXDO,      5,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetManuSel,			TBXDO,      5,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7544:,		SetFailRst,			TBXDO,      5,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetManuSel,			TBXDO,      5,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7542:,		SetFailRst,			TBXDO,      5,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetManuSel,			TBXDO,      6,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7342:,		SetFailRst,			TBXDO,      6,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetManuSel,			TBXDO,      6,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7442:,		SetFailRst,			TBXDO,      6,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetManuSel,			TBXDO,      6,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7242:,		SetFailRst,			TBXDO,      6,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetManuSel,			TBXDO,      6,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7381:,		SetFailRst,			TBXDO,      6,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetManuSel,			TBXDO,      6,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetFailRst,			TBXDO,      6,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetManuSel,			TBXDO,      6,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7545:,		SetFailRst,			TBXDO,      6,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetManuSel,			TBXDO,      6,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7581:,		SetFailRst,			TBXDO,      6,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetManuSel,			TBXDO,      6,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7104:,		SetFailRst,			TBXDO,      6,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetManuSel,			TBXDO,      7,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetFailRst,			TBXDO,      7,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetManuSel,			TBXDO,      7,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetFailRst,			TBXDO,      7,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetManuSel,			TBXDO,      7,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7144:,		SetFailRst,			TBXDO,      7,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetManuSel,			TBXDO,      7,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetFailRst,			TBXDO,      7,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetManuSel,			TBXDO,      7,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetFailRst,			TBXDO,      7,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetManuSel,			TBXDO,      7,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetFailRst,			TBXDO,      7,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetManuSel,			TBXDO,      7,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7182:,		SetFailRst,			TBXDO,      7,      0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      7,      0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      7,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7503:,		SetManuSel,			TBXDO,      8,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7503:,		SetFailRst,			TBXDO,      8,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		SetManuSel,			TBXDO,      8,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7501:,		SetFailRst,			TBXDO,      8,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		SetManuSel,			TBXDO,      8,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7301:,		SetFailRst,			TBXDO,      8,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetManuSel,			TBXDO,      8,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetFailRst,			TBXDO,      8,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		SetManuSel,			TBXDO,      8,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7201:,		SetFailRst,			TBXDO,      8,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetManuSel,			TBXDO,      8,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetFailRst,			TBXDO,      8,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetManuSel,			TBXDO,      8,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetFailRst,			TBXDO,      8,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetManuSel,			TBXDO,      8,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetFailRst,			TBXDO,      8,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7303:,		SetManuSel,			TBXDO,      9,      0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7303:,		SetFailRst,			TBXDO,      9,      0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		SetManuSel,			TBXDO,      9,      0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7544:,		SetFailRst,			TBXDO,      9,      0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		SetManuSel,			TBXDO,      9,      0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7542:,		SetFailRst,			TBXDO,      9,      0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		SetManuSel,			TBXDO,      9,      0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7341:,		SetFailRst,			TBXDO,      9,      0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetManuSel,			TBXDO,      9,      0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetFailRst,			TBXDO,      9,      0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		SetManuSel,			TBXDO,      9,      0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7241:,		SetFailRst,			TBXDO,      9,      0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		SetManuSel,			TBXDO,      9,      0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7545:,		SetFailRst,			TBXDO,      9,      0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		SetManuSel,			TBXDO,      9,      0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7344:,		SetFailRst,			TBXDO,      9,      0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetManuSel,			TBXDO,      10,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetFailRst,			TBXDO,      10,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		SetManuSel,			TBXDO,      10,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7343:,		SetFailRst,			TBXDO,      10,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetManuSel,			TBXDO,      10,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetFailRst,			TBXDO,      10,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		SetManuSel,			TBXDO,      10,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7541:,		SetFailRst,			TBXDO,      10,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		SetManuSel,			TBXDO,      10,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7505:,		SetFailRst,			TBXDO,      10,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		SetManuSel,			TBXDO,      10,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7543:,		SetFailRst,			TBXDO,      10,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		SetManuSel,			TBXDO,      10,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare1:,		SetFailRst,			TBXDO,      10,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		SetManuSel,			TBXDO,      10,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CVSpare2:,		SetFailRst,			TBXDO,      10,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetManuSel,			TBXDO,      11,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetFailRst,			TBXDO,      11,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetManuSel,			TBXDO,      11,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetFailRst,			TBXDO,      11,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		SetManuSel,			TBXDO,      11,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7581:,		SetFailRst,			TBXDO,      11,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		SetManuSel,			TBXDO,      11,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7481:,		SetFailRst,			TBXDO,      11,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		On,					TBXDO,      11,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		Off,				TBXDO,      11,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7103:,		TripRst,			TBXDO,      11,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		On,					TBXDO,      11,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		Off,				TBXDO,      11,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7102:,		TripRst,			TBXDO,      11,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		On,					TBXDO,      11,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7143:,		Off,				TBXDO,      11,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-DP7143:,		TripRst,			TBXDO,      12,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		On,					TBXDO,      12,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		Off,				TBXDO,      12,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7142:,		TripRst,			TBXDO,      12,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		On,					TBXDO,      12,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		Off,				TBXDO,      12,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7181:,		TripRst,			TBXDO,      12,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		On,					TBXDO,      12,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		Off,				TBXDO,      12,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-DP7182:,		TripRst,			TBXDO,      12,     0x0002,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0004,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0008,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0010,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      12,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7103:,		VentLc,				TBXDO,      13,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		TMPOnOff,			TBXDO,      13,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		DPOnOff,			TBXDO,      13,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		StnOnOff,			TBXDO,      13,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		ErrRstAut,			TBXDO,      13,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		Priority,			TBXDO,      13,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		VentLc,				TBXDO,      13,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		TMPOnOff,			TBXDO,      13,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		DPOnOff,			TBXDO,      13,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		StnOnOff,			TBXDO,      13,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		ErrRstAut,			TBXDO,      13,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		Priority,			TBXDO,      13,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      13,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7143:,		VentLc,				TBXDO,      14,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		TMPOnOff,			TBXDO,      14,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		DPOnOff,			TBXDO,      14,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		StnOnOff,			TBXDO,      14,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		ErrRstAut,			TBXDO,      14,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		Priority,			TBXDO,      14,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		VentLc,				TBXDO,      14,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		TMPOnOff,			TBXDO,      14,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		DPOnOff,			TBXDO,      14,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		StnOnOff,			TBXDO,      14,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		ErrRstAut,			TBXDO,      14,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		Priority,			TBXDO,      14,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      14,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TP7181:,		VentLc,				TBXDO,      15,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		TMPOnOff,			TBXDO,      15,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		DPOnOff,			TBXDO,      15,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		StnOnOff,			TBXDO,      15,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		ErrRstAut,			TBXDO,      15,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		Priority,			TBXDO,      15,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		VentLc,				TBXDO,      15,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		TMPOnOff,			TBXDO,      15,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		DPOnOff,			TBXDO,      15,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		StnOnOff,			TBXDO,      15,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		ErrRstAut,			TBXDO,      15,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7182:,		Priority,			TBXDO,      15,     0x0020,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x0040,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      15,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetIntRst,			TBXDO,      16,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetIntPT7501DS,		TBXDO,      16,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7501:,		SetIntPT7503DS,		TBXDO,      16,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetIntRst,			TBXDO,      16,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7502:,		SetIntPT7504DS,		TBXDO,      16,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetIntRst,			TBXDO,      16,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7503:,		SetIntPT7507DS,		TBXDO,      16,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetIntRst,			TBXDO,      16,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetIntPT7401DS,		TBXDO,      16,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7401:,		SetIntPT7403DS,		TBXDO,      16,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetIntRst,			TBXDO,      16,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7301:,		SetIntPT7301DS,		TBXDO,      16,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetIntRst,			TBXDO,      16,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7303:,		SetIntPT7305DS,		TBXDO,      16,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetIntRst,			TBXDO,      16,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7201:,		SetIntPT7201DS,		TBXDO,      16,     0x0080,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetIntRst,			TBXDO,      17,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetIntPT7503DS,		TBXDO,      17,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7502:,		SetIntTT7581DS,		TBXDO,      17,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetIntRst,		   	TBXDO,      17,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetIntPT7506DS,		TBXDO,      17,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7504:,		SetIntPT7381DS,		TBXDO,      17,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetIntRst,			TBXDO,      17,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetIntPT7303DS,		TBXDO,      17,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7304:,		SetIntPT7381DS,		TBXDO,      17,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetIntRst,			TBXDO,      17,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetIntPT7503DS,		TBXDO,      17,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7582:,		SetIntPT7582DS,		TBXDO,      17,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetIntRst,			TBXDO,      17,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetIntPT7403DS,		TBXDO,      17,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7482:,		SetIntPT7483DS,		TBXDO,      17,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		SetIntRst,			TBXDO,      17,     0x0080,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		IntStatPT7105DS,	TBXDO,      18,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		IntStatDP7102DS,	TBXDO,      18,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7102:,		IntStatTP7102DS,	TBXDO,      18,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		SetIntRst,			TBXDO,      18,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		IntStatPT7106DS,	TBXDO,      18,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		IntStatDP7103DS,	TBXDO,      18,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7103:,		IntStatTP7103DS,	TBXDO,      18,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		SetIntRst,			TBXDO,      18,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		IntStatPT7145DS,	TBXDO,      18,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		IntStatDP7142DS,	TBXDO,      18,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7142:,		IntStatTP7142DS,	TBXDO,      18,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		SetIntRst,			TBXDO,      18,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		IntStatPT7146DS,	TBXDO,      18,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		IntStatDP7143DS,	TBXDO,      18,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7143:,		IntStatTP7143DS,	TBXDO,      18,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		SetIntRst,   		TBXDO,      18,     0x0080,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		IntStatPT7181DS,	TBXDO,      19,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		IntStatDP7181DS,	TBXDO,      19,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-XV7181:,		IntStatTP7181DS,	TBXDO,      19,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		SetIntRst,		   	TBXDO,      19,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		IntStatPT7105DS,	TBXDO,      19,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7102:,		IntStatDP7102DS,	TBXDO,      19,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		SetIntRst,			TBXDO,      19,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		IntStatPT7106DS,	TBXDO,      19,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7103:,		IntStatDP7103DS,	TBXDO,      19,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		SetIntRst,		  	TBXDO,      19,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		IntStatPT7145DS,	TBXDO,      19,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7142:,		IntStatDP7142DS,	TBXDO,      19,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		SetIntRst,			TBXDO,      19,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		IntStatPT7146DS,	TBXDO,      19,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7143:,		IntStatDP7143DS,	TBXDO,      19,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		SetIntRst,			TBXDO,      19,     0x0080,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		IntStatPT7181DS,	TBXDO,      20,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TP7181:,		IntStatDP7181DS,	TBXDO,      20,     0x0200,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0400,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x0800,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x1000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-Reserve:,		Signal,				TBXDO,      20,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7543:,		SetOVREN,			TBXDO,      20,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7541:,		SetOVREN,			TBXDO,      20,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7544:,		SetOVREN,			TBXDO,      20,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7542:,		SetOVREN,			TBXDO,      20,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7581:,		SetOVREN,			TBXDO,      20,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7582:,		SetOVREN,			TBXDO,      20,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare1:,		SetOVREN,			TBXDO,      20,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare2:,		SetOVREN,			TBXDO,      20,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-TT7241:,		SetOVREN,			TBXDO,      21,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7242:,		SetOVREN,			TBXDO,      21,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7341:,		SetOVREN,			TBXDO,      21,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7342:,		SetOVREN,			TBXDO,      21,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7441:,		SetOVREN,			TBXDO,      21,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7442:,		SetOVREN,			TBXDO,      21,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare3:,		SetOVREN,			TBXDO,      21,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare4:,		SetOVREN,			TBXDO,      21,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7503:,		SetOVREN,			TBXDO,      21,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7501:,		SetOVREN,			TBXDO,      21,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7504:,		SetOVREN,			TBXDO,      21,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7502:,		SetOVREN,			TBXDO,      21,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7583:,		SetOVREN,			TBXDO,      21,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare5:,		SetOVREN,			TBXDO,      21,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare6:,		SetOVREN,			TBXDO,      21,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare7:,		SetOVREN,			TBXDO,      21,     0x0080,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7303:,		SetOVREN,			TBXDO,      22,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7343:,		SetOVREN,			TBXDO,      22,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare8:,		SetOVREN,			TBXDO,      22,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare9:,		SetOVREN,			TBXDO,      22,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare10:,	SetOVREN,			TBXDO,      22,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare11:,	SetOVREN,			TBXDO,      22,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare12:,	SetOVREN,			TBXDO,      22,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare13:,	SetOVREN,			TBXDO,      22,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7201:,		SetOVREN,			TBXDO,      22,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7202:,		SetOVREN,			TBXDO,      22,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7301:,		SetOVREN,			TBXDO,      22,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7302:,		SetOVREN,			TBXDO,      22,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7401:,		SetOVREN,			TBXDO,      22,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7402:,		SetOVREN,			TBXDO,      22,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TT7381:,		SetOVREN,			TBXDO,      22,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-TTSpare14:,	SetOVREN,			TBXDO,      22,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7101:,		SetOVREN,			TBXDO,      23,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7102:,		SetOVREN,			TBXDO,      23,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7103:,		SetOVREN,			TBXDO,      23,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7104:,		SetOVREN,			TBXDO,      23,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		SetOVREN,			TBXDO,      23,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetOVREN,			TBXDO,      23,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7141:,		SetOVREN,			TBXDO,      23,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7142:,		SetOVREN,			TBXDO,      23,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7143:,		SetOVREN,			TBXDO,      23,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7144:,		SetOVREN,			TBXDO,      23,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVREN,			TBXDO,      23,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		SetOVREN,			TBXDO,      23,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		SetOVREN,			TBXDO,      23,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		SetOVREN,			TBXDO,      23,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		SetOVREN,			TBXDO,      23,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		SetOVREN,			TBXDO,      23,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7182:,		SetOVREN,			TBXDO,      24,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare4:,		SetOVREN,			TBXDO,      24,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7504:,		SetOVREN,			TBXDO,      24,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7501:,		SetOVREN,			TBXDO,      24,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7301:,		SetOVREN,			TBXDO,      24,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7401:,		SetOVREN,			TBXDO,      24,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7203:,		SetOVREN,			TBXDO,      24,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7201:,		SetOVREN,			TBXDO,      24,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7202:,		SetOVREN,			TBXDO,      24,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7307:,		SetOVREN,			TBXDO,      24,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7506:,		SetOVREN,			TBXDO,      24,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7502:,		SetOVREN,			TBXDO,      24,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7302:,		SetOVREN,			TBXDO,      24,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7402:,		SetOVREN,			TBXDO,      24,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7544:,		SetOVREN,			TBXDO,      24,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7541:,		SetOVREN,			TBXDO,      24,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7341:,		SetOVREN,			TBXDO,      25,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7441:,		SetOVREN,			TBXDO,      25,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7306:,		SetOVREN,			TBXDO,      25,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7304:,		SetOVREN,			TBXDO,      25,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7505:,		SetOVREN,			TBXDO,      25,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7503:,		SetOVREN,			TBXDO,      25,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7303:,		SetOVREN,			TBXDO,      25,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7403:,		SetOVREN,			TBXDO,      25,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7545:,		SetOVREN,			TBXDO,      25,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7542:,		SetOVREN,			TBXDO,      25,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7243:,		SetOVREN,			TBXDO,      25,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7241:,		SetOVREN,			TBXDO,      25,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7242:,		SetOVREN,			TBXDO,      25,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7342:,		SetOVREN,			TBXDO,      25,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7442:,		SetOVREN,			TBXDO,      25,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7546:,		SetOVREN,			TBXDO,      25,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7543:,		SetOVREN,			TBXDO,      26,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7343:,		SetOVREN,			TBXDO,      26,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7443:,		SetOVREN,			TBXDO,      26,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7381:,		SetOVREN,			TBXDO,      26,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		SetOVREN,			TBXDO,      26,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7344:,		SetOVREN,			TBXDO,      26,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7581:,		SetOVREN,			TBXDO,      26,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7382:,		SetOVREN,			TBXDO,      26,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVREN,			TBXDO,      26,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		SetOVREN,			TBXDO,      26,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7503:,		SetOVREN,			TBXDO,      26,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7504:,		SetOVREN,			TBXDO,      26,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7501:,		SetOVREN,			TBXDO,      26,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7502:,		SetOVREN,			TBXDO,      26,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7301:,		SetOVREN,			TBXDO,      26,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7302:,		SetOVREN,			TBXDO,      26,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PDT7401:,		SetOVREN,			TBXDO,      27,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7402:,		SetOVREN,			TBXDO,      27,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7543:,		SetOVREN,			TBXDO,      27,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7544:,		SetOVREN,			TBXDO,      27,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7541:,		SetOVREN,			TBXDO,      27,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7542:,		SetOVREN,			TBXDO,      27,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7341:,		SetOVREN,			TBXDO,      27,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7342:,		SetOVREN,			TBXDO,      27,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7441:,		SetOVREN,			TBXDO,      27,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7442:,		SetOVREN,			TBXDO,      27,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare1:,	SetOVREN,			TBXDO,      27,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare2:,	SetOVREN,			TBXDO,      27,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDTSpare3:,	SetOVREN,			TBXDO,      27,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7507:,		SetOVREN,			TBXDO,      27,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7508:,		SetOVREN,			TBXDO,      27,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7547:,		SetOVREN,			TBXDO,      27,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7548:,		SetOVREN,			TBXDO,      28,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7582:,		SetOVREN,			TBXDO,      28,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7483:,		SetOVREN,			TBXDO,      28,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetOVREN,			TBXDO,      28,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVREN,			TBXDO,      28,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7505:,		SetOVREN,			TBXDO,      28,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7506:,		SetOVREN,			TBXDO,      28,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7545:,		SetOVREN,			TBXDO,      28,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7546:,		SetOVREN,			TBXDO,      28,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7581:,		SetOVREN,			TBXDO,      28,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PDT7582:,		SetOVREN,			TBXDO,      28,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7509:,		SetOVREN,			TBXDO,      28,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7549:,		SetOVREN,			TBXDO,      28,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		SetOVREN,			TBXDO,      28,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		SetOVREN,			TBXDO,      28,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7305:,		SetOVREN,			TBXDO,      28,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-PT7204:,		SetOVREN,			TBXDO,      29,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-PT7345:,		SetOVREN,			TBXDO,      29,     0x0200,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-PTReserve,							TBXDO,      29,     0x0400,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-PTReserve,							TBXDO,      29,     0x0800,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-PTReserve,							TBXDO,      29,     0x1000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-PTReserve,							TBXDO,      29,     0x2000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-PTReserve,							TBXDO,      29,     0x4000,  Open,   Close, "Switch1"}
#{Cryo,	-CDL00:,	TBx01,	-PTReserve,							TBXDO,      29,     0x8000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetDeadBandEN,		TBXDO,      29,     0x0001,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetPIDRst,			TBXDO,      29,     0x0002,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetPIDModeActiv,	TBXDO,      29,     0x0004,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7302:,		SetIntRst,			TBXDO,      29,     0x0008,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetDeadBandEN,		TBXDO,      29,     0x0010,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetPIDRst,			TBXDO,      29,     0x0020,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetPIDModeActiv,	TBXDO,      29,     0x0040,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7342:,		SetIntRst,			TBXDO,      29,     0x0080,  Open,   Close, "Switch1"}

{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetDeadBandEN,		TBXDO,      30,     0x0100,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetPIDRst,			TBXDO,      30,     0x0200,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetPIDModeActiv,	TBXDO,      30,     0x0400,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7401:,		SetIntRst,			TBXDO,      30,     0x0800,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetDeadBandEN,		TBXDO,      30,     0x1000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetPIDRst_2,		TBXDO,      30,     0x2000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetPIDModeActiv,	TBXDO,      30,     0x4000,  Open,   Close, "Switch1"}
{Cryo,	-CDL00:,	TBx01,	-CV7441:,		SetIntRst,			TBXDO,      30,     0x8000,  Open,   Close, "Switch1"}

}
###Cryo-CDL00:TBx01-PT7203:SetDelayTime	AO	s	1	0	100

###Cryo-CDL00:TBx01-PT7505:PresR	AI	bara	2	0	30 , Need Check

###Cryo-CDL00:TBx01-CV7201:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7241:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7301:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7302:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7303:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7304:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7341:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7342:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7343:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7344:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7401:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7441:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7481:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7482:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7501:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7502:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7503:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7504:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7505:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7541:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7542:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7543:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7544:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7545:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7581:SetManu	AO	%	1	0	100
###Cryo-CDL00:TBx01-CV7582:SetManu	AO	%	1	0	100

###Cryo-CDL00:TBx01-PT7101:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7102:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7103:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7104:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7105:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7106:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7141:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7142:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7143:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7144:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7145:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7146:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7181:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7182:SetAlm	AO	mbar	2	0	1100
###Cryo-CDL00:TBx01-PT7201:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7202:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7203:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7204:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7241:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7242:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7243:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7244:SetAlm	AO	mbara	1	0	TBD
###Cryo-CDL00:TBx01-PT7301:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7302:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7303:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7304:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7305:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7306:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7341:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7342:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7343:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7344:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7345:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7381:SetAlm	AO	bara	2	0	10
###Cryo-CDL00:TBx01-PT7401:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7402:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7403:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7441:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7442:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7443:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7483:SetAlm	AO	bara	2	0	20
###Cryo-CDL00:TBx01-PT7501:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7502:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7503:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7504:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7505:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7506:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7507:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7541:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7542:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7543:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7544:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7545:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7546:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7547:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7582:SetAlm	AO	bara	2	0	30
###Cryo-CDL00:TBx01-PT7583:SetAlm	AO	bara	2	0	30

