file "db/aiFloat64.template" { pattern
{SYS,	SUBSYS,		DEV,	SUBDEV,			SIGNAL,		PORT,		OFFSET, DATA_TYPE,	LOPR,	HOPR,	PREC,	EGU,		SCAN,		DESC}
{Cryo,	-CDL00:,	TBx01,	-PT7101:,		PressR,		"TBXAI",	0,		FLOAT32_BE,	0,		25,		3,		"mbar",		"1 second",	"TBx PT7101 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7102:,		PressR,		"TBXAI",	2,		FLOAT32_BE,	0,		25,		3,		"mbar",		"1 second",	"TBx PT7102 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7103:,		PressR,		"TBXAI",    4,      FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7103 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7104:,		PressR,		"TBXAI",    6,      FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7104 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7181:,		PressR,		"TBXAI",    8,      FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7181 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare1:,		PressR,		"TBXAI",    10,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PTSpare1 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7141:,		PressR,		"TBXAI",    12,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7141 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7142:,		PressR,		"TBXAI",    14,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7142 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7143:,		PressR,		"TBXAI",    16,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7143 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7144:,		PressR,		"TBXAI",    18,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7144 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare2:,		PressR,		"TBXAI",    20,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PTSpare2 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare3:,		PressR,		"TBXAI",    22,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PTSpare3 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7106:,		PressR,		"TBXAI",    24,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7106 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7105:,		PressR,		"TBXAI",    26,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7105 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7146:,		PressR,		"TBXAI",    28,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7146 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7145:,		PressR,		"TBXAI",    30,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7145 Press"}
{Cryo,	-CDL00:,	TBx01,	-PT7182:,		PressR,		"TBXAI",    32,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PT7182 Press"}
{Cryo,	-CDL00:,	TBx01,	-PTSpare4:,		PressR,		"TBXAI",    34,     FLOAT32_BE, 0,      25,     3,      "mbar",		"1 second", "TBx PTSpare4 Press"}
}



