sudo: required
dist: trusty
language: c
compiler:
  - gcc
env:
  - CMPLR=gcc
  - CMPLR=gcc EXTRA=CMD_CXXFLAGS=-std=c++11
  - CMPLR=gcc STATIC=YES
  - CMPLR=clang
  - CMPLR=clang STATIC=YES
  - WINE=32 TEST=NO STATIC=YES
  - RTEMS=4.10 TEST=YES
  - RTEMS=4.9 TEST=YES
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
    - bison
    - flex
    - texinfo
    - install-info
cache:
  directories:
   - $HOME/.cache
install: sh prepare-travis.sh </dev/null
script: sh build-travis.sh </dev/null
