#! /bin/sh

usage="Usage: trace [1-4]<CR>\n"
if [ $# -lt 1 ] || [ $1 -gt 4 ] || [ $1 -lt 1 ]
  then echo $usage
  exit 1
fi
file=/tmp/RF${1}Tek3054Trace1
if [ -f $file ]
then
   rm -f $file
fi
sddswmonitor -PVnames=S${1}:K:scaledTimeAxisWF,S${1}:K:chan1ScaledWaveWF,S${1}:K:chan2ScaledWaveWF,S${1}:K:chan3ScaledWaveWF,S${1}:K:chan4ScaledWaveWF $file 
ts=`caget -t S2:K:WF_timeStampTS`
sddsplot \
-col=S${1}:K:scaledTimeAxisWF,S${1}:K:chan1ScaledWaveWF \
-col=S${1}:K:scaledTimeAxisWF,S${1}:K:chan2ScaledWaveWF \
-col=S${1}:K:scaledTimeAxisWF,S${1}:K:chan3ScaledWaveWF \
-col=S${1}:K:scaledTimeAxisWF,S${1}:K:chan4ScaledWaveWF \
-grap=line,vary -sep=1 -layout=1,4 \
-title="$ts" \
-topTitle \
$file 

