TOP=../..

include $(TOP)/configure/CONFIG

LIBRARY_IOC += snap7
SRCS += s7_isotcp.cpp
SRCS += s7_micro_client.cpp
SRCS += s7_peer.cpp
SRCS += snap_msgsock.cpp
SRCS += snap_sysutils.cpp
INC += s7_isotcp.h
INC += s7_micro_client.h
INC += s7_peer.h
INC += s7_types.h
INC += snap_msgsock.h
INC += snap_platform.h
INC += snap_sysutils.h

include $(TOP)/configure/RULES
