TOP = ../..
include $(TOP)/configure/CONFIG

LIBRARY		+= ecat2

ecat2_SRCS += devethercat.c ecnode.c drvethercat.c eccfg.c ecengine.c ectimer.c ectools.c

#ec.h
#ecnode.h
#eccommon.h
#drvethercat.h
#ecrt.h
#ectimer.h  
#ectools.h
#drvethercatint.h
#eccfg.h
#ecdebug.h
#ecengine.h

DBD			+= drvethercat.dbd

include $(TOP)/configure/RULES
